### ISSUE TITLE
[TPU-Colab] RuntimeError: Cannot replicate if number of devices (1) is different from 8

### ISSUE THREAD

**Issue by simonepri** [PyTorchLightning/pytorch-lightning#1703] opened 2020-05-02 10:01 UTC
## 🐛 Bug

When I run `trainer.test(model)` on a pre-trained model using a Colab TPU instance, the following exception is thrown.
> NB: `trainer.train(model)` works.

### Stack trace
```
Traceback (most recent call last):
  File "run_pl_ged.py", line 217, in <module>
    trainer.test(model)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py", line 958, in test
    self.fit(model)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py", line 777, in fit
    xmp.spawn(self.tpu_train, args=(model,), nprocs=self.num_tpu_cores, start_method=start_method)
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 182, in spawn
    start_method=start_method)
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 116, in _start_fn
    _setup_replication()
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 109, in _setup_replication
    xm.set_replication(str(device), [str(device)])
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/core/xla_model.py", line 194, in set_replication
    replication_devices = xla_replication_devices(devices)
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/core/xla_model.py", line 181, in xla_replication_devices
    .format(len(local_devices), len(kind_devices)))
RuntimeError: Cannot replicate if number of devices (1) is different from 8
```

#### Code sample

```python
import pytorch_lightning as pl

model = MyLightningModule()
trainer = pl.Trainer(num_tpu_cores=8)
model = model.load_from_checkpoint(checkpoint)
model.prepare_data() # See https://github.com/PyTorchLightning/pytorch-lightning/issues/1562
trainer.test(model)
```

### Environment

Colab TPU instance with XLA 1.5

```
* CUDA:
	- GPU:
	- available:         False
	- version:           None
* Packages:
	- numpy:             1.18.3
	- pyTorch_debug:     False
	- pyTorch_version:   1.5.0a0+ab660ae
	- pytorch-lightning: 0.7.5
	- tensorboard:       2.2.1
	- tqdm:              4.38.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.6.9
	- version:           #1 SMP Wed Feb 19 05:26:34 PST 2020
```

Possibly related: https://github.com/PyTorchLightning/pytorch-lightning/pull/1019

**Comment by simonepri** [comment] 2020-05-26 22:47
Any update? Can I help somehow speeding this up?

**Comment by ArthDh** [comment] 2020-06-13 01:33
I was facing the same issue on a Colab TPU instance.
```
pytorch-lightning==0.7.6
torch==1.6.0a0+246d7bb
torch-xla==1.6+62b4c42
torchvision==0.7.0a0+c2e8a00
```

Using `trainer = pl.Trainer(resume_from_checkpoint=str(best_ckpt), num_tpu_cores=1)` 
followed by: `trainer.test(model)`

results in:

training on 1 TPU cores
INIT TPU local core: 0, global rank: 0
Exception in device=TPU:0: tensorflow/compiler/xla/xla_client/mesh_service.cc:259 : Check failed: impl_->channel->WaitForConnected( std::chrono::system_clock::now() + std::chrono::seconds(connect_wait_seconds)) 
*** Begin stack trace ***
	tensorflow::CurrentStackTrace[abi:cxx11]()
	xla::service::MeshClient::MeshClient(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
	xla::service::MeshClient::Get()
	
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	_PyFunction_FastCallDict
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	_PyFunction_FastCallDict
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	_PyFunction_FastCallDict
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	PyObject_Call
	
	Py_Main
	main
	__libc_start_main
	_start
*** End stack trace ***
Failed to connect to client mesh master: 06e59f028bed:60141
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 231, in _start_fn
    fn(gindex, *args)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/distrib_parts.py", line 535, in tpu_train
    self.run_pretrain_routine(model)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py", line 951, in run_pretrain_routine
    torch_xla.core.xla_model.rendezvous("pl.Trainer.run_pretrain_routine")
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/core/xla_model.py", line 679, in rendezvous
    return torch_xla._XLAC._xla_rendezvous(get_ordinal(), tag, payload, replicas)
RuntimeError: tensorflow/compiler/xla/xla_client/mesh_service.cc:259 : Check failed: impl_->channel->WaitForConnected( std::chrono::system_clock::now() + std::chrono::seconds(connect_wait_seconds)) 
*** Begin stack trace ***
	tensorflow::CurrentStackTrace[abi:cxx11]()
	xla::service::MeshClient::MeshClient(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
	xla::service::MeshClient::Get()
	
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	_PyFunction_FastCallDict
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	_PyFunction_FastCallDict
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	_PyFunction_FastCallDict
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	PyObject_Call
	
	Py_Main
	main
	__libc_start_main
	_start
*** End stack trace ***
Failed to connect to client mesh master: 06e59f028bed:60141
An exception has occurred, use %tb to see the full traceback.

**Comment by inidhinarayan** [comment] 2020-07-17 19:28
> I was facing the same issue on a Colab TPU instance.
> 
> ```
> pytorch-lightning==0.7.6
> torch==1.6.0a0+246d7bb
> torch-xla==1.6+62b4c42
> torchvision==0.7.0a0+c2e8a00
> ```
> 
> Using `trainer = pl.Trainer(resume_from_checkpoint=str(best_ckpt), num_tpu_cores=1)`
> followed by: `trainer.test(model)`
> 
> results in:
> 
> training on 1 TPU cores
> INIT TPU local core: 0, global rank: 0
> Exception in device=TPU:0: tensorflow/compiler/xla/xla_client/mesh_service.cc:259 : Check failed: impl_->channel->WaitForConnected( std::chrono::system_clock::now() + std::chrono::seconds(connect_wait_seconds))
> *** Begin stack trace ***
> tensorflow::CurrentStackTraceabi:cxx11
> xla::service::MeshClient::MeshClient(std::__cxx11::basic_string<char, std::char_traits, std::allocator > const&)
> xla::service::MeshClient::Get()
> 
> ```
> _PyEval_EvalFrameDefault
> 
> 
> 
> _PyEval_EvalFrameDefault
> 
> 
> _PyEval_EvalFrameDefault
> _PyFunction_FastCallDict
> 
> PyObject_Call
> _PyEval_EvalFrameDefault
> 
> 
> _PyEval_EvalFrameDefault
> 
> 
> 
> _PyEval_EvalFrameDefault
> 
> 
> 
> _PyEval_EvalFrameDefault
> 
> 
> 
> _PyEval_EvalFrameDefault
> 
> 
> 
> _PyEval_EvalFrameDefault
> 
> 
> 
> _PyEval_EvalFrameDefault
> 
> 
> 
> _PyEval_EvalFrameDefault
> 
> _PyFunction_FastCallDict
> 
> PyObject_Call
> _PyEval_EvalFrameDefault
> 
> 
> 
> _PyEval_EvalFrameDefault
> 
> 
> 
> _PyEval_EvalFrameDefault
> 
> 
> _PyEval_EvalFrameDefault
> 
> 
> _PyEval_EvalFrameDefault
> 
> 
> PyObject_Call
> _PyEval_EvalFrameDefault
> 
> 
> PyObject_Call
> _PyEval_EvalFrameDefault
> 
> 
> 
> _PyEval_EvalFrameDefault
> 
> 
> _PyEval_EvalFrameDefault
> _PyFunction_FastCallDict
> 
> PyObject_Call
> _PyEval_EvalFrameDefault
> 
> 
> 
> _PyEval_EvalFrameDefault
> 
> 
> _PyEval_EvalFrameDefault
> 
> 
> _PyEval_EvalFrameDefault
> 
> 
> 
> _PyEval_EvalFrameDefault
> 
> 
> 
> _PyEval_EvalFrameDefault
> 
> 
> 
> _PyEval_EvalFrameDefault
> 
> 
> PyObject_Call
> 
> Py_Main
> main
> __libc_start_main
> _start
> ```
> 
> *** End stack trace ***
> Failed to connect to client mesh master: 06e59f028bed:60141
> Traceback (most recent call last):
> File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 231, in _start_fn
> fn(gindex, *args)
> File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/distrib_parts.py", line 535, in tpu_train
> self.run_pretrain_routine(model)
> File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py", line 951, in run_pretrain_routine
> torch_xla.core.xla_model.rendezvous("pl.Trainer.run_pretrain_routine")
> File "/usr/local/lib/python3.6/dist-packages/torch_xla/core/xla_model.py", line 679, in rendezvous
> return torch_xla._XLAC._xla_rendezvous(get_ordinal(), tag, payload, replicas) RuntimeError: tensorflow/compiler/xla/xla_client/mesh_service.cc:259 : Check failed: impl_->channel->WaitForConnected( std::chrono::system_clock::now() + std::chrono::seconds(connect_wait_seconds))
> *** Begin stack trace ***
> tensorflow::CurrentStackTraceabi:cxx11
> xla::service::MeshClient::MeshClient(std::__cxx11::basic_string<char, std::char_traits, std::allocator > const&)
> xla::service::MeshClient::Get()
> 
> ```
> _PyEval_EvalFrameDefault
> 
> 
> 
> _PyEval_EvalFrameDefault
> 
> 
> _PyEval_EvalFrameDefault
> _PyFunction_FastCallDict
> 
> PyObject_Call
> _PyEval_EvalFrameDefault
> 
> 
> _PyEval_EvalFrameDefault
> 
> 
> 
> _PyEval_EvalFrameDefault
> 
> 
> 
> _PyEval_EvalFrameDefault
> 
> 
> 
> _PyEval_EvalFrameDefault
> 
> 
> 
> _PyEval_EvalFrameDefault
> 
> 
> 
> _PyEval_EvalFrameDefault
> 
> 
> 
> _PyEval_EvalFrameDefault
> 
> _PyFunction_FastCallDict
> 
> PyObject_Call
> _PyEval_EvalFrameDefault
> 
> 
> 
> _PyEval_EvalFrameDefault
> 
> 
> 
> _PyEval_EvalFrameDefault
> 
> 
> _PyEval_EvalFrameDefault
> 
> 
> _PyEval_EvalFrameDefault
> 
> 
> PyObject_Call
> _PyEval_EvalFrameDefault
> 
> 
> PyObject_Call
> _PyEval_EvalFrameDefault
> 
> 
> 
> _PyEval_EvalFrameDefault
> 
> 
> _PyEval_EvalFrameDefault
> _PyFunction_FastCallDict
> 
> PyObject_Call
> _PyEval_EvalFrameDefault
> 
> 
> 
> _PyEval_EvalFrameDefault
> 
> 
> _PyEval_EvalFrameDefault
> 
> 
> _PyEval_EvalFrameDefault
> 
> 
> 
> _PyEval_EvalFrameDefault
> 
> 
> 
> _PyEval_EvalFrameDefault
> 
> 
> 
> _PyEval_EvalFrameDefault
> 
> 
> PyObject_Call
> 
> Py_Main
> main
> __libc_start_main
> _start
> ```
> 
> *** End stack trace ***
> Failed to connect to client mesh master: 06e59f028bed:60141
> An exception has occurred, use %tb to see the full traceback.

Did u get any solution? I am facing the same issue

**Comment by ArthDh** [comment] 2020-07-20 00:51
Hi @inidhinarayan, I couldn't find a way around it. You might want to try with the latest repo!

**Comment by edenlightning** [comment] 2020-08-03 22:27
@nidhinarayan can you let us know if this is still happening on master?

**Comment by Borda** [comment] 2020-08-04 17:55
it shall be fixed on master, feel free to reopen if needed 🐰

**Closed by Borda** 2020-08-04 17:55 UTC
Labels: Priority, TPU, bug / fix, help wanted

**Comment by lezwon** [comment] 2020-08-15 16:50
I spent some time debugging this issue. I suspect the problem occurs as lightning loads `xla weights` back on the device. The weights are saved by the master device `xla:1` during training. When reloading, these weights are automatically moved back to `xla:1`.  When this happens the current process automatically acquires only one TPU core and considers it as a TPU device. Any attempt to call `xmp.spawn` after this will result in the given error.

To fix this issue we need to save weights using `xm.save()` instead of `torch.save`. This is will transfer the weights to a cpu device before saving. This issue is related to https://github.com/PyTorchLightning/pytorch-lightning/pull/2726

**Comment by mobassir94** [comment] 2021-01-01 09:35
@lezwon  i tried xm.save() and still i am getting the same error,
if i try the command below for installing xla then i get error **RuntimeError: Cannot replicate if number of devices (1) is different from 8**
 

```
!python3.7 -m pip install --upgrade pip
!pip install torch==1.7.0
!pip install torchvision 
!pip install cloud-tpu-client==0.10 https://storage.googleapis.com/tpu-pytorch/wheels/torch_xla-1.7-cp37-cp37m-linux_x86_64.whl
 
```

but same baseline notebook works for me if i try the command below instead for installing xla : 

```
!curl https://raw.githubusercontent.com/pytorch/xla/master/contrib/scripts/env-setup.py -o pytorch-xla-env-setup.py
!python pytorch-xla-env-setup.py --version "nightly"
```

i am working on tpu v3-8 that kaggle provides but i can't go beyond 1x8 = 8 batch size for the same model that can take batch size as 16 on kaggle free gpu,also for same model if we use tf tpu v3-8 then we can pass batch size = 8x16
i am a pytorch lover but because of this massive disadvantage of xla i am forced to use tf tpu :(

**Comment by sapthrishi** [comment] 2021-02-26 13:05
Am still facing this issue today

**Comment by LisburnLad** [comment] 2021-04-17 10:51
I'm experiencing the same issue with the [Lightning TPU example notebook] (https://colab.research.google.com/github/PytorchLightning/pytorch-lightning/blob/master/notebooks/06-mnist-tpu-training.ipynb), run on Colab.

Both the single TPU core examples work, but when trying to run on 8 cores I get the error:

"RuntimeError: Cannot replicate if number of devices (1) is different from 8"

**Comment by Sanjay03079** [comment] 2021-05-05 20:26
Having the same issue with a kaggle kernel .

**Comment by Sanjay03079** [comment] 2021-05-05 20:26
Exception in device=TPU:0: Cannot replicate if number of devices (1) is different from 8
Traceback (most recent call last):
Exception in device=TPU:1: Cannot replicate if number of devices (1) is different from 8  File "/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 330, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)

**Comment by lezwon** [comment] 2021-05-16 09:02
@LisburnLad @Sanjay03079 did you run 
`trainer = pl.Trainer(max_epochs=3, progress_bar_refresh_rate=20, tpu_cores=[5])`
before you ran
`trainer = pl.Trainer(max_epochs=3, progress_bar_refresh_rate=20, tpu_cores=8)`
?

**Comment by talhaanwarch** [comment] 2021-06-14 15:14
@lezwon i run this `trainer = pl.Trainer(max_epochs=3, progress_bar_refresh_rate=20, tpu_cores=8)` only and tried to restart kernal also. but it did not work

**Comment by daniellepintz** [comment] 2021-10-11 22:55
I am experiencing the same issue in #9712. https://app.circleci.com/pipelines/github/PyTorchLightning/pytorch-lightning/44836/workflows/20f3cc67-3596-4d27-8ecb-c909a3cf6577/jobs/132588/parallel-runs/0/steps/0-119

@Borda any insight here?

**Comment by satpalsr** [comment] 2022-06-03 05:31
I confirm the problem still exists.

**Comment by kaushikb11** [comment] 2022-07-01 22:21
@satpalsr Could you share your reproducible script for the bug? I could take a look.

**Comment by JessicaLopezEspejel** [comment] 2022-08-15 15:55
Hello, any news? I am facing the same problem.
