### ISSUE TITLE
NoneType datamodule/train_dataloader reference in `self.trainer`

### ISSUE THREAD

**Issue by rharish101** [PyTorchLightning/pytorch-lightning#10275] opened 2021-10-31 07:53 UTC
## 🐛 Bug

`self.trainer.datamodule` and `self.trainer.train_dataloader` are both `None` inside `configure_optimizers` for `LightningModule`.

### To Reproduce

```python
import os

import torch
from torch.utils.data import DataLoader, Dataset

from pytorch_lightning import LightningModule, Trainer


class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return {"loss": loss}

    def validation_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("valid_loss", loss)

    def test_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("test_loss", loss)

    def configure_optimizers(self):
        # Both the below lines fail
        print(len(self.trainer.datamodule.train_dataloader()))
        print(len(self.trainer.train_dataloader()))
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)


def run():
    train_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    val_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    test_data = DataLoader(RandomDataset(32, 64), batch_size=2)

    model = BoringModel()
    trainer = Trainer(
        default_root_dir=os.getcwd(),
        limit_train_batches=1,
        limit_val_batches=1,
        num_sanity_val_steps=0,
        max_epochs=1,
    )
    trainer.fit(model, train_dataloaders=train_data, val_dataloaders=val_data)
    trainer.test(model, dataloaders=test_data)


if __name__ == "__main__":
    run()

```

### Expected behavior

I should get the reference to the training dataloader.

### Environment

- PyTorch Lightning Version (e.g., 1.3.0): 1.4.9
- PyTorch Version (e.g., 1.8): 1.9.1+cu102
- Python version: 3.8.5
- OS (e.g., Linux): Linux
- CUDA/cuDNN version: 10.2
- GPU models and configuration: NVIDIA GeForce GTX 960M
- How you installed PyTorch (`conda`, `pip`, source): pip
- If compiling from source, the output of `torch.__config__.show()`:
- Any other relevant information:

### Additional context

According to the [datamodule section in the documentation for LightningModule](https://pytorch-lightning.readthedocs.io/en/latest/common/lightning_module.html#datamodule), this should work.

**Comment by SkafteNicki** [comment] 2021-10-31 14:59
I can confirm that `self.trainer.train_dataloader` is `None` inside `configure_optimizers`, however if I pass in a datamodule like this (adjusted version of the script provided):
```python
class CustomDataModule(LightningDataModule):
        def train_dataloader(self):
            return train_data

        def val_dataloader(self):
            return val_data

        def test_data(self):
            return test_data
    ...
    trainer.fit(model, datamodule=CustomDataModule())
```
then `self.trainer.datamodule` is correctly setup. It happens in these lines:
https://github.com/PyTorchLightning/pytorch-lightning/blob/cb8a2165a3e4418670d0caa334da99b016d488e3/pytorch_lightning/trainer/connectors/data_connector.py#L244-L245
which are missing from the corresponding method for setting up the dataloader:
https://github.com/PyTorchLightning/pytorch-lightning/blob/cb8a2165a3e4418670d0caa334da99b016d488e3/pytorch_lightning/trainer/connectors/data_connector.py#L200-L201

**Comment by rharish101** [comment] 2021-10-31 15:07
Thanks, passing in a datamodule worked!

> which are missing from the corresponding method for setting up the dataloader:

So there's still a bug, right? I could create a PR to solve it. I have a question, though: should the dataloaders be attached to `self.trainer` (within `DataConnector`) by creating a new datamodule within `attach_dataloaders`, similar to `attach_datamodule`? That way, the docs can stay the same. I was thinking of doing something along the lines of `LightningDataModule.from_datasets`:
https://github.com/PyTorchLightning/pytorch-lightning/blob/cb8a2165a3e4418670d0caa334da99b016d488e3/pytorch_lightning/core/datamodule.py#L400-L407

**Comment by rohitgr7** [comment] 2021-10-31 20:14
one workaround
```py
def configure_optimizers(self):
    self.trainer.reset_train_dataloader(self)
    self.trainer.train_dataloader  # now accessible :)
```
the reason being the dataloaders are not initialized until `configure_optimizers` is called. They are just referenced. So unless and until there is any initialization, the trainer won't have any dataloaders attached to it.

@awaelchli do you think it's viable to do the first initialization outside fit_loop inside `trainer.py` before we initialize optimizers/schedulers?

**Comment by awaelchli** [comment] 2021-12-01 10:19
This will be addressed by #10430

**Comment by rohitgr7** [comment] 2021-12-01 10:41
@awaelchli I think all of these issues will be solved by this one: https://github.com/PyTorchLightning/pytorch-lightning/issues/10760, BC that's the end goal.

**Closed** 2021-12-01 10:42 UTC
Labels: bug, help wanted

**Comment by awaelchli** [comment] 2021-12-01 10:52
I disagree, this issue is about #10430 and it is a requirement for #10760 if I understand correctly.
