### ISSUE TITLE
k-fold cross validation using DataModule

### ISSUE THREAD

**Issue by celsofranssa** [PyTorchLightning/pytorch-lightning#4287] opened 2020-10-21 14:57 UTC
DataModule is great! 
I'm wondering how it can be applied to handle with k-fold cross-validation.

**Comment by rohitgr7** [comment] 2020-10-21 18:41
all k models and datamodules will be independent so create seperate datamodules and models for each.

**Comment by ananyahjha93** [comment] 2020-10-21 22:45
I think there is a discussion of having a cross validation feature in Lightning in #839.

**Comment by ananyahjha93** [comment] 2020-10-21 22:49
@SkafteNicki @Borda @justusschock tagging you guys here as well.

**Closed** 2021-02-09 23:46 UTC
Labels: data / DataModule, duplicate, enhancement, help wanted, question

**Comment by Svito-zar** [comment] 2021-03-09 10:16
Has this feature been implemented yet?
I could not find it in the documentation ...

**Comment by SkafteNicki** [comment] 2021-03-09 10:38
@Svito-zar not implemented, closed due to being a duplicate of #839

**Comment by macabdul9** [comment] 2021-06-03 15:40
Any update on this?
