### ISSUE TITLE
Inherit from Callback throws missing Trainer argument

### ISSUE THREAD

**Issue by NumesSanguis** [PyTorchLightning/pytorch-lightning#4182] opened 2020-10-16 03:10 UTC
## 🐛 Bug

The PL 1.0.x update has removed the `trainer` argument from `TrainerCallbackHookMixin` when calling e.g. `callback.on_init_start(self)`. However, `Callback` has not been updated for this change. This results in a missing argument `trainer`.

- `TrainerCallbackHookMixin` link: https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/trainer/callback_hook.py#L42
- `Callback` link: https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/callbacks/base.py#L38

## Please reproduce using [the BoringModel and post here](https://colab.research.google.com/drive/1HvWVVTK8j2Nj52qU4Q4YCyzOm0_aLQF3?usp=sharing)

BoringModel colab: https://colab.research.google.com/drive/1i38oUFbnkgmgamMk6Jc4zpc9BrF31ZfE?usp=sharing

### To Reproduce

BoringModel

### Expected behavior

Not throw an error when using `class MyPrintingCallback(Callback)`

### Actual behavior
```python
TypeError                                 Traceback (most recent call last)

<ipython-input-13-1f9f6fbe4f6c> in <module>()
----> 1 test_x(tmpdir)

3 frames

/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/callback_hook.py in on_init_start(self)
     40         """Called when the trainer initialization begins, model has not yet been set."""
     41         for callback in self.callbacks:
---> 42             callback.on_init_start(self)
     43 
     44     def on_init_end(self):

TypeError: on_init_start() missing 1 required positional argument: 'trainer'
```

### Environment

 - PyTorch Version (e.g., 1.0): 1.0.2
 - OS (e.g., Linux): Google Colab

**Comment by nateraw** [comment] 2020-10-16 03:16
possible duplicate of #3813? Not sure if rooted entirely in same issue

**Comment by NumesSanguis** [comment] 2020-10-16 11:26
Sorry, it seems I didn't save the modifications to show the bug. I was not allowed to save, because I didn't copy the notebook. The link in the original post has been updated.

**Comment by ydcjeff** [comment] 2020-10-16 15:51
@NumesSanguis you need to call your custom callback class
```py
        callbacks=[MyPrintingCallback()] # needs ()
```

**Comment by awaelchli** [comment] 2020-10-16 17:32
@ydcjeff is right, his fix works

**Closed by awaelchli** 2020-10-16 17:32 UTC
Labels: bug / fix, help wanted

**Comment by NumesSanguis** [comment] 2020-10-17 08:46
Yup, can confirm that this was the issue.
