### ISSUE TITLE
How to implement Weighted DistributedSampler?

### ISSUE THREAD

**Issue by marsggbo** [PyTorchLightning/pytorch-lightning#10946] opened 2021-12-05 14:20 UTC
### Motivation

My dataset is highly imbalanced, and now I want to use `ddp` mode to train my model.

I've implemented the `WeightedRandomSampler`, and I wonder how can I merge it to `DistributedSampler`?

cc @borda

**Comment by tchaton** [comment] 2021-12-06 10:20
Hey @marsggbo,

This issue would be better suited on PyTorch itself.

However, DistributedSampler isn't too complex. It would simplify chunk the dataset for each rank. You could do exactly the same once you have generated the indices used to load the samples in a random weighted manner.

**Comment by tchaton** [comment] 2022-01-06 07:23
Hey @marsggbo,

It is possible to convert a sampler into its distributed version. Here is the code

```py
from typing import Iterator
from torch.utils.data import RandomSampler, DistributedSampler, Dataset
from torch.utils.data.sampler import SequentialSampler

data = range(10)

sampler = SequentialSampler(data)

print([i for i in sampler])
assert [i for i in sampler] == [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

class SamplerIterator:

    def __init__(self, sampler):
        self.sampler = sampler

    def __iter__(self):
        for item in self.sampler:
            yield item

    def __len__(self):
        return len(self.sampler)

def sampler_to_distributed(sampler, num_replicas, rank):
    return DistributedSampler(SamplerIterator(sampler), num_replicas=num_replicas, rank=rank, shuffle=False)


distributed_sampler_0 = sampler_to_distributed(sampler, 2, 0)
distributed_sampler_1 = sampler_to_distributed(sampler, 2, 1)

print()
print(0, [i for i in distributed_sampler_0])
assert [i for i in sampler] == [0, 2, 4, 6, 8]
print()
print(1, [i for i in distributed_sampler_1])
assert [i for i in sampler] == [1, 3, 5, 7, 9]
print()
```

**Comment by carmocca** [comment] 2022-01-14 14:08
Closing as this is a duplicate of: https://github.com/PyTorchLightning/pytorch-lightning/issues/9883

**Closed by carmocca** 2022-01-14 14:08 UTC
Labels: feature
