### ISSUE TITLE
Checkpooint Callback not called when training GAN from documentation

### ISSUE THREAD

**Issue by PasqualeZingo** [PyTorchLightning/pytorch-lightning#969] opened 2020-02-27 18:20 UTC
I tried to add a model checkpoint callback to the GAN example from the documentation (https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/domain_templates/gan.py), but it is failing silently; no checkpoints are being written.  I can't find anything in the checkpoint docs that indicate why it is not working.

#### What's your environment?
 - OS: Linux
 - Packaging: Conda
 - Version : 0.6, pytorch 1.4

**Comment by jeremyjordan** [comment] 2020-02-28 05:17
@PasqualeZingo could you reproduce the error in a Colab notebook and share the link?

**Comment by PasqualeZingo** [comment] 2020-02-28 18:08
Sure thing, here it is: https://colab.research.google.com/drive/1wvZXP3WYxolfa4oA0mVnawtCXDr19eLd

Thanks @jeremyjordan !

**Comment by jeremyjordan** [comment] 2020-03-02 04:36
Ah ok I think I know what's going on here. 

If you look at the [checkpointing callback](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/callbacks/model_checkpoint.py#L120), it's invoked with `on_validation_end`. 

However, because you don't have a `validation_step` defined, the trainer is [skipping validation](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/trainer/trainer.py#L1111). As a result, the callback to save the model checkpoints is never actually called.

**Comment by williamFalcon** [comment] 2020-03-02 10:34
should we enable the checkpoint callback to use any metric across training or validation step?

**Comment by PasqualeZingo** [comment] 2020-03-02 15:41
That would be ideal, in the mean time I can fool the validation loop into running for my use.  Would it be worth updating the docs in the mean time to clarify about the checkpoint callback?

**Comment by jeremyjordan** [comment] 2020-03-02 15:54
Yes, we should be running this `on_epoch_end` after both training and validation are complete.

**Comment by williamFalcon** [comment] 2020-03-05 04:05
merged #1043

**Closed by williamFalcon** 2020-03-05 04:05 UTC
Labels: question
