### ISSUE TITLE
What is the module attribute in the training_loop.py? 

### ISSUE THREAD

**Issue by redmlr** [PyTorchLightning/pytorch-lightning#4890] opened 2020-11-28 17:19 UTC
I want to train my model using pytorch_lightning but, when I pass my model into the trainer.fit(mymodel) function an error gets thrown. It says **"my model" has no attribute 'module'**. I searched through the pytorch_lightning files and found it in _pytorch_lightning/trainer/training_loop.py on line 123 - 125_. There is actually a class attribute that's called module, but my model class doesn't have it.

#Code
    ```
if args.load_model_from:
        speech_module = SpeechModule.load_from_checkpoint(args.load_model_from, model=model, args=args)
    else:
        speech_module = SpeechModule(model, args)

    logger = TensorBoardLogger(args.logdir, name='speech_recognition')
    trainer = Trainer(logger=logger)

    trainer = Trainer(
        max_epochs=args.epochs, gpus=args.gpus,
        num_nodes=args.nodes, distributed_backend=None,
        logger=logger, gradient_clip_val=1.0,
        val_check_interval=args.valid_every,
        checkpoint_callback=checkpoint_callback(args),
        resume_from_checkpoint=args.resume_from_checkpoint
    )
    trainer.fit(speech_module)

```
My environment:
 - OS: macOS 11.0.1
 - Packaging: pip
 - Version: python 3.7.9
- CPU/GPU: M1 (16GB shared cache and memory)

**Comment by tchaton** [comment] 2020-11-28 17:23
Hey @redmlr,

Would you mind reproduce this bug with the BoringModel ?

Best regards,
Thomas Chaton.

**Comment by redmlr** [comment] 2020-11-28 17:28
Thank you for answering so fast @tchaton,

Would you mind to explain what the BoringModel is? I'm sorry its my first time doing training using pytorch-lightning..

**Comment by redmlr** [comment] 2020-11-28 17:30
If that helps, here is my code for the SpeechModule class:

```
class SpeechModule(LightningModule):

    def __init__(self, model, args):
        super(SpeechModule, self).__init__()
        self.model = model
        self.criterion = nn.CTCLoss(blank=28, zero_infinity=True)
        self.args = args

    def forward(self, x, hidden):
        return self.model(x, hidden)

    def configure_optimizers(self):
        self.optimizer = optim.AdamW(self.model.parameters(), self.args.learning_rate)
        self.scheduler = optim.lr_scheduler.ReduceLROnPlateau(
                                        self.optimizer, mode='min',
                                        factor=0.50, patience=6)

        self.scheduler_2 = {
            'scheduler' : self.scheduler,
            'reduce_on_plateau' : True,
            # val_checkpoint_on is val_loss passed in as checkpoint_on
            'monitor': 'val_checkpoint_on'
        }

        return [self.optimizer], [self.scheduler_2]

    def step(self, batch):
        spectrograms, labels, input_lengths, label_lengths = batch 
        bs = spectrograms.shape[0]
        hidden = self.model._init_hidden(bs)
        hn, c0 = hidden[0].to(self.device), hidden[1].to(self.device)
        output, _ = self(spectrograms, (hn, c0))
        output = F.log_softmax(output, dim=2)
        loss = self.criterion(output, labels, input_lengths, label_lengths)
        return loss

    def training_step(self, batch, batch_idx):
        loss = self.step(batch)
        logs = {'loss': loss, 'lr': self.optimizer.param_groups[0]['lr'] }
        return {'loss': loss, 'log': logs}

    def train_dataloader(self):
        d_params = Data.parameters
        d_params.update(self.args.dparams_override)
        train_dataset = Data(json_path=self.args.train_file, **d_params)
        return DataLoader(dataset=train_dataset,
                            batch_size=self.args.batch_size,
                            num_workers=self.args.data_workers,
                            pin_memory=True,
                            collate_fn=collate_fn_padd)

    def validation_step(self, batch, batch_idx):
        loss = self.step(batch)
        return {'val_loss': loss}

    def validation_epoch_end(self, outputs):
        avg_loss = torch.stack([x['val_loss'] for x in outputs]).mean()
        self.scheduler.step(avg_loss)
        tensorboard_logs = {'val_loss': avg_loss}
        return {'val_loss': avg_loss, 'log': tensorboard_logs}

    def val_dataloader(self):
        d_params = Data.parameters
        d_params.update(self.args.dparams_override)
        test_dataset = Data(json_path=self.args.valid_file, **d_params, valid=True)
        return DataLoader(dataset=test_dataset,
                            batch_size=self.args.batch_size,
                            num_workers=self.args.data_workers,
                            collate_fn=collate_fn_padd,
                            pin_memory=True)
```

**Comment by carmocca** [comment] 2020-11-28 17:54
It might be caused due to using an invalid combination of Trainer args. I opened https://github.com/PyTorchLightning/pytorch-lightning/issues/4356 to discuss it.

In my case it was due to using `num_processes=2` without `accelerator="ddp_cpu"`

**Comment by redmlr** [comment] 2020-11-28 18:14
My training args are:
Epochs: 10
Batch_size: 64
Lr: 1e-3
GPUs: 0
Nodes: 2
Data_workers: 8
Dist_backend: ddp or ddp_cpu
And the train and test file locations

**Comment by carmocca** [comment] 2020-11-28 18:19
Do not use `ddp_cpu`, it is for debugging the ddp environment on CPU only.

Given those args, I suspect its due to `nodes=2`

**Comment by redmlr** [comment] 2020-11-28 18:23
The problem is that I do not have a dedicated gpu and when I am removing the nodes or set it to 0, an error gets thrown, which seems unfixable for me...

`zsh: illegal hardware instruction  python3 train.py --nodes=0 --gpus=0 --data_workers=4    `

**Comment by carmocca** [comment] 2020-11-30 00:59
Then you should try to find the cause of that error. Setting the nodes to 0 does not fix it, it just makes your program crash (with an `AttributeError`) before it happens.

**Comment by redmlr** [comment] 2020-11-30 14:43
Yes, that is obvious, but I cannot fix it because there is no similar error. I searched hours on google and found some errors caused by too old cpus and not supported tensorflow version but that isn’t the case.. Maybe I should create a new issue/question on stackoverflow

**Comment by carmocca** [comment] 2020-12-30 19:16
Hi @redmlr. Closing this issue since it is probably a hardware issue unrelated to Lightning.

Feel free to re-open if you need to!

**Closed by carmocca** 2020-12-30 19:16 UTC
Labels: question, waiting on author, won't fix
