### ISSUE TITLE
 Training Process hangs. Full RAM and SWAP.

### ISSUE THREAD

**Issue by Arij-Aladel** [PyTorchLightning/pytorch-lightning#5725] opened 2021-01-31 03:49 UTC
Hello!

Whilst fine-tuning T5 using pytorchLightning last version on my own dataset, the training script hangs in the middle of epoch 1 or 90% of it , and just stays there. No exception thrown, no error, nothing.
training is on one gpu. 
num workers = 4 is used.
It turns out that the RAM (64 GBs) is full and so is the SWAP (6 GB) for some reason. The GPU usage shows memory used.  I am not even keeping intermediate torch tensors (model outputs, targets) after the update on that particular batch are completed. Any ideas what might be happening? FYI, this happens with a seemingly large dataset with  2338175  training samples and 59721 validation samples. What is the possible reasons for that?

**Comment by angadkalra** [comment] 2021-02-10 05:32
Same thing happens to me. Progress bar freezes and I see 4 python processes at 100% and 3/4 GPUs at 100%.

**Comment by tchaton** [comment] 2021-02-15 10:44
Hey both of you,

Lightning keeps track of `training_step` outputs and metrics on gpu for optimization purposes. 
This work well for medium dataset, but becomes an issue with larger ones.

Could you try `Trainer(move_metrics_to_cpu=True)` and set `training_epoch_end` to `None`. It shouldn't keep anything extra on gpu.

Keep us updated.

Best,
T.C

**Comment by angadkalra** [comment] 2021-02-15 17:34
> Hey both of you,
> 
> Lightning keeps track of `training_step` outputs and metrics on gpu for optimization purposes.
> This work well for medium dataset, but becomes an issue with larger ones.
> 
> Could you try `Trainer(move_metrics_to_cpu=True)` and set `training_epoch_end` to `None`. It shouldn't keep anything extra on gpu.
> 
> Keep us updated.
> 
> Best,
> T.C

I'll try now, thanks.

**Comment by Arij-Aladel** [comment] 2021-02-16 13:37
@tchaton  Actually I have solved the problem , the problem was with the number of workers it should be zero or one as I remember

**Comment by angadkalra** [comment] 2021-02-16 18:21
> @tchaton Actually I have solved the problem , the problem was with the number of workers it should be zero or one as I remember

What was the it/s speed with 1 num_workers?

**Comment by Arij-Aladel** [comment] 2021-02-24 10:07
@angadkalra really I did not pay attention to that what was important to me that the code works and it works, sorry for late response

**Comment by lrwagner** [comment] 2021-02-24 15:10
I think I'm running into the same issue when using a large dataset. CPU (not gpu, I think op meant the same) Memory is just growing through the Epoch until training stops (training is done on 1 gpu), when the memory is full. Imo using less workers for the dataloader shouldn't fix the issue, it just reduces overall memory consumption by the dataloaders and also slows everything down for a lot !?

**Comment by angadkalra** [comment] 2021-02-24 17:48
> I think I'm running into the same issue when using a large dataset. CPU (not gpu, I think op meant the same) Memory is just growing through the Epoch until training stops (training is done on 1 gpu), when the memory is full. Imo using less workers for the dataloader shouldn't fix the issue, it just reduces overall memory consumption by the dataloaders and also slows everything down for a lot !?
> 
> Edit: Memory seems to be stable when using only 1 worker, but this slows everything down a lot. Might have to do something with how dataloaders work, which hast nothing to do with pytorch-lightning

This was happening to me but was fixed once I removed all python lists and dicts for my datamodule code and training code. I try to only use torch tensors or numpy arrays.

**Comment by lucadiliello** [comment] 2021-02-28 11:49
Same thing happening to me. Interestingly, I noticed that when using a `IterableDataset` the problem is much less evident. Moreover, after each epoch memory usage is reset to a starting value. 

I cannot train a small BERT with 64GB of RAM because the machine goes OOM after about 50% of the steps. The memory keeps increasing linearly after the first steps to a maximum value that is reached at each training epoch end. The problem is maybe not evident or relevant when training small models or when using small datasets.

**Comment by lucadiliello** [comment] 2021-02-28 11:51
> Hey both of you,
> 
> Lightning keeps track of `training_step` outputs and metrics on gpu for optimization purposes.
> This work well for medium dataset, but becomes an issue with larger ones.
> 
> Could you try `Trainer(move_metrics_to_cpu=True)` and set `training_epoch_end` to `None`. It shouldn't keep anything extra on gpu.
> 
> Keep us updated.
> 
> Best,
> T.C

How could this be a solution if @Arij-Aladel said that RAM is full (and not the GPU memory). Moving metrics to CPU would only increase RAM usage...what am I missing?

**Closed** 2021-04-10 06:54 UTC
Labels: won't fix

**Comment by edwardpwtsoi** [comment] 2021-05-05 02:33
Having the same issue, will setting a ratio to limit train batch help? I have only sufficient memory for 20% of my datasets. I wonder could I set limit train batch to 0.2? I went through the training loop implementation but doesn't see the limit train batch actually affect the training loop. Also, if it does work, do I need to set reload data loader per epoch to make sure it is not training on the same portion of 20% data?

**Comment by fate3439** [comment] 2021-08-21 04:49
This is happening to me as well. I am using a lmdb containing 100M items, each one is a vector of dimension 128. So the total size of lmdb on disk is around 400GB. In theory, the pytorch loader should not load entire data set into the memory, but the seems like the behavior contradicts it. Does anyone has any working fix? Thanks a lot...

**Comment by someshfengde** [comment] 2022-02-13 07:00
same thing is happening to me too even the limiting training size to 8 and reducing num_workers is not working. And I've compared this to tensorflow code but with tensorflow we can have 256 batch size and everything is working fine

**Comment by doloresgarcia** [comment] 2024-04-02 12:09
I also have the same issue, this makes lightning unusable for big trainings, why is there no plan to fix it?

**Comment by ASoleimaniB** [comment] 2024-06-10 14:06
Same thing is happening to me. Every iteration the RAM usage increases and then go down at the end of epoch but remain ±10% higher than previous epoch and during the validation I get out of RAM.

**Comment by jgvinholi** [comment] 2025-01-29 14:23
Problem still persists for me. No solution has been suggested, maybe the issue should be reopened?
