### ISSUE TITLE
Global step always zero after loading checkpoint

### ISSUE THREAD

**Issue by timothybrooks** [PyTorchLightning/pytorch-lightning#6470] opened 2021-03-10 20:42 UTC
I am saving checkpoints inside my module using `self.trainer.save_checkpoint(path)`. I am able to load these checkpoints into the model using `MyModel.load_from_checkpoint(path)` and trainer using `Trainer(resume_from_checkpoint=path)`. However, both the resulting model and trainer have `global_step=0` regardless of the step when saving. From the documentation I was of the impression that checkpoints saved the global step, which is important for my use case. How can I attain the global step from a checkpoint?

**Comment by carmocca** [comment] 2021-03-10 21:12
Here's a reproduction snippet

```python
def test_bug(tmpdir):
    class TestModel(BoringModel):
        def on_pretrain_routine_end(self) -> None:
            # BUG
            # this fails because global_step is incorrectly increased
            assert self.trainer.global_step == 4

    model = BoringModel()
    trainer = Trainer(default_root_dir=tmpdir, max_epochs=2, limit_train_batches=2)
    trainer.fit(model)
    
    # correct
    # steps: (0, 1, 2, 3)
    # it is increased to 4 so it can run if fit is called again
    assert trainer.global_step == 4

    ckpt = tmpdir / "model.ckpt"
    trainer.save_checkpoint(ckpt)

    trainer = Trainer(default_root_dir=tmpdir, resume_from_checkpoint=str(ckpt), max_epochs=4, limit_train_batches=2)
    
    # correct
    # the checkpoint state will be restored at the start of fit
    # an argument could be made to change this
    assert trainer.global_step == 0

    trainer.fit(TestModel())
    
    # correct
    # steps: (4, 5, 6, 7)
    assert trainer.global_step == 8
```

Note that the `global_step` does get loaded, just after fit, not after the Trainer is instantiated (see the snippet)

However, this made me notice the step number is not correct.

This should probably be looked at with https://github.com/PyTorchLightning/pytorch-lightning/issues/5007. We need to clean the step/epoch management across runs

**Comment by timothybrooks** [comment] 2021-03-10 22:27
I see, thanks for the explanation. I would argue that `Trainer(resume_from_checkpoint=path).global_step` and `Model.load_from_checkpoint(path).global_step` should reflect the true global step, rather than loading only during a call to `trainer.fit()`. Having the loaded global step at zero is inaccurate, and prevents the global step from being used in downstream processing and analysis that does not involve calling `trainer.fit()`. The `Model.load_from_checkpoint(path).global_step` case would be particularly valuable to me in two instances:

1. Post-processing of model that involves global step, such as taking weighted combinations of checkpoint network weights based on their global step.

2. Creating plots and visualizations which demonstrate change throughout training, such as computing expensive metrics (which are not run during training), analyzing feature activations, or exploring latent space manipulations, all as a function of the global step.

In the meantime, is there perhaps a workaround for directly loading the global step from the checkpoint?

**Comment by carmocca** [comment] 2021-03-10 22:33
Yeah, what you are proposing is sound. I'll take a shot when I get the chance 👍 

You can get the global_step like this: `torch.load(ckpt)["global_step"] - 1` (`-1` due to the bug mentioned above)

**Comment by carmocca** [comment] 2021-07-01 21:18
Status update. There are 2 things going on here:

1. The main point of the OP. This is to restore the global step on trainer init, not on fit start. This can be considered a feature request. No progress has been made here and it's not entirely clear whether this is possible as the full checkpoint state needs the accelerators to be initialized to restore it. Could explore an approach where only the simple properties are restored and everything model related is done later during `fit`. Any additional thoughts on this? @awaelchli @ananthsub @SeanNaren ?

2. The global step is wrong when reloading, this is a duplicate of #7406.

**Comment by SeanNaren** [comment] 2021-07-02 09:10
Thanks @carmocca, I agree with you! Making the change to load the checkpoint state via the Trainer before training begins is difficult. We assume state will be restored on fit currently and it wouldn't be wise to change this (as based on different plugins, loading behaviour changes).

I think the workaround of having to load the state dictionary to obtain the global step is a reasonable workaround as it will remain useable as is. I think if we were to do anything within Lightning, we'd have to do a similar thing; load the state dict twice.

**Closed** 2021-07-12 15:21 UTC
Labels: Priority P0, bug / fix, checkpoint, help wanted

**Comment by carmocca** [comment] 2021-07-12 15:38
Closing as point (1) will not be addressed. In fact, the `Trainer(resume_from_checkpoint)` should be eventually removed in favor of a `trainer.fit(ckpt_path)` flag. This would be consistent with the rest of the trainer methods and would avoid users being confused about the global step not being loaded on initialization. @SeanNaren
