### ISSUE TITLE
PyTorch supports Metal Performance Shader as an accelerator now, can pytorch-lightning also add support for that?

### ISSUE THREAD

**Issue by valkjsaaa** [PyTorchLightning/pytorch-lightning#13119] opened 2022-05-20 17:39 UTC
## 🚀 Feature

Support Metal Performance Shader (GPU APIs in macOS) in pytorch-lightning

### Motivation

PyTorch supports Metal Performance Shader as an accelerator now. I don't see any reason why this shouldn't be supported in PyTorch Lightning.

### Pitch

A new file can be added to the `accelerator` folder.

### Alternatives

I don't think there is an alternative.

### Additional context

PyTorch supporting GPU on macOS: https://pytorch.org/blog/introducing-accelerated-pytorch-training-on-mac/

**Comment by ananthsub** [comment] 2022-05-20 17:50
This is a duplicate of https://github.com/PyTorchLightning/pytorch-lightning/issues/13102

**Closed** 2022-05-20 17:50 UTC
Labels: duplicate
