### ISSUE TITLE
CI job `cpu (ubuntu-18.04, 3.9, oldest, stable)` failing with Segmentation fault

### ISSUE THREAD

**Issue by daniellepintz** [PyTorchLightning/pytorch-lightning#11206] opened 2021-12-21 20:54 UTC
## 🐛 Bug

The CI job `cpu (ubuntu-18.04, 3.9, oldest, stable)` has been failing quite consistently on recent PRs with a seg fault: 
`/home/runner/work/_temp/a06dced7-640c-436b-bbb1-c17e205bf64d.sh: line 2:  3542 Segmentation fault      (core dumped) coverage run --source pytorch_lightning -m pytest pytorch_lightning tests -v --durations=50 --junitxml=junit/test-results-Linux-py3.9-oldest-stable.xml`

Recent runs:
https://github.com/PyTorchLightning/pytorch-lightning/runs/4597791363?check_suite_focus=true
https://github.com/PyTorchLightning/pytorch-lightning/runs/4598799055?check_suite_focus=true
https://github.com/PyTorchLightning/pytorch-lightning/runs/4599551767?check_suite_focus=true
https://github.com/PyTorchLightning/pytorch-lightning/runs/4589679232?check_suite_focus=true

This job is often the only failing job, making the whole CI red. However this job is not required to merge a PR, so contributors aren't strongly motivated to fix it. As part of https://github.com/PyTorchLightning/pytorch-lightning/issues/9445 I believe we should either mark this test as required or delete it, with a personal preference for deleting it.

cc @carmocca @akihironitta @borda

**Comment by carmocca** [comment] 2021-12-21 22:51
Duplicate of #11184

**Closed by carmocca** 2021-12-21 22:51 UTC
Labels: bug, ci
