### ISSUE TITLE
Gpus=1 + precision not working when using only certain layers

### ISSUE THREAD

**Issue by williamFalcon** [PyTorchLightning/pytorch-lightning#4522] opened 2020-11-04 20:24 UTC
## 🐛 Bug

Making a finetuning model where the backbone isn't training breaks 16-bit.

**Comment by SeanNaren** [comment] 2020-11-05 12:26
Just to keep all the details here, this seems to be a side effect of amp. When we call `self.trainer.scaler.step(optimizer)` internally the scaler does an inf check on the optimizer's parameters, which is the assertion being thrown. This check needs to coincide with ensuring that the parameters are even updated within this step.

**Comment by edenlightning** [comment] 2020-11-17 18:12
@SeanNaren follow up with pytorch team

**Comment by simonm3** [comment] 2021-03-13 14:42
Probably related to this I am unable to train an efficientnet using precision=16. I get the error AssertionError: "No inf checks were recorded for this optimizer."

**Comment by SeanNaren** [comment] 2021-07-26 10:33
@simonm3 would you be able to provide more details? I'm circling back to this after a long while and need to come up with a reproducible script (cc @williamFalcon, who I think had a reproducible script at some point).

Below I have an example of a backbone which doesn't record gradients, however a single layer on top recording gradients. Maybe we can start there and modify:

```python
import os

import torch
from torch.utils.data import DataLoader, Dataset

from pytorch_lightning import LightningModule, Trainer


class RandomDataset(Dataset):

    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(LightningModule):

    def __init__(self):
        super().__init__()
        self.backbone = torch.nn.Linear(32, 32)
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        with torch.no_grad():
            x = self.backbone(x)
        x = self.layer(x)
        return x

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return {"loss": loss}

    def validation_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("valid_loss", loss)

    def test_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("test_loss", loss)

    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)


def run():
    train_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    val_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    test_data = DataLoader(RandomDataset(32, 64), batch_size=2)

    model = BoringModel()
    trainer = Trainer(
        default_root_dir=os.getcwd(),
        limit_train_batches=1,
        limit_val_batches=1,
        num_sanity_val_steps=0,
        max_epochs=1,
        precision=16,
        gpus=1,
        weights_summary=None,
    )
    trainer.fit(model, train_dataloaders=train_data, val_dataloaders=val_data)
    trainer.test(model, dataloaders=test_data)


if __name__ == '__main__':
    run()
```

**Comment by tchaton** [comment] 2021-09-15 11:02
Hey @simonm3,

Any updates ?

**Comment by carmocca** [comment] 2022-01-12 02:27
Closing this issue as it's very old and has no repro.

I'm sure somebody will report it again if it's still a problem.

**Closed by carmocca** 2022-01-12 02:27 UTC
Labels: bug, help wanted, 3rd party
