### ISSUE TITLE
"MisconfigurationException: PyTorch XLA not installed." Even though PyTorch XLA is installed

### ISSUE THREAD

**Issue by simonrouse9461** [PyTorchLightning/pytorch-lightning#4829] opened 2020-11-24 07:06 UTC
## 🐛 Bug

I'm using exactly the same command to install pytorch xla as shown in the doc:
```bash
curl https://raw.githubusercontent.com/pytorch/xla/master/contrib/scripts/env-setup.py -o pytorch-xla-env-setup.py
python pytorch-xla-env-setup.py --version nightly --apt-packages libomp5 libopenblas-dev
```
However, I still got this error:
```
GPU available: False, used: False
TPU available: True, using: 1 TPU cores
training on 1 TPU cores
---------------------------------------------------------------------------
MisconfigurationException                 Traceback (most recent call last)
<ipython-input-11-1f9f6fbe4f6c> in <module>()
----> 1 test_x(tmpdir)

2 frames
/usr/local/lib/python3.6/dist-packages/pytorch_lightning/accelerators/tpu_accelerator.py in setup(self, model)
     61         # TODO: Move this check to Trainer __init__ or device parser
     62         if not TPU_AVAILABLE:
---> 63             raise MisconfigurationException('PyTorch XLA not installed.')
     64 
     65         # see: https://discuss.pytorch.org/t/segfault-with-multiprocessing-queue/81292/2

MisconfigurationException: PyTorch XLA not installed.
```

## Please reproduce using [the BoringModel and post here](https://colab.research.google.com/drive/1HvWVVTK8j2Nj52qU4Q4YCyzOm0_aLQF3?usp=sharing)

https://colab.research.google.com/drive/1dz4NY233VoBv9SIb22JnrWiqYBHFpxCm?usp=sharing

### To Reproduce

run through the colab notebook in the link above

### Expected behavior
no error

### Environment

**Note**: `Bugs with code` are solved faster ! `Colab Notebook` should be made `public` !

* `IDE`: Please, use our python [bug_report_model.py](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/bug_report_model.py
) template.

* `Colab Notebook`: Please copy and paste the output from our [environment collection script](https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py) (or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py
# For security purposes, please check the contents of collect_env_details.py before running it.
python collect_env_details.py
```

* CUDA:
	- GPU:
	- available:         False
	- version:           None
* Packages:
	- numpy:             1.18.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.8.0a0+4ed7f36
	- pytorch-lightning: 1.0.7
	- tqdm:              4.41.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.6.9
	- version:           #1 SMP Thu Jul 23 08:00:38 PDT 2020

**Comment by rohitgr7** [comment] 2020-11-24 16:53
@simonrouse9461 can you make your notebook public?

**Comment by simonrouse9461** [comment] 2020-11-24 16:57
> @simonrouse9461 can you make your notebook public?

Sorry, I forgot to check. It's now public.

**Comment by rohitgr7** [comment] 2020-11-24 18:29
when I changed the time here to 20 sec, it worked.
https://github.com/PyTorchLightning/pytorch-lightning/blob/fb0278a457be64a25cd2cf7e6d29c6ae3846ccc3/pytorch_lightning/utilities/xla_device_utils.py#L44

not sure if this is the real issue. cc @lezwon

**Comment by teddykoker** [comment] 2020-11-24 22:33
Hmm I tried to ran the notebook and it worked just fine for me

**Comment by lezwon** [comment] 2020-11-25 01:17
> when I changed the time here to 20 sec, it worked.
> https://github.com/PyTorchLightning/pytorch-lightning/blob/fb0278a457be64a25cd2cf7e6d29c6ae3846ccc3/pytorch_lightning/utilities/xla_device_utils.py#L44
> 
> not sure if this is the real issue. cc @lezwon

It might be the issue. The behavior is not consistent every time. Have a PR in works which changes this to 20 secs. @rohitgr7 maybe we could quickly make this change for now and see if the behavior is more consistent.

**Comment by rohitgr7** [comment] 2020-11-25 06:00
Yep checked again. It's working now with 10 sec. I believe it has to do something with the availability.

**Comment by SaiKeshav** [comment] 2020-11-27 10:05
I was also facing the same issue in my code (it occurs randomly and bothered me quite a bit). Changing it to 20 secs has resolved the issue in my case.

**Comment by armandnaessens** [comment] 2020-11-27 14:51
How do you change it to 20 seconds in the source file?

**Comment by AnselmC** [comment] 2020-11-27 18:04
Facing the same issue but changing to 20 secs (or some other larger value) does not solve the issue for me. Also, it's failing right away, so don't see how this could be a timing issue for me...
Unfortunately, I can't share the notebook but following the instructions as per the [readme](https://pytorch-lightning.readthedocs.io/en/latest/tpu.html)

**Comment by rohitgr7** [comment] 2020-11-27 18:23
> How do you change it to 20 seconds in the source file?

@armandnaessens there are multiple ways, one way on colab you can do:
```python
from pytorch_lightning.utilities.xla_device_utils import XLADeviceUtils
```
then hover over `XLADeviceUtils` it will give you an option to `View Source`, click on it, update the value there from 10 to 20, save it, restart the notebook and run again.

**Comment by rohitgr7** [comment] 2020-11-27 18:27
AFAIR the reason why we do it this way is because if someone installs XLA on a device with no TPU, then just checking XLA installation to verify a TPU device exist or not is not correct. We need to check the device by calling `xm.xla_device()`, since pytorch doesn't have any functionality to check TPU device just like for GPU (torch.cuda.is_available()). Anyone got suggestions how this can be done in a better way if possible??

**Comment by simonrouse9461** [comment] 2020-11-27 19:26
Change it to 20 didn't work for me. I then changed it to 100, and it worked. Is there a more robust way to fix it than setting a magic number?

**Comment by rohitgr7** [comment] 2020-11-27 19:29
cc @lezwon any suggestion or an alternative to check TPU availability here?

**Comment by lezwon** [comment] 2020-11-28 01:08
There was initially no timeout for checking the TPU availability. However, in some cases this resulted in lightning hanging during imports, so a timeout of 10 was added.  Kaggle/Colab TPU initialization time differs, due to which I suspect we are facing this issue. One way to deal with this might be to lazy check for TPU device. i.e only during `.fit`. Rest of the times we can just check if `XLA` is available.

**Comment by lezwon** [comment] 2020-11-29 08:40
This may be fixed in #4309.

**Comment by evanatyourservice** [comment] 2020-11-29 17:01
I've been using TPUs a lot and can confirm this error only happens occasionally in colab, and I just restart the the runtime until the TPUs have loaded.

@lezwon I think lazy checking would be a good idea like you say because it's often only a matter of seconds, but if the TPUs haven't loaded before `.fit` is called, perhaps there is a way to print a "warning: waiting for TPUs to start" and wait? Somehow having it wait at that point vs. throwing an error is probably ideal incase time was spent preprocessing and building variables before `.fit`. But if that's not possible a more descriptive error on what happened would let people know it's less of an error and more of just needing to wait for the TPUs to start.

**Comment by Borda** [comment] 2020-11-30 10:18
el free to re-open if needed 🐰

**Comment by rohitgr7** [comment] 2020-11-30 18:52
opening this because it needs to be fixed. Came up again on forums.
https://forums.pytorchlightning.ai/t/misconfigurationexception-pytorch-xla-not-installed/429

**Comment by edenlightning** [comment] 2020-11-30 20:57
@Borda

**Comment by lezwon** [comment] 2020-12-03 03:25
@simonrouse9461 can you try the master branch and let us know if the issue is still occurring?

**Comment by ayushm-agrawal** [comment] 2020-12-07 03:00
I got this error again on Colab today.

**Comment by lezwon** [comment] 2020-12-07 05:41
@ayushm-agrawal did you try with the master branch?

**Comment by Borda** [comment] 2020-12-07 10:42
@simonrouse9461 I have run the notebook you shared and have not observed any issue/error...
in general, I would recommend using a stable version like 1.6 or 1.7 not nightly builds
pls fee free to reopen if you have problems also on stable XLA versions 🐰

**Closed by Borda** 2020-12-07 10:42 UTC
Labels: 3rd-party, TPU, bug / fix, help wanted, waiting on author

**Comment by umbertov** [comment] 2020-12-08 00:04
I had the same problem on Colab + XLA 1.7. 
Changing the join() timeout to 100 as @simonrouse9461 said got rid of the issue: slowly, the messages like 
```
INIT TPU local core: 6, global rank: 6 with XLA_USE_BF16=None
INFO:lightning:INIT TPU local core: 6, global rank: 6 with XLA_USE_BF16=None
```
started appearing, slowly and one at a time (up to 8).

With the default `join` timeout, running my training script on Colab TPUs was a hit or miss. To overcome this, i put my invocation in a `while true; do py train.py && exit 0 ; done` loop just to find that moment when the TPU becomes readily available... and it was only possible when setting `tpu_cores=1` in the `Trainer`, because setting it to 8 would just never work.

**Comment by ayushm-agrawal** [comment] 2020-12-08 00:32
> @ayushm-agrawal did you try with the master branch?

I tried installing on Colab using the following command. 
`pip install git+https://github.com/PytorchLightning/pytorch-lightning.git@master --upgrade`
Got this error

```Collecting git+https://github.com/PytorchLightning/pytorch-lightning.git@master
  Cloning https://github.com/PytorchLightning/pytorch-lightning.git (to revision master) to /tmp/pip-req-build-cekbn4x_
  Running command git clone -q https://github.com/PytorchLightning/pytorch-lightning.git /tmp/pip-req-build-cekbn4x_
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
ERROR: Command errored out with exit status 1: /usr/bin/python3 /usr/local/lib/python3.6/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpsw5o0jxw Check the logs for full command output.```

**Comment by graceyangfan** [comment] 2020-12-08 01:04
@Borda  I meet this error on colab TPU .
I install the packages following the https://pytorch-lightning.readthedocs.io/en/latest/tpu.html:
'''
!curl https://raw.githubusercontent.com/pytorch/xla/master/contrib/scripts/env-setup.py -o pytorch-xla-env-setup.py
!python pytorch-xla-env-setup.py --version nightly --apt-packages libomp5 libopenblas-dev
‘’‘

**Comment by umbertov** [comment] 2020-12-08 11:25
Btw, a quick way for anyone getting this issue to change the `join` timeout is the following:

```python
from pytorch_lightning.utilities import xla_device_utils
!sed 's/join(10)/join(100)/' \
    {xla_device_utils.__file__} \
    -i # IN-PLACE
```
