### ISSUE TITLE
Remove mypy from pre-commit hooks

### ISSUE THREAD

**Issue by arnaudgelas** [PyTorchLightning/pytorch-lightning#5431] opened 2021-01-08 20:14 UTC
As of now, `pre-commit` hooks are not used by developers.
I see 2 reasons for dropping `mypy` hooks at this point:

1.  `mypy` command line use `setup.cfg` as configuration file. It is fine when used alone to get configuration and list of files. But when running with `pre-commit`, `pre-commit` add at files in the command line, which overrides the list of files with provided configuration. So when running, `pre-commit run --all-files` `mypy` runs on all python files (not the one given in `setup.cfg`). Since in general, you may want to add `pre-commit` checks in your CI to enforce `pre-commit` usage, it will dramatically fail with the following errors:

> 
> mypy.....................................................................Failed
> - hook id: mypy
> - exit code: 1
> 
> docs/source/conf.py:28: error: Module has no attribute "__LIGHTNING_SETUP__"  [attr-defined]
> docs/source/conf.py:277: error: Function is missing a type annotation  [no-untyped-def]
> docs/source/conf.py:295: error: Function is missing a type annotation  [no-untyped-def]
> setup.py:24: error: Name 'builtins' already defined (by an import)  [no-redef]
> setup.py:29: error: Module has no attribute "__LIGHTNING_SETUP__"  [attr-defined]
> tests/models/data/horovod/train_default_model.py:25: error: Item "None" of "Optional[str]" has no attribute "split"  [union-attr]
> tests/models/data/horovod/train_default_model.py:46: error: Function is missing a type annotation  [no-untyped-def]
> tests/trainer/logging/test_logger_connector.py:36: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
> tests/trainer/logging/test_logger_connector.py:52: error: Function is missing a type annotation  [no-untyped-def]
> tests/trainer/logging/test_logger_connector.py:64: error: Function is missing a type annotation  [no-untyped-def]
> tests/trainer/logging/test_logger_connector.py:74: error: Function is missing a type annotation  [no-untyped-def]
> tests/trainer/logging/test_logger_connector.py:110: error: Function is missing a type annotation  [no-untyped-def]
> tests/trainer/logging/test_logger_connector.py:123: error: Function is missing a type annotation  [no-untyped-def]
> tests/trainer/logging/test_logger_connector.py:126: error: Function is missing a return type annotation  [no-untyped-def]
> tests/trainer/logging/test_logger_connector.py:133: error: Function is missing a return type annotation  [no-untyped-def]
> tests/trainer/logging/test_logger_connector.py:133: note: Use "-> None" if function does not return a value
> tests/trainer/logging/test_logger_connector.py:139: error: Function is missing a type annotation  [no-untyped-def]
> tests/trainer/logging/test_logger_connector.py:160: error: Function is missing a return type annotation  [no-untyped-def]
> tests/trainer/logging/test_logger_connector.py:168: error: Function is missing a type annotation  [no-untyped-def]
> tests/trainer/logging/test_logger_connector.py:205: error: Function is missing a type annotation  [no-untyped-def]
> tests/trainer/logging/test_logger_connector.py:216: error: Function is missing a type annotation  [no-untyped-def]
> tests/trainer/logging/test_logger_connector.py:226: error: Function is missing a type annotation  [no-untyped-def]
> tests/trainer/logging/test_logger_connector.py:230: error: Function is missing a return type annotation  [no-untyped-def]
> tests/trainer/logging/test_logger_connector.py:230: note: Use "-> None" if function does not return a value
> tests/trainer/logging/test_logger_connector.py:234: error: Function is missing a return type annotation  [no-untyped-def]
> tests/trainer/logging/test_logger_connector.py:271: error: Function is missing a type annotation  [no-untyped-def]
> tests/trainer/logging/test_logger_connector.py:373: error: Function is missing a type annotation  [no-untyped-def]
> tests/trainer/logging/test_logger_connector.py:379: error: Function is missing a type annotation  [no-untyped-def]
> tests/trainer/logging/test_logger_connector.py:384: error: Function is missing a type annotation  [no-untyped-def]
> tests/trainer/logging/test_logger_connector.py:388: error: Function is missing a type annotation  [no-untyped-def]
> tests/trainer/logging/test_logger_connector.py:392: error: Function is missing a type annotation  [no-untyped-def]
> tests/trainer/logging/test_logger_connector.py:397: error: Function is missing a type annotation  [no-untyped-def]
> tests/trainer/logging/test_logger_connector.py:401: error: Function is missing a type annotation  [no-untyped-def]
> tests/trainer/logging/test_logger_connector.py:406: error: Function is missing a type annotation  [no-untyped-def]
> tests/trainer/logging/test_logger_connector.py:410: error: Function is missing a return type annotation  [no-untyped-def]
> tests/trainer/logging/test_logger_connector.py:413: error: Function is missing a return type annotation  [no-untyped-def]
> tests/trainer/logging/test_logger_connector.py:416: error: Function is missing a return type annotation  [no-untyped-def]
> tests/trainer/logging/test_logger_connector.py:433: error: Function is missing a type annotation  [no-untyped-def]
> Found 36 errors in 4 files (checked 372 source files)

2. In my humble opinion, you want to keep git pre-commit hooks _light_. Formatting, removing trailing spaces, sorting import are definitively OK, but running static analysis, unit tests can last long and can discourage people from contributing to the projects. It is rather a blocking experience rather than helping one. So I would recommend removing mypy hooks from pre-commit but makes sure it is part of the script to be used before a submission or executed by the CI.

What do you think?

**Comment by tchaton** [comment] 2021-01-09 17:23
Hey @arnaudgelas,

We are planning to start typing all the codebase.
Lightning being a visible framework in AI, we need to show lead by example.

Would you mind helping in such doing ?
We are going to start file by file, type everything until mypy doesn t complain and remove the ignore.

Best,
T.C

**Comment by arnaudgelas** [comment] 2021-01-10 19:28
Hey @tchaton,

I could definitively help in such an initiative :+1: 

Note: This issue is not against `mypy`, but just to discuss about the possibility to remove `mypy` from `pre-commit` hook.

Best,
Arnaud

**Comment by tchaton** [comment] 2021-01-11 11:06
Hey @arnaudgelas,

Glad to hear you want to help out ! Let's keep it for now, and remove it when it starts to become a bottleneck 👍 
Ping @Borda for it :)
If you want to help, please make a PR resolving a section of the codebase with `mypy`.

Thanks a lot !
Best,
T.C

**Comment by Borda** [comment] 2021-01-11 13:19
I do not think it is a good idea to remove it as we test it in CI anyway, it seems rather the problem is in not correct setting...

**Comment by arnaudgelas** [comment] 2021-01-11 13:28
@Borda Have you try enabling `pre-commit`? 

Could you please elaborate?

I don't see the connection in between pre-commit hook and CI. For instance, I do't see any check on trailing white space in the CI whereas it is in pre-commit. It is true that there should be one CI job enforcing pre-commit to be used (by calling pre-commit hook for every PR).

**Comment by Borda** [comment] 2021-01-11 13:43
> @Borda Have you try enabling `pre-commit`?

not really, never used pre-commit 🐰 
cc: @akihironitta

**Comment by carmocca** [comment] 2021-01-11 19:22
> It is true that there should be one CI job enforcing pre-commit to be used (by calling pre-commit hook for every PR).

+1

I agree it is not a good idea to have mypy in pre-commit for a large project, especially if it's not already perfectly typed.

So run the pre-commit hook in CI + mypy

**Comment by akihironitta** [comment] 2021-01-16 09:10
In my humble opinion, I thought we should keep mypy in pre-commit since it, by default, checks only modified files (right?), and pre-commit is just an optional checker which not everyone uses. (I'm neutral on this as I don't really use pre-commit... :sweat_smile: )

**Closed** 2021-02-22 13:46 UTC
Labels: enhancement, won't fix
