### ISSUE TITLE
LoggerCollection name redundancy

### ISSUE THREAD

**Issue by twsl** [PyTorchLightning/pytorch-lightning#10954] opened 2021-12-06 10:46 UTC
## 🐛 Bug

When you create a logger collection, the name of the logger collection is used for the save path in `ModelCheckpoint`. LoggerCollection concats  the names of all logger. Therefore, in my example the checkpoints are saved to `f"{experiment_name}_{experiment_name}"` instead of `experiment_name`.

### To Reproduce

```python
tb_logger = TensorBoardLogger(save_dir=root_dir, name=experiment_name, version=version)
csv_logger = CSVLogger(save_dir=root_dir, name=experiment_name, version=version)
trainer = pl.Trainer(
        logger=[
            csv_logger,
            tb_logger,
        ],
    )

#...

class TestModule(pl.LightningModule):
    def configure_callbacks(self):
        checkpoint = ModelCheckpoint(
            monitor="val_map",
            filename="{epoch}-{step}--{val_map:.4f}",
            auto_insert_metric_name=True,
            every_n_epochs=1,
        )
        return [checkpoint]
```

### Expected behavior

I would expect the checkpoints to be saved under the same name I set for the loggers. I understand the motive behind the current implementation, but I think only unique names should be concatenated there. Same goes for the version property.

### Environment

- PyTorch Lightning Version (e.g., 1.5.0): 1.5.4
- PyTorch Version (e.g., 1.10): 1.10
- Python version (e.g., 3.9): 3.8
- OS (e.g., Linux): Linux
- CUDA/cuDNN version:
- GPU models and configuration: 1080
- How you installed PyTorch (`conda`, `pip`, source): pip
- If compiling from source, the output of `torch.__config__.show()`: -
- Any other relevant information:

### Additional context

Workaround is to set the `dirpath` argument manually.

cc @borda @awaelchli @edward-io @ananthsub @tchaton

**Comment by tchaton** [comment] 2021-12-06 11:15
Dear @twsl,

Would you be interested in contributing a fix?

Best,
T.C

**Comment by ashutoshml** [comment] 2021-12-06 13:25
I can help with fixing this issue.

**Comment by tchaton** [comment] 2021-12-06 17:06
Great @ashutoshml, I assigned you to the issue.

**Comment by ashutoshml** [comment] 2021-12-06 17:13
Thanks.  I'll start working on it.

What are the requirements for the fix, though?

Based on the issue reported, I assume the fix should only be concerning `experiment_name` in the `loggers.` Is there anything else that needs to change?

**Comment by tchaton** [comment] 2021-12-07 11:58
Hey @ashutoshml,

I would assume this to fix the problem. There might be some edge case if the users wanted to have twice of the same type of loggers though.

**Comment by ashutoshml** [comment] 2021-12-07 12:04
Sure. I can take a look at that. 
Currently the issue is assigned to you, though.

**Closed** 2021-12-23 00:35 UTC
Labels: bug, good first issue, logger, priority: 1
