### ISSUE TITLE
DataHook makes pylint error after >=1.5.0

### ISSUE THREAD

**Issue by Aiden-Jeon** [PyTorchLightning/pytorch-lightning#10667] opened 2021-11-22 03:50 UTC
### To Reproduce
`pytorch_lightning>=1.5.0` makes below pylint error.
```bash
W: 87, 0: Method 'predict_dataloader' is abstract in class 'DataHooks' but is not overridden (abstract-method)
W: 87, 0: Method 'test_dataloader' is abstract in class 'DataHooks' but is not overridden (abstract-method)
W: 87, 0: Method 'train_dataloader' is abstract in class 'DataHooks' but is not overridden (abstract-method)
W: 87, 0: Method 'val_dataloader' is abstract in class 'DataHooks' but is not overridden (abstract-method)
```
This is due to change of `on_train_dataloader` to `train_dataloader`, removing prefix `on_`.
Pylint handles `raise NotImplementedError` as `abstractmethod`.
And `train_dataloader` raises  `NotImplementedError` when not defined.
```python
def train_dataloader(self) -> EVAL_DATALOADERS:
    ...
    raise NotImplementedError("`predict_dataloader` must be implemented to be used with the Lightning Trainer")
```

### Expected behavior
I think `on_train_dataloader` and `train_dataloader` is not doing different job.
To make consistency, this raise code should be removed from the function.
And i found same issue https://github.com/PyTorchLightning/pytorch-lightning/issues/2815, that raise is not the desired way.

### Environment

- PyTorch Lightning Version (e.g., 1.3.0): >=1.5.0
- PyTorch Version (e.g., 1.8) 1.10
- Python version: 3.8.10
- OS (e.g., Linux): Ubuntu
- CUDA/cuDNN version: x
- GPU models and configuration:
- How you installed PyTorch (`conda`, `pip`, source): pip
- If compiling from source, the output of `torch.__config__.show()`:
- Any other relevant information:

### Additional context

cc @justusschock @awaelchli @ninginthecloud

**Comment by justusschock** [comment] 2021-11-22 09:54
@Aiden-Jeon actually `on_train_dataloader` and `train_dataloader` have different responsibilities. The first one is a (now deprecated) hook that was called whenever the second one was called (which usually builds and returns the loader).

I am afraid, that we cannot remove the `NotImplementedError` there since this method will be triggered (and has to error out if not implemented) when no other data source is given to the trainer.

As a workaround, you could disable this particular warning (`W0223`). 

#2815 is quite old and the way the data part is currently handled by the trainer, the `NotImplementedError` is exactly what we want here. An alternative could be to return `None` here and then raise a `RuntimeError` inside the trainer when data is None

**Comment by carmocca** [comment] 2022-03-01 13:33
Closing as this is currently expected behaviour after #8752.

**Closed by carmocca** 2022-03-01 13:33 UTC
Labels: bug, data handling
