### ISSUE TITLE
[Bug] Incorrect time estimation in the progress bar

### ISSUE THREAD

**Issue by ShaneTian** [PyTorchLightning/pytorch-lightning#12875] opened 2022-04-25 09:25 UTC
## 🐛 Bug

The progress bar shows the incorrect time estimation when `epoch > 0`:

```
Epoch 0: : 910it [25:44,  1.70s/it]
Epoch 1: : 1it [25:48, 1548.78s/it]
```

`(25 * 60 + 48) / 1 = 1548

### Environment

* CUDA:
        - GPU:
                - A100-SXM4-40GB
                - A100-SXM4-40GB
                - A100-SXM4-40GB
                - A100-SXM4-40GB
                - A100-SXM4-40GB
                - A100-SXM4-40GB
                - A100-SXM4-40GB
                - A100-SXM4-40GB
        - available:         True
        - version:           11.3
* Packages:
        - numpy:             1.20.1
        - pyTorch_debug:     False
        - pyTorch_version:   1.10.2+cu113
        - pytorch-lightning: 1.6.0
        - tqdm:              4.63.1
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - 
        - processor:         x86_64
        - python:            3.7.10
        - version:           #1 SMP Fri Mar 19 10:07:22 CST 2021

### Additional context

Similar to https://github.com/PyTorchLightning/pytorch-lightning/issues/12787

cc @awaelchli @rohitgr7

**Comment by carmocca** [comment] 2022-04-26 12:09
Might be a duplicate of https://github.com/PyTorchLightning/pytorch-lightning/issues/12787

**Comment by rohitgr7** [comment] 2022-04-26 15:22
hey @ShaneTian !

would you mind trying out #12889 and checking if it fixes your issue?

**Closed** 2022-05-03 16:21 UTC
Labels: bug, progress bar: tqdm
