### ISSUE TITLE
Output not reduced in DP

### ISSUE THREAD

**Issue by Deanamic** [PyTorchLightning/pytorch-lightning#1537] opened 2020-04-20 17:53 UTC
## 🐛 Bug
I believe there is a discrepancy in the training and validation epoch ends when training in parallel gpus. I cannot release the code I'm working with as it is private, but I'll try and reproduce if I can. 
The bug is that the output in validation epochs is not reduced, we can verify it [in the source of the validation](https://github.com/PyTorchLightning/pytorch-lightning/blob/0203938af8f69a19b7e0264f18e03d543d86e0e9/pytorch_lightning/trainer/evaluation_loop.py#L262), and we can also see that all references to [this function](https://github.com/PyTorchLightning/pytorch-lightning/blob/0203938af8f69a19b7e0264f18e03d543d86e0e9/pytorch_lightning/trainer/logging.py#L183) are inside an `if train` statement.  
This can lead to bugs which are hard to detect without looking at the source code. For example,  you can calculate the mean of the loss at `training_epoch_end`, but the same code depending on the number of gpus, validation samples and batchsize might lead to bugs in `validation_epoch_end`.

### To Reproduce
Given 4 gpus, 10 validation samples and a batchsize of 4. The last validation step will only have two outputs. Then:
Running `torch.stack([x['loss'] for x in outputs]).mean()` works in `training_epoch_end` as outputs are reduced before reaching `training_epoch_end`. 
Running `torch.stack([x['loss'] for x in outputs]).mean()` will fail in `validaition_epoch_end` as outputs are not reduced, and the first dimention of the output coming from the last batch differs. so `torch.stack` will fail

### Expected behavior
I expect that both validation and training epochs have the same behaviour, or if not there has to be a clear warning.

**Comment by williamFalcon** [comment] 2020-04-20 22:55
they should have the same behavior. mind putting together a colab to illustrate? mnist should be enough no?

**Comment by Deanamic** [comment] 2020-04-21 01:47
I don't think I can run on colab as it is a problem when using multiple gpus, I'll try and run a short demo on my cluster

**Comment by Deanamic** [comment] 2020-04-21 03:46
[This code ilustrates the issue](https://gist.github.com/Deanamic/d0aa1bdbed83f288d7365327046ceb97)
If you run with
  -  2 gpus, 
  - batch size:2 
  - dataloader size: 3

The outputs from the 2 training/validation steps will have dimension 2 and 1 in each epoch. 
For training, it's OK as it is reduced. We verify that the exception occurs in the validation epoch end, having the sanity run disabled.
On the other hand, if we run with a batch size of 3 the problem will not happen.I belive this bug only will happen if there is a gpu with no data in a run, i.e. `len(val_dataloader)%batch_size < n_gpus`Which make this bug very hard to diagnose and many times unnoticed.
The error is the following:
```
Traceback (most recent call last):
  File "dpbug.py", line 75, in <module>  
    main()  
  File "dpbug.py", line 72, in main  
    val_dataloaders = val_dl)  
  File "/cluster/home/dzhu/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer  /trainer.py", line 702, in fit  
    self.dp_train(model)  
  File "/cluster/home/dzhu/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer  /distrib_parts.py", line 538, in dp_train  
    self.run_pretrain_routine(model)  
  File "/cluster/home/dzhu/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer  /trainer.py", line 865, in run_pretrain_routine  
    self.train()
  File "/cluster/home/dzhu/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 363, in train
    self.run_training_epoch()
  File "/cluster/home/dzhu/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 457, in run_training_epoch
    self.run_evaluation(test_mode=self.testing)
  File "/cluster/home/dzhu/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 372, in run_evaluation
    eval_results = self._evaluate(self.model, dataloaders, max_batches, test_mode)
  File "/cluster/home/dzhu/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 316, in _evaluate
    eval_results = model.validation_epoch_end(outputs)
  File "dpbug.py", line 44, in validation_epoch_end
    loss = torch.stack([x['loss'] for x in outputs]).mean()
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 1 and 2 in dimension 1 at /tmp/pip-req-build-4baxydiv/aten/src/THC/generic/THCTensorMath.cu:71
```

**Comment by Deanamic** [comment] 2020-04-21 04:07
QQ: Why is the reason the calls to `self.reduce_distributed_output()` are only for training.  
I think the fix is probably adding a call to `self.reduce_distributed_output()` [here](https://github.com/PyTorchLightning/pytorch-lightning/blob/bd168819f2e6433a8b0f0d497eda785199cf65cf/pytorch_lightning/trainer/evaluation_loop.py#L262). but I haven't looked too deep into the issue. I'm having quite a bit of work right now, so hopefully someone else will look into it

**Comment by Borda** [comment] 2020-04-21 19:45
@Deanamic mind send a PR? :]

**Comment by Deanamic** [comment] 2020-04-21 20:49
I won't be able to work on this until approximately mid May, so hopefully someone can work on this. Else I'll do it when I'm available

**Comment by jbschiratti** [comment] 2020-05-03 09:14
@Borda and @Deanamic : I can have a look at this if you do not mind :-)

**Comment by junwen-austin** [comment] 2020-08-17 21:26
I am curious the status of this issue. Could this be fixed in the near future? 

I am in the process of migration from Pytorch to lightning and I ran into the same issue outlined above when I changed batch_size. 

Thanks.

**Comment by Borda** [comment] 2020-08-17 21:50
@junwen-austin would you be interested in sending a fix for this issue? :]

**Comment by junwen-austin** [comment] 2020-08-17 22:01
@Borda I'd love to but my background is data science and do not have lots of coding experience in DDP. I am using Lightning for my data science project at work and am really impressed by the design and philosophy of Lightning 👍

**Comment by Deanamic** [comment] 2020-08-19 09:35
I didn't know this bug was still open, the fix shouldn't involve coding with DDP as pytorch should handle everything. I could try fix that now, but I wondered if there is any way to test multiple GPUs as I do not have access to that.

> I think the fix is probably adding a call to `self.reduce_distributed_output()` [here](https://github.com/PyTorchLightning/pytorch-lightning/blob/bd168819f2e6433a8b0f0d497eda785199cf65cf/pytorch_lightning/trainer/evaluation_loop.py#L262). but I haven't looked too deep into the issue. I'm having quite a bit of work right now, so hopefully someone else will look into it

This should probably fix the issue, but would require further testing

**Comment by Borda** [comment] 2020-09-15 19:46
@jbschiratti @junwen-austin @Deanamic anyone wants to take this over?

**Comment by teddykoker** [comment] 2020-09-16 18:35
This appears to be an issue on both `training_epoch_end()` as well as `validation_epoch_end()`, as there is now no reduction for either.

**Comment by teddykoker** [comment] 2020-09-16 19:26
Seems to work using results objects, but not with dicts

**Comment by williamFalcon** [comment] 2020-09-22 22:29
ok... this is not a bug.

The batch sizes are too small and you're not dropping the last batch.
What ends up happening is that one GPU processes 2 items and the second only 1 item (because your batch size is 3).

And thus your outputs aren't the same length... this is not something we can automate... so you have to either check for that in your code or make sure your batch size is always a multiple of GPUs.

**Closed by williamFalcon** 2020-09-22 22:29 UTC
Labels: DP, Priority, bug / fix, help wanted, v1.0 allowed
