### ISSUE TITLE
`global_step` is incorrect while restarting

### ISSUE THREAD

**Issue by rohitgr7** [PyTorchLightning/pytorch-lightning#11555] opened 2022-01-20 18:32 UTC
## 🐛 Bug

While resuming `global_step` is increased since it's incremented during checkpointing.
https://github.com/PyTorchLightning/pytorch-lightning/blob/1a2536361749d13e3f30cec11c7da11747f425ab/pytorch_lightning/trainer/connectors/checkpoint_connector.py#L343

any reason why this is incremented? even if training is stopped in between (no fault-tolerant), the checkpoint is restarted from the next epoch anyways.

### To Reproduce

Code:
```py
import torch
import os
from pytorch_lightning import LightningModule
from pytorch_lightning import Trainer
from torch.utils.data import Dataset, DataLoader


class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def training_step(self, batch, batch_idx):
        loss = self.layer(batch).sum()
        print(f'Epoch: {self.current_epoch} Global step: {self.global_step}')
        return loss

    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)


class RandomDataset(Dataset):
    def __init__(self, size, num_samples):
        self.len = num_samples
        self.data = torch.randn(num_samples, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


train_data = DataLoader(RandomDataset(32, 64), batch_size=2)
trainer = Trainer(limit_train_batches=2, max_epochs=1, enable_checkpointing=False, enable_progress_bar=False, enable_model_summary=False)
model = BoringModel()
trainer.fit(model, train_dataloaders=train_data)

ckpt_path = 'resume.ckpt'
trainer.save_checkpoint(ckpt_path)

trainer = Trainer(limit_train_batches=2, max_epochs=2, enable_checkpointing=False, enable_progress_bar=False, enable_model_summary=False)
trainer.fit(model, train_dataloaders=train_data, ckpt_path=str(ckpt_path))
```

Output:
```console
Epoch: 0 Global step: 0
Epoch: 0 Global step: 1
Epoch: 1 Global step: 3
Epoch: 1 Global step: 4
```

### Expected behavior

```console
Epoch: 0 Global step: 0
Epoch: 0 Global step: 1
Epoch: 1 Global step: 2
Epoch: 1 Global step: 3
```

### Environment

- PyTorch Lightning Version (e.g., 1.5.0):
- PyTorch Version (e.g., 1.10):
- Python version (e.g., 3.9):
- OS (e.g., Linux):
- CUDA/cuDNN version:
- GPU models and configuration:
- How you installed PyTorch (`conda`, `pip`, source):
- If compiling from source, the output of `torch.__config__.show()`:
- Any other relevant information:

### Additional context

cc @awaelchli @ananthsub @ninginthecloud @rohitgr7

**Comment by carmocca** [comment] 2022-01-21 01:37
I believe this is a duplicate of https://github.com/PyTorchLightning/pytorch-lightning/issues/7406.

I've wanted to fix this for a long time, will tackle global step after the current epoch fix is merged.

**Comment by ninginthecloud** [comment] 2022-01-21 18:27
Hi, @rohitgr7, I think it relates to how user is using checkpointing. If user uses checkpoint callback, then on `on_train_epoch_end`, global_step has decreased by 1, see https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/callbacks/model_checkpoint.py#L298-L309
``` def on_train_epoch_end(self, trainer: "pl.Trainer", pl_module: "pl.LightningModule") -> None:
        """Save a checkpoint at the end of the training epoch."""
        # as we advance one step at end of training, we use `global_step - 1` to avoid saving duplicates
        trainer.fit_loop.global_step -= 1
        if (
            not self._should_skip_saving_checkpoint(trainer)
            and self._save_on_train_epoch_end
            and self._every_n_epochs > 0
            and (trainer.current_epoch + 1) % self._every_n_epochs == 0
        ):
            self.save_checkpoint(trainer)
        trainer.fit_loop.global_step += 1
```
That's why in pytorch-lightning/pytorch_lightning/trainer/connectors/checkpoint_connector.py, global_step increased by 1. 

But you are right, if user uses checkpoint in the way you showed in the example, it could easily come to incorrect value.

**Closed** 2022-01-21 18:50 UTC
Labels: bug, checkpointing
