### ISSUE TITLE
Significant Amount of Idle Time Not Part of Training or Validation Steps

### ISSUE THREAD

**Issue by JSAustin** [PyTorchLightning/pytorch-lightning#2875] opened 2020-08-08 00:07 UTC
## 🐛 Bug

When running in AWS using multi-GPU machines, we begin to notice that time spent between epochs becomes very significant. For our case, we spend 17 seconds without GPU processing between epochs that isn't part of either train or validation time. We don't have other custom functions running, so it isn't anything else beyond PyTorch lightning's other functions. When we go to 8 GPUs, this 17 seconds starts to become very significant (25% of the total time). With 1 GPU, it's not much of a factor. We considered it was model saving, but it also happens if we skip validation on some epochs.

We are using PyTorch Lightning 0.8.5 with ddp and PyTorch 1.5.0. In case it matters, our dataloaders load images each mini-batch from Lustre and aren't limited by bandwidth.

**Comment by ananyahjha93** [comment] 2020-08-08 02:54
@JSAustin can you provide a part of code which can be used to reproduce this issue? Have you tried the same thing with DataParallel instead of DDP?

**Comment by ananyahjha93** [comment] 2020-08-08 15:48
@JSAustin Can you also mention if you are using a logger? (one of lightning's or otherwise)

**Comment by monoelh** [comment] 2020-08-13 08:58
This is due to some reinitializing of the datasets at the beginning of each validation epoch. The time grows with the number of workers used. Especially with small datasets and ddp training this accumulates to a significant amount time, since N workers are spawned for each GPU.
A solution is suggested here:
https://github.com/pytorch/pytorch/issues/15849
Which has to be modified like this to work with newer versions of Pytorch:
(also pytorch lightning 0.8.5 and pytorch 1.5.1)
`
class _RepeatSampler(object):
    """ Sampler that repeats forever.
    Args:
        sampler (Sampler)
    """

    def __init__(self, sampler):
        self.sampler = sampler

    def __iter__(self):
        while True:
            yield from iter(self.sampler)


# avoid reinitiation between epochs
class ContinuousDataLoader(torch.utils.data.DataLoader):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._DataLoader__initialized = False
        self.batch_sampler = _RepeatSampler(self.batch_sampler)
        self._DataLoader__initialized = True
        self.iterator = super().__iter__()

    def __len__(self):
        return len(self.batch_sampler.sampler)

    def __iter__(self):
        for i in range(len(self)):
            yield next(self.iterator)`

**Comment by ananyahjha93** [comment] 2020-08-26 17:27
@JSAustin any updates on this one?

**Comment by JSAustin** [comment] 2020-08-27 23:27
Yes, sorry. I was using both Tensorboard and Comet. I can confirm it also happens if I just use Comet. Haven't yet tried no logger. Providing the code is hard. It's proprietary. Easier to answer questions. I'm going to look at what monoelh mentioned and see if that fixes it.

Thanks!

**Comment by huyvnphan** [comment] 2020-09-02 16:02
Hi I have the same problems here. The idle time between epochs are about 20s seconds and scale up with num_workers for dataloader.

**Comment by edenlightning** [comment] 2020-09-22 20:53
@ananyahjha93 are you able to repro?

**Comment by ananyahjha93** [comment] 2020-09-24 15:38
@edenafek not yet, None of my runs face this issue right now.

**Comment by edenlightning** [comment] 2020-10-02 20:50
closing this for now. feel free to reopen if needed!

**Closed by edenlightning** 2020-10-02 20:50 UTC
Labels: DDP, Priority, bug / fix, help wanted, information needed, v1.0 allowed
