### ISSUE TITLE
using LBFGS optimizer in pytorch lightening the model is not converging as compared to native pytoch + LBFGS

### ISSUE THREAD

**Issue by peymanpoozesh** [PyTorchLightning/pytorch-lightning#4083] opened 2020-10-11 17:44 UTC
### Common bugs:
Comparing the results of LBFGS + Pytorch lightening to native pytorch + LBFGS, Pytorch lightening is not able to update wights and  model is not converging. there are some issues to point out:
1. Adam + Pytorch lightening on MNIST works fine, however LBFGS + Pytorch lightening is not working as expected.
2. LBFGS + Native pytorch works very well, however when we try LBFGS + Pytorch lightening it does not work as expected.

## 🐛 Bug

LBFGS + Pytorch Lightening has problem converging and weights are updating as compared to Adam + Pytorch lightening.

#### Code sample
```
import os
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torchvision.datasets import MNIST
from torchvision import transforms,datasets
from torch.utils.data import DataLoader,random_split
import pytorch_lightning as pl 
from IPython.display import clear_output

class LightningMNISTClassifier(pl.LightningModule):
  def __init__(self):
    super(LightningMNISTClassifier,self).__init__()
    self.layer_1 = nn.Linear(28 * 28, 128)
    self.layer_2 = nn.Linear(128, 256)
    self.layer_3 = nn.Linear(256, 10)
    
  def forward(self, x):
    batch_size, channels, width, height = x.size()
    x=x.view(batch_size,-1)
    # layer 1
    x = self.layer_1(x)
    x = torch.relu(x)
    # layer 2
    x = self.layer_2(x)
    x = torch.relu(x) 
    # layer 3
    x = self.layer_3(x)
    # probability distribution over labels
    x = torch.log_softmax(x, dim=1)  
    return x 
  def prepare_data(self):
    transform=transforms.Compose([transforms.ToTensor(), 
                                  transforms.Normalize((0.1307,), (0.3081,))])
    # prepare transforms standard to MNIST
    mnist_train = MNIST(os.getcwd(), train=True, download=True, transform=transform)
    mnist_test = MNIST(os.getcwd(), train=False, download=True, transform=transform)  
    self.mnist_train, self.mnist_val = random_split(mnist_train, [55000, 5000])

  def train_dataloader(self):
    return DataLoader(self.mnist_train,batch_size=1024)
 
  # def val_dataloader(self):
  #   return DataLoader(self.mnist_val,batch_size=1024)
  # def test_dataloader(self):
  #   return DataLoader(self.mnist_test,batch_size=1024)


  def configure_optimizers(self):
    # optimizer=optim.Adam(self.parameters(),lr=1e-3)
    optimizer = optim.LBFGS(self.parameters(), lr=1e-2)
    return optimizer

  # def backward(self, trainer, loss, optimizer):
  #   loss.backward(retain_graph=True)


  def optimizer_step(self, current_epoch, batch_nb, optimizer, optimizer_idx,
                     second_order_closure, on_tpu=False, using_native_amp=False,
                     using_lbfgs=False):
        # update params
      optimizer.step(second_order_closure) 

  def cross_entropy_loss(self,logits,labels):
    return F.nll_loss(logits,labels)

  def training_step(self,train_batch,batch_idx):
    x,y=train_batch
    logits=self.forward(x)
    loss=self.cross_entropy_loss(logits,y)
    return  {'loss':loss}

  def training_epoch_end(self,outputs):
    avg_loss=torch.stack([x['loss'] for x in outputs]).mean()
    print('epoch={}, avg_Train_loss={:.2f}'.format(self.current_epoch,avg_loss.item()))
    # return {'avg_train_loss':avg_loss}

  # def validation_step(self,val_batch,batch_idx):
  #   x,y=val_batch
  #   logits=self.forward(x)
  #   loss=self.cross_entropy_loss(logits,y)
  #   return {'val_loss':loss}
  # def validation_epoch_end(self,outputs):
  #   avg_loss=torch.stack([x['val_loss'] for x in outputs]).mean()
  #   print('epoch={}, avg_Test_loss={:.2f}'.format(self.current_epoch,avg_loss.item()))
  #   return {'avg_val_loss':avg_loss}

model=LightningMNISTClassifier()
#from pytorch_lightning.callbacks import EarlyStopping
trainer=pl.Trainer(max_epochs=400,gpus=1,
                  #  check_val_every_n_epoch=2,
                  #  accumulate_grad_batches=5,
#                   early_stop_callback=early_stop,
                  #  limit_train_batches=50,
#                   val_check_interval=0.25,
                   progress_bar_refresh_rate=0,
#                   num_sanity_val_steps=0,
                   weights_summary=None)
clear_output(wait=True)
trainer.fit(model)Preformatted text.

```
### Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py
# For security purposes, please check the contents of collect_env_details.py before running it.
python collect_env_details.py
```

Environment:
-Colab and pycharm 
-PyTorch version: 1.6.0+CPU and GPU
-pytorch-lightning==1.0.0rc3

**Comment by rohitgr7** [comment] 2020-10-11 18:13
do you have the code for native PyTorch + LBFGS for the same?

**Comment by peymanpoozesh** [comment] 2020-10-11 21:33
this is the code including MNIST and LBFGS that works fine with native pytorch:

```
import os
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torchvision.datasets import MNIST
from torchvision import transforms,datasets
from torch.utils.data import DataLoader,random_split


class PytorchMNISTClassifier(nn.Module):
  def __init__(self):
    super(PytorchMNISTClassifier,self).__init__()
    self.layer_1 = nn.Linear(28 * 28, 128)
    self.layer_2 = nn.Linear(128, 256)
    self.layer_3 = nn.Linear(256, 10)
  def forward(self, x):
    batch_size, channels, width, height = x.size()
    x=x.view(batch_size,-1)
    # layer 1
    x = self.layer_1(x)
    x = torch.relu(x)
    # layer 2
    x = self.layer_2(x)
    x = torch.relu(x) 
    # layer 3
    x = self.layer_3(x)
    # probability distribution over labels
    x = torch.log_softmax(x, dim=1)  
    return x 

def cross_entropy_loss(logits,labels):
  return F.nll_loss(logits,labels)

if __name__ == '__main__':

  if torch.cuda.is_available():
    device=torch.device('cuda:0')
  else:
    device=torch.device('cpu')

  model=PytorchMNISTClassifier()
  model=model.to(device)
  # optimizer=optim.Adam(model.parameters(),lr=1e-3)
  optimizer = optim.LBFGS(model.parameters(),lr=0.01)

  transform=transforms.Compose([transforms.ToTensor(), 
                                  transforms.Normalize((0.1307,), (0.3081,))])
  # prepare transforms standard to MNIST
  mnist_train = MNIST(os.getcwd(), train=True, download=True, transform=transform)
  mnist_test = MNIST(os.getcwd(), train=False, download=True, transform=transform)  
  mnist_train, mnist_val = random_split(mnist_train, [55000, 5000])

  data=DataLoader(mnist_train,batch_size=1024)

  for Epoch in range(10):
    loss_total=0.
    for i,(x,y) in enumerate(data):
      x=x.to(device)
      y=y.to(device)
      def closure():
        logits=model(x)
        optimizer.zero_grad()
        loss=cross_entropy_loss(logits,y)
        loss.backward(retain_graph=True)
        return loss
    loss_out = optimizer.step(closure)
    loss_total+=loss_out.item()
    print('total_loss--->', loss_total)
```

**Comment by williamFalcon** [comment] 2020-10-12 09:27
You don't need to override optimizer_step... you're only doing it to pass in the second_order closure, but that's exactly what the default implementation does

```
        if on_tpu:
            xm.optimizer_step(optimizer)
        elif using_native_amp:
            self.trainer.scaler.step(optimizer)
        elif using_lbfgs:
            optimizer.step(second_order_closure)
        else:
            optimizer.step()

```

**Comment by rohitgr7** [comment] 2020-10-12 12:38
@williamFalcon still should converge right?? even if the overridden method is doing the same update. Maybe a bug here if it's not converging in pl. will check this.

**Comment by peymanpoozesh** [comment] 2020-10-12 18:29
@williamFalcon we modified the code by removing optimizer_step, however it dose not help solving the issue.

**Comment by rohitgr7** [comment] 2020-10-12 19:00
ok found something. not sure if it's correct or not since I haven't used LBFGS before.

I checked that [optim.LBFGS calls closure 20 times for each step](https://discuss.pytorch.org/t/optim-lbfgs-calls-closure-20-times-for-each-step/14032) and in [this example](https://github.com/pytorch/examples/blob/master/time_sequence_prediction/train.py) it doesn't call any step and `.backward()` explicitly but relies on `optimizer.step(closure)` to do that. Also in every 20 steps the underlying loss is different.

But pl calls an explicit [training_step](https://github.com/PyTorchLightning/pytorch-lightning/blob/42a4fe06b04455d543b7de305af715422a5544c9/pytorch_lightning/trainer/training_loop.py#L748-L753) with the [closure](https://github.com/PyTorchLightning/pytorch-lightning/blob/42a4fe06b04455d543b7de305af715422a5544c9/pytorch_lightning/trainer/training_loop.py#L710-L715) obviously that means it will be called 21 times + an explicit `loss.backward()` is called always.

These are my observations. Anyone with prior experience with LBFGS optimizer can confirm the right way to do this.

**Comment by williamFalcon** [comment] 2020-10-12 19:04
how many times does it get called with pytorch?

i assume that second order methods like lbfgs will likely get called n times? i’m not sure about the details but maybe pytorch approximates the hessian under the hood and thus you’d see all these calls happen?

**Comment by rohitgr7** [comment] 2020-10-12 19:06
> RuntimeError: grad can be implicitly created only for scalar outputs
the given example calls it 20 times.

**Comment by peymanpoozesh** [comment] 2020-10-12 19:13
the default value for the number of iterations is 20 times , based on the pytorch help: 

torch.optim.LBFGS(params, lr=1, max_iter=20, max_eval=None, tolerance_grad=1e-07, tolerance_change=1e-09, history_size=100, line_search_fn=None)

**Comment by peymanpoozesh** [comment] 2020-10-15 03:25
@williamFalcon We are in the process of developing a code that requires me to use LBFGS optimizer. I'd like to use pytorch-lightening platform for this code. do you think that the LBFGS issue can be resolved any time soon in the later versions?

**Comment by justusschock** [comment] 2020-10-21 13:39
@rohitgr7 unfortunately it does not seem to be fixed by #4190 even though the number of backward calls are now correct (there is a test for that). The loss is still not decreasing though (haven't investigated further)

**Comment by rohitgr7** [comment] 2020-10-21 18:17
ok will check this if get some time :)

**Comment by peymanpoozesh** [comment] 2020-10-27 02:25
@williamFalcon it seems that the LBFGS optimizer in the latest version of pytorch-lightening carries the same issue as the previous versions. Is there a way to fix this issue temporarily up to the time that bug gets fixed.

**Comment by peymanpoozesh** [comment] 2020-11-27 05:38
@Borda , @edenlightning ,LBFGS issue dose not seem be fixed in the latest version of pytorch Lightening. should we hope that this issue could be fixed in the near future?  we started a project using pytorch lightening and got stuck because of not being able to use LBFGS optimizer. if it is not fixed yet, would be possible to expedite resolving this issue?

**Comment by Bajo1994** [comment] 2021-01-01 18:36
@williamFalcon @Borda @edenlightning Since this thread will be closed automatically within the next 48 hours, I decided to mention you guys with the hope that the bug gets fixed in a meaningful period. I also appreciate @justusschock for his efforts to fix the issue. Ignoring a bug will not fix it, and it dramatically stops the research activities of people who trusted lightning. Please help us with fixing the bug.

**Comment by Bajo1994** [comment] 2021-01-13 01:51
@carmocca I am very thankful if you take a look at the discussion made here to see whether you can help us fix the issue. The LBFGS bug in lightning has dramatically impacted an important project that I am working on.

**Comment by edenlightning** [comment] 2021-01-14 02:00
Apologize for the delay! We try our best to take a look at every issue with the resources that we have. We bumped the priority for this one and will try to prioritize in the next few weeks!

**Comment by Bajo1994** [comment] 2021-01-14 02:04
@edenlightning I greatly appreciate your help on this subject.

**Comment by akihironitta** [comment] 2021-01-15 16:40
As @justusschock added the tests in https://github.com/PyTorchLightning/pytorch-lightning/pull/4190 and I confirmed locally with `cProfile`, the number of backward passes (the number of times `closure` was called) in PL is 20 which is the same as native PyTorch, so this should be no problem.

However, the return value of `closure` behaves strangely between PL and native PyTorch. (I might be wrong, but I'll continue to look into it tomorrow morning...)

<details>
<summary>PL example from @peymanpoozesh</summary>

```python
import os
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torchvision.datasets import MNIST
from torchvision import transforms, datasets
from torch.utils.data import DataLoader, random_split
import pytorch_lightning as pl


class LightningMNISTClassifier(pl.LightningModule):
    def __init__(self):
        super(LightningMNISTClassifier, self).__init__()
        self.layer_1 = nn.Linear(28 * 28, 128)
        self.layer_2 = nn.Linear(128, 256)
        self.layer_3 = nn.Linear(256, 10)

    def forward(self, x):
        batch_size, channels, width, height = x.size()
        x = x.view(batch_size, -1)
        x = self.layer_1(x)
        x = torch.relu(x)
        x = self.layer_2(x)
        x = torch.relu(x)
        x = self.layer_3(x)
        x = torch.log_softmax(x, dim=1)
        return x

    def prepare_data(self):
        transform = transforms.Compose(
            [transforms.ToTensor(), transforms.Normalize((0.1307,), (0.3081,))]
        )
        mnist_train = MNIST(os.getcwd(), train=True, download=True, transform=transform)
        mnist_test = MNIST(os.getcwd(), train=False, download=True, transform=transform)
        self.mnist_train, self.mnist_val = random_split(mnist_train, [55000, 5000])

    def train_dataloader(self):
        return DataLoader(self.mnist_train, batch_size=1024)

    def configure_optimizers(self):
        # optimizer=optim.Adam(self.parameters(),lr=1e-3)
        optimizer = optim.LBFGS(self.parameters(), lr=1e-2)
        return optimizer

    def cross_entropy_loss(self, logits, labels):
        return F.nll_loss(logits, labels)

    def training_step(self, train_batch, batch_idx):
        x, y = train_batch
        logits = self.forward(x)
        loss = self.cross_entropy_loss(logits, y)
        return {"loss": loss}

    def training_epoch_end(self, outputs):
        # print(outputs)
        avg_loss = torch.stack([x["loss"] for x in outputs]).mean()
        print(
            "epoch={}, avg_Train_loss={:.2f}".format(
                self.current_epoch, avg_loss.item()
            )
        )

model = LightningMNISTClassifier()
trainer = pl.Trainer(
    max_epochs=10, progress_bar_refresh_rate=0, weights_summary=None, fast_dev_run=3,
)
trainer.fit(model)
```

</details>

<details>
<summary>native PyTorch example from @peymanpoozesh</summary>

```python
import os
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torchvision.datasets import MNIST
from torchvision import transforms, datasets
from torch.utils.data import DataLoader, random_split


class PytorchMNISTClassifier(nn.Module):
    def __init__(self):
        super(PytorchMNISTClassifier, self).__init__()
        self.layer_1 = nn.Linear(28 * 28, 128)
        self.layer_2 = nn.Linear(128, 256)
        self.layer_3 = nn.Linear(256, 10)

    def forward(self, x):
        batch_size, channels, width, height = x.size()
        x = x.view(batch_size, -1)
        x = self.layer_1(x)
        x = torch.relu(x)
        x = self.layer_2(x)
        x = torch.relu(x)
        x = self.layer_3(x)
        x = torch.log_softmax(x, dim=1)
        return x


def cross_entropy_loss(logits, labels):
    return F.nll_loss(logits, labels)


if __name__ == "__main__":

    if torch.cuda.is_available():
        device = torch.device("cuda:0")
    else:
        device = torch.device("cpu")

    model = PytorchMNISTClassifier()
    model = model.to(device)
    # optimizer=optim.Adam(model.parameters(),lr=1e-3)
    optimizer = optim.LBFGS(model.parameters(), lr=0.01)

    transform = transforms.Compose(
        [transforms.ToTensor(), transforms.Normalize((0.1307,), (0.3081,))]
    )

    mnist_train = MNIST(os.getcwd(), train=True, download=True, transform=transform)
    mnist_test = MNIST(os.getcwd(), train=False, download=True, transform=transform)
    mnist_train, mnist_val = random_split(mnist_train, [55000, 5000])

    data = DataLoader(mnist_train, batch_size=1024)

    for Epoch in range(10):
        loss_total = 0.0
        for i, (x, y) in enumerate(data):
            x = x.to(device)
            y = y.to(device)
            def closure():
                logits = model(x)
                optimizer.zero_grad()
                loss = cross_entropy_loss(logits, y)
                loss.backward(retain_graph=True)
                print(loss.item())
                return loss

        loss_out = optimizer.step(closure)
        loss_total += loss_out.item()
        print("total_loss--->", loss_total)
```

</details>

**Comment by akihironitta** [comment] 2021-02-21 07:35
@peymanpoozesh @Bajo1994 Sorry for the delay. I haven't figured out why LBFGS behaves differently between Lightning and native PyTorch, but I found an easy workaround, so let me share it here.

The workaround is to use the manual optimization instead of the default automatic optimization (See my notebook linked below for the complete code using BoringModel):
```python
class Model(pl.LightningModule):
    def __init__(self, ...):
        self.automatic_optimization = False
        ...

    def training_step(self, batch, batch_idx):
        optimizer = self.optimizers()
        def closure():
            output = self.layer(batch)
            optimizer.zero_grad()
            loss = self.loss(batch, output)
            self.manual_backward(loss)
            return loss
        loss_out = optimizer.optimizer.step(closure=closure)
        return {"loss": loss_out}
```

See also:
[Full code of the workaround - Google Colab](https://colab.research.google.com/drive/1QEg2jBQfq7xNbyBude9jpLCQiC1ugKhB#scrollTo=RSKOOuiaaQqE)
[Manual optimization - PyTorch Lightning Docs](https://pytorch-lightning.readthedocs.io/en/stable/common/optimizers.html#manual-optimization)

**Comment by akihironitta** [comment] 2021-02-22 07:54
Here are the minimal code examples using BoringModel.
<details>
<summary>Lightning code</summary>

```python
import pytorch_lightning as pl
import torch
from torch.utils.data import DataLoader, Dataset
pl.seed_everything(42)

class RandomDataset(Dataset):
    def __init__(self, size, num_samples):
        self.len = num_samples
        self.data = torch.randn(num_samples, size)
    def __getitem__(self, index):
        return self.data[index]
    def __len__(self):
        return self.len

class BoringModel(pl.LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)
    def forward(self, x):
        return self.layer(x)
    def loss(self, batch, prediction):
        return torch.nn.functional.mse_loss(prediction, torch.ones_like(prediction))
    def training_step(self, batch, batch_idx):
        output = self.layer(batch)
        loss = self.loss(batch, output)
        return {"loss": loss}
    def training_step_end(self, training_step_outputs):
        loss = training_step_outputs["loss"]
        print("closure_loss:", loss)
        return training_step_outputs
    def configure_optimizers(self):
        # optimizer = torch.optim.Adam(self.parameters(), lr=1e-3)
        optimizer = torch.optim.LBFGS(self.parameters(), lr=0.01, max_iter=20)
        return optimizer

def main():
    ds = RandomDataset(32, 100000)
    dl = DataLoader(ds, batch_size=1024)
    model = BoringModel()
    trainer = pl.Trainer(
        progress_bar_refresh_rate=0,
        fast_dev_run=1,
    )
    trainer.fit(model, dl)

if __name__ == "__main__":
    main()
```

</details>

<details>
<summary>Pure PyTorch code</summary>

```python
import torch
import torch.nn as nn
from pytorch_lightning import seed_everything
from torch.utils.data import DataLoader, Dataset
seed_everything(42)

class RandomDataset(Dataset):
    def __init__(self, size, num_samples):
        self.len = num_samples
        self.data = torch.randn(num_samples, size)
    def __getitem__(self, index):
        return self.data[index]
    def __len__(self):
        return self.len

class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.layer = torch.nn.Linear(32, 2)
    def forward(self, x):
        return self.layer(x)

def main():
    ds = RandomDataset(32, 100000)
    dl = DataLoader(ds, batch_size=1024)
    model = Model()
    # optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
    optimizer = torch.optim.LBFGS(model.parameters(), lr=0.01, max_iter=20)
    for epoch in range(3):
        for i, x in enumerate(dl):
            def closure():
                prediction = model(x)
                loss = torch.nn.functional.mse_loss(prediction, torch.ones_like(prediction))
                optimizer.zero_grad()  # removing this line causes the same bug as in Lightning script
                loss.backward()
                print("closure_loss:", loss.item())
                return loss
            loss_out = optimizer.step(closure=closure)

if __name__ == '__main__':
    main()
```

</details>

cc: @carmocca @tchaton

**Comment by justusschock** [comment] 2021-02-22 09:45
@akihironitta Why doesn't `optimizer.step(closure=closure)` work? Why do you have to unwrap it?

**Comment by akihironitta** [comment] 2021-02-22 10:00
@justusschock Fixed! (It was just for print debugging from another script because LightningOptimizer doesn't return the output of `closure()`)

**Comment by Bajo1994** [comment] 2021-02-28 00:48
@akihironitta I am very thankful for your great effort on this bug. I am looking forward to resuming my project as soon as you update the pl package. In my code, I like to switch between LBFGS and Adam optimizers. I like to use the LBFGS when the loss is large and then switch to Adam. I hope switching between these two optimizers would be smooth in pl (I had difficulties in switching between these two optimizers in native PyTorch). I will keep you posted if there is any problem.

**Closed** 2021-03-01 13:36 UTC
Labels: Priority P1, bug / fix, help wanted
