### ISSUE TITLE
When training with ddp, the tensorboard logger is not initialized properly and training does not start.

### ISSUE THREAD

**Issue by bokutotu** [PyTorchLightning/pytorch-lightning#7099] opened 2021-04-19 13:17 UTC
## 🐛 Bug
I am trying to train using 4 gpu's with ddp+hydra+tensorboard, but the training stops with an unknown error.
The condition where I run into this problem is when `cfg.num_gpus` is -1 and `cfg.accelerator` is `ddp`.

When training with only one GPU, the problem does not occur. That is, if `cfg.num_gpus` in the code below is 1 and `cfg.accelerator` is `None`.

### To Reproduce

Use following [**BoringModel**](https://colab.research.google.com/drive/1HvWVVTK8j2Nj52qU4Q4YCyzOm0_aLQF3?usp=sharing) and post here

### Environment
```python
import os

import torch
from torch.utils.data import Dataset

import pytorch_lightning as pl
from pl_examples import cli_lightning_logo
from pytorch_lightning import LightningModule, Trainer

import hydra

class RandomDataset(Dataset):
    """
    >>> RandomDataset(size=10, length=20)  # doctest: +ELLIPSIS
    <...bug_report_model.RandomDataset object at ...>
    """

    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(LightningModule):
    """
    >>> BoringModel()  # doctest: +ELLIPSIS +NORMALIZE_WHITESPACE
    BoringModel(
      (layer): Linear(...)
    )
    """

    def __init__(self):
        """
        Testing PL Module
        Use as follows:
        - subclass
        - modify the behavior for what you want
        class TestModel(BaseTestModel):
            def training_step(...):
                # do your own thing
        or:
        model = BaseTestModel()
        model.training_epoch_end = None
        """
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def loss(self, batch, prediction):
        # An arbitrary loss to have a loss that updates the model weights during `Trainer.fit` calls
        return torch.nn.functional.mse_loss(prediction, torch.ones_like(prediction))

    def step(self, x):
        x = self.layer(x)
        out = torch.nn.functional.mse_loss(x, torch.ones_like(x))
        return out

    def training_step(self, batch, batch_idx):
        output = self.layer(batch)
        loss = self.loss(batch, output)
        return {"loss": loss}

    def training_step_end(self, training_step_outputs):
        return training_step_outputs

    def training_epoch_end(self, outputs) -> None:
        torch.stack([x["loss"] for x in outputs]).mean()

    def validation_step(self, batch, batch_idx):
        output = self.layer(batch)
        loss = self.loss(batch, output)
        return {"x": loss}

    def validation_epoch_end(self, outputs) -> None:
        torch.stack([x['x'] for x in outputs]).mean()

    def test_step(self, batch, batch_idx):
        output = self.layer(batch)
        loss = self.loss(batch, output)
        return {"y": loss}

    def test_epoch_end(self, outputs) -> None:
        torch.stack([x["y"] for x in outputs]).mean()

    def configure_optimizers(self):
        optimizer = torch.optim.SGD(self.layer.parameters(), lr=0.1)
        lr_scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=1)
        return [optimizer], [lr_scheduler]


#  NOTE: If you are using a cmd line to run your script,
#  provide the cmd line as below.
#  opt = "--max_epochs 1 --limit_train_batches 1".split(" ")
#  parser = ArgumentParser()
#  args = parser.parse_args(opt)


class TestModel(BoringModel):

    def on_train_epoch_start(self) -> None:
        print('override any method to prove your bug')

@hydra.main(config_path=[path to config], config_name=[file name].yaml)
def main(cfg):

    # fake data
    train_data = torch.utils.data.DataLoader(RandomDataset(32, 64))
    val_data = torch.utils.data.DataLoader(RandomDataset(32, 64))
    test_data = torch.utils.data.DataLoader(RandomDataset(32, 64))
    checkpoint_callback = ModelCheckpoint(
            monitor='val_loss',
            dirpath='res/model/{}/{}'.format(cfg.model.mode, cfg.atom_name),
            filename=cfg.atom_name+cfg.model.mode+'-{epoch:02d}-{val_loss:.2f}',
            save_top_k=3,
            mode='min',
    )

    tensorboard = pl.loggers.TensorBoardLogger(".", "", "", log_graph=True, default_hp_metric=False)
    # model
    model = TestModel()
     trainer = Trainer(
            logger=tensorboard,
            max_epochs=cfg.epochs,
            gpus=cfg.num_gpus,
            callbacks=[checkpoint_callback],
            accelerator=cfg.accelerator,
            benchmark=True,
            deterministic=True,
    )
    trainer.fit(model, train_data, val_data)
    trainer.test(test_dataloaders=test_data)


if __name__ == '__main__':
    cli_lightning_logo()
    main()
```

```
[2021-04-19 21:53:03,922][HYDRA] Launching 8 jobs locally
[2021-04-19 21:53:03,922][HYDRA] 	#0 : atom_name=CA model=lstm
Global seed set to 1234
ans norm is 0.9445711970329285
input size is (42444, 309, 1203)
ans size (42444, 309, 3)
ans norm is 0.9445711970329285
input size is (10612, 309, 1203)
ans size (42444, 309, 3)
GPU available: True, used: True
TPU available: None, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
usage: train.py [--help] [--hydra-help] [--version] [--cfg {job,hydra,all}] [--package PACKAGE] [--run] [--multirun] [--shell-completion] [--config-path CONFIG_PATH] [--config-name CONFIG_NAME] [--config-dir CONFIG_DIR] [--info] [overrides [overrides ...]]
train.py: error: unrecognized arguments: hydra.run.dir="[path to train.py]/multirun/2021-04-19/21-53-02/0" hydra.job.name=train_ddp_process_1
usage: train.py [--help] [--hydra-help] [--version] [--cfg {job,hydra,all}] [--package PACKAGE] [--run] [--multirun] [--shell-completion] [--config-path CONFIG_PATH] [--config-name CONFIG_NAME] [--config-dir CONFIG_DIR] [--info] [overrides [overrides ...]]
train.py: error: unrecognized arguments: hydra.run.dir="[path to train.py]/multirun/2021-04-19/21-53-02/0" hydra.job.name=train_ddp_process_1 hydra.run.dir="[path to train.py]/multirun/2021-04-19/21-53-02/0" hydra.job.name=train_ddp_process_2
usage: train.py [--help] [--hydra-help] [--version] [--cfg {job,hydra,all}] [--package PACKAGE] [--run] [--multirun] [--shell-completion] [--config-path CONFIG_PATH] [--config-name CONFIG_NAME] [--config-dir CONFIG_DIR] [--info] [overrides [overrides ...]]
train.py: error: unrecognized arguments: hydra.run.dir="[path to train.py]/multirun/2021-04-19/21-53-02/0" hydra.job.name=train_ddp_process_1 hydra.run.dir="[path to train.py]/multirun/2021-04-19/21-53-02/0" hydra.job.name=train_ddp_process_2 hydra.run.dir="[path to train.py]/multirun/2021-04-19/21-53-02/0" hydra.job.name=train_ddp_process_3

```
 - PyTorch Version (e.g., 1.0): 1.8.1
 - OS (e.g., Linux): CentOS
 - How you installed PyTorch :`conda`
 - Build command you used (if compiling from source):
 - Python version: 3.8
 - CUDA/cuDNN version:10.2 , 7605
 - GPU models and configuration: Tesla V100 x 4
 - Any other relevant information:

**Comment by tchaton** [comment] 2021-04-20 08:06
Dear @bokutotu,

It seems to me the issue is the `hydra.run.dir="[path to train.py]/multirun/2021-04-19/21-53-02/0"`
due to @hydra.main(config_path=[path to config], config_name=[file name].yaml).

We are using `os.getcwd()` to get the current cmd being run.

https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/plugins/training_type/ddp.py#L173.

Would you mind resolving this and sharing the error message if any with DDP ?

Best,
T.C

**Closed** 2021-06-09 00:46 UTC
Labels: 3rd-party, DDP, bug / fix, help wanted, won't fix
