### ISSUE TITLE
logging precision issue

### ISSUE THREAD

**Issue by qqueing** [PyTorchLightning/pytorch-lightning#9713] opened 2021-09-27 04:23 UTC
### To Reproduce

https://github.com/PyTorchLightning/pytorch-lightning/issues/8887
https://github.com/PyTorchLightning/pytorch-lightning/issues/8930

This problem is logging precision. 
If I use float32, logging process change my logging
(ex: .
validation_epoch_end(self, metrics)
 'val_clk_sum': tensor(3211., device='cuda:0'),
-->
trainer.logged_metrics
 'val_clk_sum': tensor(3210.9998, device='cuda:0'),
)

I know that if I use float 64 this problem doesn't happen.
But I don't want to use the trainer default of 64 because of logging.

### Expected behavior

Above mentioned

### Environment

- PyTorch Lightning Version (e.g., 1.3.0):
- PyTorch Version (e.g., 1.8)
- Python version:
- OS (e.g., Linux):
- CUDA/cuDNN version:
- GPU models and configuration:
- How you installed PyTorch (`conda`, `pip`, source):
- If compiling from source, the output of `torch.__config__.show()`:
- Any other relevant information:

**Comment by carmocca** [comment] 2021-09-27 15:38
Hi @qqueing 

See my previous response: https://github.com/PyTorchLightning/pytorch-lightning/issues/8887#issuecomment-899055840. A way for us to reproduce the issue is necessary to fix it.

Until then, I'll have to close this issue again. If you can provide the code and your exact environment so that it's reproducible, then we will re-open and look into this.

**Closed by carmocca** 2021-09-27 15:38 UTC
Labels: bug / fix, help wanted
