### ISSUE TITLE
Give users more control on paths used by ModelCheckpoint callback

### ISSUE THREAD

**Issue by hbredin** [PyTorchLightning/pytorch-lightning#4718] opened 2020-11-17 16:41 UTC
When initializing a `ModelCheckpoint` callback like this:
```python
model_checkpoint = ModelCheckpoint(monitor="val_loss", filename="{epoch}-{val_loss:.3f}")
```

we get checkpoint files with names that look like this: 
```
epoch=1-val_loss=0.436.ckpt
```

This looks really nice but the use of this `name=value` pattern is not necessarily what the end user would want. 
In particular, tools like `hydra` will need the end user to escape the `=` sign:

```bash
$ python train.py trainer.resume_from_checkpoint="epoch\=1-val_loss\=0.436.ckpt"
```
which is not very practical.

Here comes my question: would it be possible to allow for more flexibility on the naming scheme of model checkpoints in `ModelCheckpoint` callback?

The culprit is this line:
https://github.com/PyTorchLightning/pytorch-lightning/blob/c208ac68c88a23977ae3d156dabb1440a9f1c9f3/pytorch_lightning/callbacks/model_checkpoint.py#L377

**Comment by carmocca** [comment] 2020-11-17 23:05
Duplicate of #4012

**Closed** 2020-11-17 23:27 UTC
Labels: duplicate
