### ISSUE TITLE
Error meet when reproducing mingpt with pytorch lightning+deepspeed.

### ISSUE THREAD

**Issue by fireragnarous** [PyTorchLightning/pytorch-lightning#12979] opened 2022-05-05 07:58 UTC
## 🐛 Bug

When I tried to reproduce the Mingpt example you provided in https://github.com/SeanNaren/minGPT, I built the environment according to the requirement.txt and tried to train the 1.7B model and met the error below:
![2](https://user-images.githubusercontent.com/55270059/166881767-4fabf499-a1a8-451a-9de8-9236d0cf31fb.JPG)

![1](https://user-images.githubusercontent.com/55270059/166881801-da5ab5d2-d92f-4494-9359-63210c39eeef.JPG)

### Expected behavior
Just follow the instructions in https://github.com/SeanNaren/minGPT
### Environment

using anaconda
- PyTorch Lightning Version (e.g., 1.5.0): 1.6.0
- PyTorch Version (e.g., 1.10): 1.11.0
- Python version (e.g., 3.9): 3.8
- OS (e.g., Linux): Linux
- CUDA/cuDNN version: Cuda compilation tools, release 11.6, V11.6.124
- GPU models and configuration: 2*Nvidia 3090
- How you installed PyTorch (`conda`, `pip`, source): conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch
- Deepspeed: 0.6.3

### Additional context

The CPU size is 48*Intel(R) Xeon(R) Silver 4214 CPU @ 2.20GHz. I wonder if the problem is caused by my limited GPU resources, but according to your introduction the 1.7B version is available to run on a single GPU. I sincerely hope you can help me find the cause of problem together, thank you very much.

cc @SeanNaren @awaelchli @rohitgr7 @akihironitta

**Comment by akihironitta** [comment] 2022-05-05 08:13
Hi @fireragnarous! The error msg looks very similar to https://github.com/microsoft/DeepSpeed/issues/1878.

@SeanNaren Could I ask for your help here? Any idea why we still see the error with DeepSpeed 0.6.3?

**Comment by akihironitta** [comment] 2022-05-05 08:24
@fireragnarous As a quick workaround, you could downgrade DeepSpeed to `<=0.5.10`.

**Comment by fireragnarous** [comment] 2022-05-05 08:32
> @fireragnarous As a quick workaround, you could downgrade DeepSpeed to `<=0.5.10`.

Thank you for your quick reply. I have tried the previous version of deepspeed. When I used 0.5.10, another error occurred:
![3](https://user-images.githubusercontent.com/55270059/166887901-0ffea39d-fa0d-4cd2-b96f-ce13915d00bb.JPG)
 I guess it may because a new version of mingpt has been updated and don't suit old version of deepspeed?

**Comment by SeanNaren** [comment] 2022-05-05 09:15
Will investigate!

**Comment by SeanNaren** [comment] 2022-05-05 09:31
@fireragnarous I'm able to reproduce this error for deepspeed==0.6.3, but 0.5.10 works. The error you're seeing when using 0.5.10 seems to be because you have CUDA 11.6 installed on the local machine but Torch was compiled with 11.3.

This I think is only needed for `DeepSpeedCPUAdam` could you try modifying the command from `--strategy deepspeed_stage_3_offload` to `--strategy deepspeed_stage_3` and letting me know if this works?

**Comment by fireragnarous** [comment] 2022-05-05 09:44
@SeanNaren  yeah, it seems just because the mismatching of CUDA and Torch version,
![4](https://user-images.githubusercontent.com/55270059/166898716-f5878e55-777a-4f38-9137-f1083ffb1d9d.JPG)
I built such an environment just to support the 3090 GPU.

**Comment by fireragnarous** [comment] 2022-05-05 09:44
> @SeanNaren yeah, it seems just because the mismatching of CUDA and Torch version, ![4](https://user-images.githubusercontent.com/55270059/166898716-f5878e55-777a-4f38-9137-f1083ffb1d9d.JPG) I built such an environment just to support the 3090 GPU.

in deepspeed==0.5.10

**Comment by fireragnarous** [comment] 2022-05-05 10:05
@SeanNaren Now I changed the cuda version to 11.3 and deepspeed==0.5.10 correctly worked now.

**Comment by SeanNaren** [comment] 2022-05-05 10:07
Glad there is a workaround, going to make an issue on the DeepSpeed repo to try to get 0.6.3 working!

**Comment by fireragnarous** [comment] 2022-05-05 10:49
@SeanNaren Thanks for you effort.

**Comment by SeanNaren** [comment] 2022-05-05 18:20
@fireragnarous this PR for DeepSpeed seems to fix the issue: https://github.com/microsoft/DeepSpeed/pull/1916

We'll wait till this is merged and a version of DeepSpeed is released to remedy the error!

**Comment by SeanNaren** [comment] 2022-05-06 23:12
@fireragnarous this should be available in the latest DeepSpeed release now, just do `pip install deepspeed -U`!

**Closed by SeanNaren** 2022-05-06 23:12 UTC
Labels: bug, 3rd party, strategy: deepspeed
