### ISSUE TITLE
Indefinite hang when attempting to run tests

### ISSUE THREAD

**Issue by janeyx99** [PyTorchLightning/pytorch-lightning#3593] opened 2020-09-21 21:07 UTC
Running the tests in two different environments both hang (though at different spots). Relevant to [Issue 2041](https://github.com/PyTorchLightning/pytorch-lightning/issues/2041)

**Repro 1 (on Docker with pytorch pre-installed)**
* Code and results found [in this PR](https://github.com/pytorch/pytorch-integration-testing/pull/9)
* Run `make pytorch-lightning` which does the following
    * Set up Docker Image (commands in Dockerfile)
        * Clone v0.9.0
        * Install cmake and requirements
    * Run the tests (commands in Makefile)
* [Results](https://app.circleci.com/pipelines/github/pytorch/pytorch-integration-testing/38/workflows/6e42edac-0bb3-475f-8d56-88378650d102/jobs/177): hangs on `tests/loggers/test_all.py::test_logger_created_on_rank_zero_only`

**Repro 2 (in CentOS 8 without Docker, on CLI)**
* Clone v0.9.0: `git clone --branch 0.9.0 https://github.com/PyTorchLightning/pytorch-lightning`
* Install cmake and requirements: `pip install cmake && pip install --requirement requirements/base.txt --quiet --upgrade`
* Install some more requirements: `HOROVOD_BUILD_ARCH_FLAGS="-mfma" pip install --requirement ./requirements/devel.txt --quiet --upgrade`
* Run the tests: `coverage run --source pytorch_lightning -m pytest pytorch_lightning tests -v --durations=0 --junitxml=junit/test-results-centos-3.8.xml`
* Hangs on `pytorch_lightning/loggers/neptune.py::pytorch_lightning.loggers.neptune.NeptuneLogger`
* Note: this issue also occurs on `master`, not just v0.9.0

**Comment by Borda** [comment] 2020-09-21 22:44
> Running the tests in two different environments both hang (though at different spots). Relevant to [Issue 2041](https://github.com/PyTorchLightning/pytorch-lightning/issues/2041)

I think this is different, long tests and infinitely hanging...
Are you using a base docker image so I can reproduce?

**Comment by Borda** [comment] 2020-09-21 23:19
@janeyx99 mind shareing your environment, because I do not see any hanging tests on master these days...

**Comment by Borda** [comment] 2020-09-22 21:52
it shall be resolved with #3596 and some more following...

**Comment by edenlightning** [comment] 2020-10-02 20:43
@Borda is this solved?

**Comment by Borda** [comment] 2020-10-02 21:09
Just run it on two machines and could not replicate, so I'll close it now... Also, the integration PR was merged fine
@janeyx99 feel free to reopen if needed, but we can fix only master, not past releases... 🐰

**Closed by Borda** 2020-10-02 21:09 UTC
Labels: Priority, bug / fix, help wanted, tests / CI
