### ISSUE TITLE
Disable automatic checkpoint loading

### ISSUE THREAD

**Issue by theSoenke** [PyTorchLightning/pytorch-lightning#368] opened 2019-10-14 19:43 UTC
**Is your feature request related to a problem? Please describe.**
The last checkpoint is being automatically restored when a checkpoint exists. This is an issue for me when the model has previously been trained with different settings or I want to train a network from scratch. 

If I want to use a checkpoint I would prefer to explicitly pass the checkpoint that should be used.

**Describe the solution you'd like**
Provide an option to disable the automatic loading of checkpoints to the trainer.

**Describe alternatives you've considered**
An alternative would be to modify `ModelCheckpoint` class and add that option there so that only that class is responsible for checkpoint creation and loading.

**Comment by williamFalcon** [comment] 2019-10-23 10:21
@theSoenke the previous checkpoint is only used if the experiment has the same version. Is that what you mean? @neggert

**Comment by neggert** [comment] 2019-10-23 14:56
Hmm, okay. I think this should work fine for test tube, even with the changes in #413. This has never worked with MLFlow, since MLFlow generates its own "version". I'll have to give some thought as to how to reproduce this behavior in MLFlow.

**Comment by williamFalcon** [comment] 2020-01-21 13:34
@theSoenke has this been fixed on master? @neggert

**Comment by Ir1d** [comment] 2020-02-27 13:06
Shall we add an option to disable the automatic loading? I sometimes have to run some old version exp, the loading disturbs a lot.

**Comment by williamFalcon** [comment] 2020-02-27 13:23
I kind of want to remove the automatic loading...
@ethanwharris @hadim thoughts?

**Comment by hadim** [comment] 2020-02-27 13:27
I agree. Loading should be done only on demand IMO.

**Comment by ethanwharris** [comment] 2020-02-27 13:28
Yeah, I'm on board with this - perhaps should still throw a warning if a checkpoint is going to be overwritten?

**Comment by Ir1d** [comment] 2020-02-27 13:42
For the time being, is there a recommended way to override this functionality?

**Closed** 2020-03-03 02:50 UTC
Labels: enhancement
