### ISSUE TITLE
pytorch lightning metric.SSIM increasingGPU memory

### ISSUE THREAD

**Issue by hw-kim-ivan** [PyTorchLightning/pytorch-lightning#5733] opened 2021-02-01 10:06 UTC
### Before asking:
1. Try to find answers to your questions in [the Lightning Forum!](https://forums.pytorchlightning.ai/)
2. Search for similar [issues](https://github.com/PyTorchLightning/pytorch-lightning/issues).
3. Search the [docs](https://pytorch-lightning.readthedocs.io/en/latest/).

#### What is your question?
Hello:) Using pytorch lightning metric SSIM(structural index similarity) which good metric for image prediction, GPU memory is continually increasing even new epoch starts.
But when MSE loss is used,  memory shows up and down so no problem is made.
I don't get what is the problem as I'm newbie of ML also Python...
Can you help me find what's the problem with this code?
 
#### Code

class video_pred(pl.LightningModule):

    def __init__(self, hparams=None, model=None):
        super(video_pred, self).__init__()

        ### default config
        self.path = os.path.join(os.getcwd(),dir)
        self.normalize = False
        self.model = model

        ### logging config
        self.log_images = True

        ### Training config
        self.accuracy = pl.metrics.SSIM()
        self.batch_size = opt.batch_size
        self.n_steps_past = 5
        self.n_steps_ahead = 5 

    def SSIM_loss(self, y_hat, y):
        loss_4_each_frame = (self.accuracy(y_hat[:,0,:,:,:].squeeze(), y[:,0,:,:,:].squeeze()) + 
                self.accuracy(y_hat[:,1,:,:,:].squeeze(), y[:,1,:,:,:].squeeze()) +
                self.accuracy(y_hat[:,2,:,:,:].squeeze(), y[:,2,:,:,:].squeeze()) +
                self.accuracy(y_hat[:,3,:,:,:].squeeze(), y[:,3,:,:,:].squeeze()) +
                self.accuracy(y_hat[:,4,:,:,:].squeeze(), y[:,4,:,:,:].squeeze()))/5  #mean SSIM loss for 5 sqeunce images

        return loss_4_each_frame

    def create_video(self, x, y_hat, y):
        preds = torch.cat([x.cpu(), y_hat.cpu()], dim=1)[0]
        y_plot = torch.cat([x.cpu(), y.cpu()], dim=1)[0]
        difference = (torch.pow(y_hat[0] - y[0], 2)).detach().cpu() #L2 norm
        zeros = torch.zeros(difference.shape)

        difference_plot = torch.cat([zeros.cpu().unsqueeze(0), difference.unsqueeze(0).cpu()], dim=1)[
            0] 
        final_image = torch.cat([y_plot, preds, difference_plot], dim=0)
        grid = torchvision.utils.make_grid(final_image, nrow=self.n_steps_past + self.n_steps_ahead)

        return grid

    def forward(self, x):
        output = self.model(x, future_seq=self.n_steps_ahead)
        return output

    def training_step(self, batch, batch_idx):
        x, y = batch[:, 0:self.n_steps_past, :, :, :], batch[:, self.n_steps_past:, :, :, :]
        x = x.permute(0, 1, 4, 2, 3)
        y = y.squeeze().permute(0,1,4,2,3)

        y_hat = self.forward(x).permute(0,2,1,3,4)  # torch.Size([12, 5, 3, 100, 100])
        loss = self.SSIM_loss(y_hat, y)              # SSIM
                                     
        # save learning_rate
        lr_saved = self.trainer.optimizers[0].param_groups[-1]['lr']
        lr_saved = torch.scalar_tensor(lr_saved)

        if self.log_images:
          final_image = self.create_video(x, y_hat, y)
          wandb.log({"Train":[wandb.Image(final_image, caption="Train")]})
          plt.close()

        torch.cuda.empty_cache()
        
        wandb.log({'train_loss':loss})
        return loss

    def validation_step(self, batch, batch_idx):
        x, y = batch[:, 0:self.n_steps_past, :, :, :], batch[:, self.n_steps_past:, :, :, :]
        x = x.permute(0, 1, 4, 2, 3)
        y = y.squeeze().permute(0,1,4,2,3)
        y_hat = self.forward(x).permute(0,2,1,3,4) 
        loss = self.SSIM_loss(y_hat, y)              # SSIM

        if self.log_images:
          final_image = self.create_video(x, y_hat, y)
          wandb.log({"Validation":[wandb.Image(final_image, caption="Validation")]})
          plt.close()

        torch.cuda.empty_cache()
        wandb.log({'val_loss':loss}) # MSE or PSNR or SSIM
       
    def configure_optimizers(self):
        return torch.optim.Adam(self.parameters(), lr=opt.lr, betas=(opt.beta_1, opt.beta_2))

    def data_split(self,train):
      dataset = SequenceDataset(self.path,10)
      radar_train, radar_val, radar_test = random_split(dataset, [1000, 100, len(dataset)-(1000+100)])

      if train:
        return radar_train
      else:
        return radar_val

    def train_dataloader(self):
        train_data = self.data_split(train=True)
      
        train_loader = torch.utils.data.DataLoader(
            dataset=train_data,
            batch_size=self.batch_size,
            shuffle=True)

        return train_loader

    def val_dataloader(self):
        val_data = self.data_split(train=False)

        val_loader = torch.utils.data.DataLoader(
            dataset=val_data,
            batch_size=self.batch_size,
            shuffle=True)

        return val_loader

conv_lstm_model = EncoderDecoderConvLSTM(nf=opt.n_hidden_dim, in_chan=3)
model = video_pred(model=conv_lstm_model)
trainer = Trainer(max_epochs=opt.epochs,
                  gpus=opt.n_gpus,
                  logger= wandb_logger,
                  progress_bar_refresh_rate=20,
                  val_check_interval=0.5)
                  
trainer.fit(model)

#### What have you tried?
tried smaller batch size to see if gpu memory is cleared when new epoch is start, but memory is still increasing..
#### What's your environment?

 - OS: [Win]
 - Packaging [pytorch on google colab]
 - Version [torch : 1.7.0+cu101, pytorch lightning : 1.1.6]

**Comment by robogast** [comment] 2021-02-01 10:44
From the docs:
```Warning: Metric `SSIM` will save all targets predictions in buffer. For large datasets this may to large memory footprint.```

**Comment by hw-kim-ivan** [comment] 2021-02-01 10:51
> From the docs:
> `` Warning: Metric `SSIM` will save all targets predictions in buffer. For large datasets this may to large memory footprint. ``

Thank you for reply:) can you explain what the 'buffer'means?

**Comment by SkafteNicki** [comment] 2021-02-03 08:40
@hw-kim-ivan Yes, currently all predictions and targets are saved to calculate the final value. It can probably be done in a smarter way that just requires a bit more book keeping.
That said, the memory footprint should reset between epochs because the metric states are reset.

**Comment by hw-kim-ivan** [comment] 2021-02-03 09:43
> @hw-kim-ivan Yes, currently all predictions and targets are saved to calculate the final value. It can probably be done in a smarter way that just requires a bit more book keeping.
> That said, the memory footprint should reset between epochs because the metric states are reset.
> 
> Would it be possible for you to reproduce using the [boringmodel](https://colab.research.google.com/drive/1HvWVVTK8j2Nj52qU4Q4YCyzOm0_aLQF3?usp=sharing)

Thank you for reply:) I have two questions if you don't mind...

1. As I'm not familiar with handling memory, I just added [torch.cuda.empty_cache()] at the end of training and validation step, you mean it isn't enough for managing memory? 
2. What does it mean reproducing using the boringmodel? I can see general model inside the link.
Would it be better to reproduce my model into boringmodel? 

It's sad that I can'y fully understand your kind help..

**Comment by SkafteNicki** [comment] 2021-02-03 10:43
@hw-kim-ivan 
1) hopefully you should not have to call `torch.cuda.empty_cache()` in your code as lightning should free up memory between epochs. That is why there may be a bug here
2) when i say "reproduce using boringmodel" I mean if you could put in your own code (only the nessesary part) into a colab notebook so I am able to reproduce the bug/error you are getting

**Comment by hw-kim-ivan** [comment] 2021-02-03 11:42
> @hw-kim-ivan
> 
> 1. hopefully you should not have to call `torch.cuda.empty_cache()` in your code as lightning should free up memory between epochs. That is why there may be a bug here
> 2. when i say "reproduce using boringmodel" I mean if you could put in your own code (only the nessesary part) into a colab notebook so I am able to reproduce the bug/error you are getting

Oh! It would be great to reproduce my code exactly into boringmodel format, but it's what i have done.
https://colab.research.google.com/drive/1LTO4f1SXafpcio1FPu1FSBA59-7ulBVL?usp=sharing
--

**Comment by SkafteNicki** [comment] 2021-02-03 14:05
hi @hw-kim-ivan,
when I try to run your code I get the following error:
`NameError: name 'EncoderDecoderConvLSTM' is not defined`
could you include the remaining code and make sure that all cells can run (under "runtime"->"run all cells")

**Comment by hw-kim-ivan** [comment] 2021-02-04 08:58
https://colab.research.google.com/drive/126YICZq48xBe5MtNck7Hnb2fb_2wV0k8?usp=sharing
Thanks @SkafteNicki  for taking care of:)
It's the code for ConvLSTM Autoencoder for image prediction(predict 5 images from previous 5 images) with 2 stacked encoders and decoders.

The problem is GPU memory continuously increasing with SSIM metric for loss function while MSE isn't. 
--
My log is with wandb!

**Comment by SkafteNicki** [comment] 2021-02-10 14:02
Hi @hw-kim-ivan 
I found the error. You need to manually reset the metric between epochs. Normally lightning will do this for you if you are using `self.log` to log the metric, but since you in this case are using `wandb.log` it is not reset.
Therefore, adding:
``` python
def training_epoch_end(self, outputs):
     self.accuracy.reset()
```
should solve your problem.
Here is a small run I did with your code, with and without manual reset between epochs. As you can see the one without reset the memory keeps building up (because `SSIM` metric is storing input in its buffer) whereas the one with reset only increases during a epoch.
![memory](https://user-images.githubusercontent.com/24896311/107519491-9ef1e080-6bb0-11eb-862c-29e5471d0a24.PNG)

**Comment by hw-kim-ivan** [comment] 2021-02-11 08:29
> Hi @hw-kim-ivan
> I found the error. You need to manually reset the metric between epochs. Normally lightning will do this for you if you are using `self.log` to log the metric, but since you in this case are using `wandb.log` it is not reset.
> Therefore, adding:
> 
> ```python
> def training_epoch_end(self, outputs):
>      self.accuracy.reset()
> ```
> 
> should solve your problem.
> Here is a small run I did with your code, with and without manual reset between epochs. As you can see the one without reset the memory keeps building up (because `SSIM` metric is storing input in its buffer) whereas the one with reset only increases during a epoch.
> ![memory](https://user-images.githubusercontent.com/24896311/107519491-9ef1e080-6bb0-11eb-862c-29e5471d0a24.PNG)

Thanks for inspecting error closely despite the messy code@SkafteNicki.
I wouldn't come up with manual reset without your help!
Thanks again:)

**Comment by SkafteNicki** [comment] 2021-02-11 08:35
@hw-kim-ivan your welcome :]
I am closing this issue, please reopen if this does not solve this problem.

**Closed by SkafteNicki** 2021-02-11 08:35 UTC
Labels: Priority P1, bug / fix, metrics

**Comment by annikabrundyn** [comment] 2021-03-05 16:46
hi @SkafteNicki :) I'm using SSIM as a loss and noticing the same issue of memory blowing up and I don't think it's related to logging.

I've replicated with the boring model - https://colab.research.google.com/drive/1xju-i6w4sdy6pWSDgp_wB_Xvhnko5J8t?usp=sharing

Mind taking a look?

**Comment by annikabrundyn** [comment] 2021-03-05 18:48
Just saw this in the docs - so I guess manual reset is required :)

<img width="886" alt="Screen Shot 2021-03-05 at 1 46 20 PM" src="https://user-images.githubusercontent.com/42869932/110159815-2ea63b80-7db9-11eb-9d38-eb41c2ba0323.png">

**Comment by SkafteNicki** [comment] 2021-03-05 21:10
@annikabrundyn yes sorry for not getting back to you before now. So from v1.2 and onwards you will need to reset the metric yourself.
However, from the code you send it seems like you are not using the metric interface for accumulation (over multiple batches) but just for calculating the SSIM score on a single batch. In that case I highly recommend that you just use fthe functional counterpart:
`from pytorch_lightning.metrics.functional import ssim`
This is a simple python function so it does not save to a buffer and therefore does not need to be reset.

**Comment by annikabrundyn** [comment] 2021-03-06 19:35
you're right! thanks so much for the help @SkafteNicki
