### ISSUE TITLE
Incorrect Precision/Recall/F1 score compared to sklearn

### ISSUE THREAD

**Issue by junwen-austin** [PyTorchLightning/pytorch-lightning#3035] opened 2020-08-18 15:31 UTC
### To Reproduce

1. Copy the code
2. Run the code from top to bottom
3. Compare print results
4. See Difference between sklearn and Lightning

#### Code 

```####
import torch
import numpy as np
import pytorch_lightning as pl
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

print(pl.__version__)


#### Generate binary data
pl.seed_everything(2020)
n = 10000  # number of samples
y = np.random.choice([0, 1], n)
y_pred = np.random.choice([0, 1], n, p=[0.1, 0.9])
y_tensor = torch.tensor(y)
y_pred_tensor = torch.tensor(y_pred)


# Accuracy appears alright
print('accuracy from sklearn', accuracy_score(y, y_pred))
print('accuracy from lightning functional', pl.metrics.functional.accuracy(y_pred_tensor, y_tensor, num_classes=2))
print('accuracy from lightning tensor', pl.metrics.Accuracy(num_classes=2)(y_pred_tensor, y_tensor))

## results
## accuracy from sklearn 0.4986
## accuracy from lightning functional tensor(0.4986)
## accuracy from lightning tensor tensor(0.4986)

# Precision appears to be off, compared to sklearn
print('precision from sklearn', precision_score(y, y_pred))
print('precision from lightning functional', pl.metrics.functional.precision(y_pred_tensor, y_tensor, num_classes=2))
print('precision from lightning tensor', pl.metrics.Precision(num_classes=2)(y_pred_tensor, y_tensor))

## precision from sklearn 0.5005544466622311
## precision from lightning functional tensor(0.4906)
## precision from lightning tensor tensor(0.4906)

#Recall appears to be off, compared to sklearn
print('recall from sklearn', recall_score(y, y_pred))
print('recall from lightning functional', pl.metrics.functional.recall(y_pred_tensor, y_tensor, num_classes=2))
print('recall from lightning tensor', pl.metrics.Recall(num_classes=2)(y_pred_tensor, y_tensor))

## recall from sklearn 0.8984872611464968
## recall from lightning functional tensor(0.4967)
## recall from lightning tensor tensor(0.4967)

#F1 appears to be off, compared to sklearn
print('F1 from sklearn', f1_score(y, y_pred))
print('F1 from lightning functional', pl.metrics.functional.f1_score(y_pred_tensor, y_tensor, num_classes=2))
print('F1 from lightning tensor', pl.metrics.F1(num_classes=2)(y_pred_tensor, y_tensor))

## F1 from sklearn 0.6429283577837915
## F1 from lightning functional tensor(0.4007)
## F1 from lightning tensor tensor(0.4007)

```

### Expected behavior

Precision/Recall/F1 results are expected to be consistent with those from sklearn.
### Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py
# For security purposes, please check the contents of collect_env_details.py before running it.
python collect_env_details.py
```

 - PyTorch Version : 1.5.1
 - OS (e.g., Linux):  MacOS
 - How you installed PyTorch (`conda`, `pip`, source):  Pip
 - Build command you used (if compiling from source):
 - Python version:  3.7
 - CUDA/cuDNN version:   None
 - GPU models and configuration:    @@None
 - Any other relevant information:

**Comment by junwen-austin** [comment] 2020-08-18 15:32
@Borda

**Comment by junwen-austin** [comment] 2020-08-18 15:41
By the way, Precision/Recall/F1 scores are also off in Pytorch-lightning 0.8.5

**Comment by williamFalcon** [comment] 2020-08-18 16:21
i thought we tested against sklearn?

**Comment by Borda** [comment] 2020-08-18 16:26
we do test it here:
https://github.com/PyTorchLightning/pytorch-lightning/blob/321fb8b7c0b39afa1fb32f83fc6b3a8a5d38bd82/tests/metrics/functional/test_classification.py#L38-L59

**Comment by Borda** [comment] 2020-08-18 16:27
@justusschock @SkafteNicki mind have look, pls 🐰

**Comment by SkafteNicki** [comment] 2020-08-18 16:31
Its because we calculate the `macro` average instead of the `micro` average which is the default in sklearn

**Comment by SkafteNicki** [comment] 2020-08-18 16:34
At some point we should probably support the different averaging methods that sklearn also have as one averaging method may be more meaningful in some cases (like very unbalanced datasets)

**Comment by junwen-austin** [comment] 2020-08-18 16:59
I figured out the reason why this is a discrepancy:

for binary classification, to recover sklearn, precision/recall/F1 should be done something like below:
```
pl.metrics.functional.precision(y_pred_tensor, y_tensor, num_classes=2, reduction='none')[1])

```
where reduction by default is `elementwise_mean` instead of `none`, the [1] returns the score for class 1 

We can close the issue for now, but **it would be really good to update the document to reflect these subtle differences.** 

For multi-classes, I assume there will be more nuances between Lightning and Sklearn, given different ways of doing average (`macro`,
`micro` and so on

**Comment by Borda** [comment] 2020-08-19 15:23
@junwen-austin mind update it docs so we avoid similar questions in future...

**Comment by junwen-austin** [comment] 2020-08-19 18:49
@Borda Yes I plan to do more testing on metrics if you do not mind and then update the docs so that we have more examples. Does this sound good to you?

**Comment by raynardj** [comment] 2020-09-01 06:03
# 🐛 Bug

> We can not produce sklearn's ```micro``` f1 with PL, right?

For some scenario, like classifying 200 classes, with most of the predicted class index is right, ```micro f1``` makes a lot more sense than ```macro f1```

Steps to reproduce the behavior:

* Copy the code
* Run the code from top to bottom
* Compare print results
* See Difference between sklearn and Lightning

```python
from sklearn.metrics import f1_score as sklearn_f1
from pytorch_lightning.metrics import F1
import torch

# create sample label
y = torch.randint(high = 199,size = (210,))

print("dummy label/prediction")
print(y)

# If the model answered perfect predictions within batch, it should print out a perfect score.
sk_macro_f1 = sklearn_f1(y.numpy(),y.numpy(),labels=list(range(200)),average = 'macro')
sk_micro_f1 = sklearn_f1(y.numpy(),y.numpy(),labels=list(range(200)),average = 'micro')

pl_f1 = F1(200,reduction = "elementwise_mean")
pl_ele_f1 = pl_f1(y,y)

print(f"""sklearn macro f1:\t{sk_macro_f1}
skelarn micro f1:\t{sk_micro_f1}
pl_elementwise f1:\t{pl_ele_f1}
""")

```


will output the following, while PL produce the macro f1 0.625, but the model predicted perfectly 

```
dummy label/prediction
tensor([ 15,  27,  80,  52,  53, 127, 168, 157, 170, 146, 123, 149,  70,   2,
        175, 163,  43, 194, 125,  52, 147, 150, 134, 133,   0, 166, 160, 166,
        165,  16, 184, 125, 180, 186,  56,  83, 189, 197,  22,  56, 104, 141,
        174, 192,   5,  31,   2, 170, 131, 166, 191, 167, 104,  55, 163,  92,
        193, 146,  68,  52,  11, 187,  40, 170, 137, 121,  16,  56, 164,  42,
        173,  45, 176,  49,  70,  15, 106, 129, 115, 179,   7, 124,  64, 142,
        127,  67, 120, 133,  90, 155,  97, 164,  41,  16, 113, 167, 172, 160,
         99, 139,  69,  64, 157, 107, 100, 179, 122, 169,  27,  36, 134, 113,
         29,  50,  35,  32, 174, 193, 177,  93, 183, 165, 180,  85, 134,  63,
         64,  23,  23,   0,   7,  42,  22,  11, 141, 180,  87, 182, 144, 121,
         33,  99,  45, 110,  24, 158,  22, 181, 132, 150, 146,  35,  23,   0,
        165, 178, 147,  55,  63,  45, 175,  79, 121,  63,  36,  92, 108, 109,
        170, 193, 161, 122,  41,   6,  71, 150,  32,  43, 188,  17, 134, 129,
         20, 189, 118,  35,  68,  78,  29,  76,  43, 139, 119,  11,  23, 146,
        135,  74,  87,  66, 153,   3,  84,  98, 131, 109, 191, 188,  81, 177])
/anaconda3/lib/python3.7/site-packages/pytorch_lightning/utilities/distributed.py:37: UserWarning: You have set 200 number of classes if different from predicted (198) and target (198) number of classes
  warnings.warn(*args, **kwargs)
sklearn macro f1:	0.625
skelarn micro f1:	1.0
pl_elementwise f1:	0.625
```

**Comment by justusschock** [comment] 2020-09-01 06:44
@raynardj We are already tracking it in this issue and it will be part of our new aggregation system. However this may take a while to lay out.

**Comment by raynardj** [comment] 2020-09-02 02:14
> @raynardj We are already tracking it in this issue and it will be part of our new aggregation system. However this may take a while to lay out.

I'm also in the slack by the same user name, anything I can contribute to the matter?

**Comment by SkafteNicki** [comment] 2020-09-02 07:40
@raynardj if you want to help, please write to me on slack (username Nicki Skafte), as I already have some code ready that you could help finish :]

**Closed** 2020-09-15 12:36 UTC
Labels: Metrics, Priority, bug / fix, help wanted
