### ISSUE TITLE
ssim functional metric not working with 16 bit precision

### ISSUE THREAD

**Issue by annikabrundyn** [PyTorchLightning/pytorch-lightning#6383] opened 2021-03-06 21:46 UTC
## 🐛 Bug

ssim functional metric doesn't work with native 16 bit precision

## Please reproduce using the BoringModel

https://colab.research.google.com/drive/1Wzxjq-oQavT-kg9go9Ti-AcCEhuir7H9?usp=sharing

if you remove 16 bit precision from trainer it works but with 16 bit precision it gives the following error:

```TypeError: Expected `preds` and `target` to have the same data type. Got pred: torch.float32 and target: torch.float16.```

**Comment by awaelchli** [comment] 2021-03-07 03:31
There is an explicit check in ssim for the dtype
https://github.com/PyTorchLightning/pytorch-lightning/blob/966184a452c773a691b063195c817f3aed899f16/pytorch_lightning/metrics/functional/ssim.py#L42

However, even if both preds and target are half tensors (to avoid the reported exception), we find that ssim does not support half tensors:

```python
import torch
from pytorch_lightning.metrics.functional import ssim

pred = torch.rand([16, 1, 16, 16])
target = pred * 1.25

pred = pred.half()
target = target.half()

out = ssim(pred, target)
```

Raises:
```
  File "C:/Users/aeduw/Documents/Repositories/pytorch-lightning/ax.py", line 8, in <module>
    out = ssim(pred, target)
  File "C:\Users\aeduw\Documents\Repositories\pytorch-lightning\pytorch_lightning\metrics\functional\ssim.py", line 154, in ssim
    return _ssim_compute(preds, target, kernel_size, sigma, reduction, data_range, k1, k2)
  File "C:\Users\aeduw\Documents\Repositories\pytorch-lightning\pytorch_lightning\metrics\functional\ssim.py", line 79, in _ssim_compute
    data_range = max(preds.max() - preds.min(), target.max() - target.min())
RuntimeError: "max_all" not implemented for 'Half'
```

**Comment by awaelchli** [comment] 2021-03-07 03:38
@ydcjeff do you have an idea if ssim can be written to support float16?

**Comment by ydcjeff** [comment] 2021-03-07 14:47
It works with half CUDA tensors, but not CPU tensors (pytorch doesn't support it)
```py
>>> pred = torch.rand([16, 1, 16, 16], device='cuda', dtype=torch.half)
>>> target = pred * 1.25
>>> ssim(pred, target)
tensor(0.9521, device='cuda:0', dtype=torch.float16)
```

**Comment by awaelchli** [comment] 2021-03-07 15:04
@ydcjeff thanks, that makes sense. 

Then this leaves the question how do we handle the case when the types are different.
Currently user has to convert the target tensor to the type of the predictions which are half type.

```python
target = target.type_as(pred)
ssim(pred, target)
```
(@annikabrundyn this is the workaround for your use case)

@ydcjeff Would it be reasonable to convert target automatically to the type of pred in ssim?

**Comment by ydcjeff** [comment] 2021-03-07 15:26
I would avoid to covert automatically (such as `pred` being float16, `target` being `unit8`)
It is better let user handle the type IMO

**Comment by awaelchli** [comment] 2021-03-07 15:34
@justusschock @SkafteNicki requesting comment/confirm if we should leave it as is and let user make sure types match

**Comment by SkafteNicki** [comment] 2021-03-07 19:47
I am aware of this issue, and I agree with @ydcjeff that we should not do any automatic casting.
Please, see this issue https://github.com/PyTorchLightning/pytorch-lightning/issues/5317 where I have listed all metrics that does not work with half precision on cpu (https://github.com/PyTorchLightning/pytorch-lightning/issues/5317#issuecomment-753305053)
I have some work in progress on a local branch (https://github.com/SkafteNicki/pytorch-lightning/tree/metrics/float16_support)  that aims to solve this issue for some of the metrics + add test to proper document which metrics support this.

**Comment by awaelchli** [comment] 2021-03-07 19:50
great, thanks @SkafteNicki 
closing and treating this as duplicate of #5317 then

**Closed by awaelchli** 2021-03-07 19:50 UTC
Labels: bug / fix, help wanted, metrics, with code

**Comment by annikabrundyn** [comment] 2021-03-07 22:02
ah nice! sorry i didn't see the open issue before. i think it was mostly confusing because i'm also using psnr and it's not giving a type error so it felt a bit weird to only cast for ssim since both are PL metrics. thanks for all the help!
