### ISSUE TITLE
stopped calling datamodule.train_dataloader() when tuning the batch_size using pl.trainer.tune()

### ISSUE THREAD

**Issue by randommm** [PyTorchLightning/pytorch-lightning#7562] opened 2021-05-15 19:59 UTC
**version 1.3.1 pytorch_lightining stopped calling datamodule.train_dataloader() when tuning the batch_size using pl.trainer.tune()**

I don't know if this was reported already, but since version 1.3.1 pytorch_lightining stopped calling datamodule.train_dataloader() when tuning the batch_size using pl.trainer.tune(), so the batch_size effectivelly stays fixed at 2, see the attached files, in particular the print statements of

```python
    def train_dataloader(self):
        print("THIS SHOULD BE CALLED!!!!!", self.batch_size)
```
and
```python
    def training_step(self, train_batch, batch_idx):
        inputv, target = train_batch
        output = self.forward(inputv)
        print("actual batch_size", len(inputv))
```
when tune is called.

[code_examples.zip](https://github.com/PyTorchLightning/pytorch-lightning/files/6488147/code_examples.zip)

**Comment by Lucklyric** [comment] 2021-05-16 03:53
@randommm I think the problem is caused by a set of refractory works that happened in 1.3. 
https://github.com/PyTorchLightning/pytorch-lightning/blob/e126649d19e85c449b007008361f10374878f2f4/pytorch_lightning/tuner/batch_size_scaling.py#L150
iterative batch_size tunning is now calling `trainer.tunner._run()` rather than `trainer.fit()` (in 1.2)
https://github.com/PyTorchLightning/pytorch-lightning/blob/1396321b4d779dba837749dfba5e12fe5dac00d0/pytorch_lightning/tuner/batch_size_scaling.py#L177
Hence, there is no fresh calling of `training_loop.setup_fit` as well as `data_connector.attach_data()`
https://github.com/PyTorchLightning/pytorch-lightning/blob/1396321b4d779dba837749dfba5e12fe5dac00d0/pytorch_lightning/trainer/training_loop.py#L100:9

**Comment by Lucklyric** [comment] 2021-05-16 05:23
Hi @randommm, I think the problem is caused by
1. train and val dataloaders only reset when they are none. We can change it to `if self.trainer.train_dataloader is None or self.trainer.tunning:`
https://github.com/PyTorchLightning/pytorch-lightning/blob/e126649d19e85c449b007008361f10374878f2f4/pytorch_lightning/trainer/training_loop.py#L184-L195

2. Then the trainer.tuning status should be set to True before _run in Tuner
https://github.com/PyTorchLightning/pytorch-lightning/blob/e126649d19e85c449b007008361f10374878f2f4/pytorch_lightning/tuner/tuning.py#L60-L65

**Comment by randommm** [comment] 2021-05-16 12:29
Thanks @Lucklyric ! Was it like that on versions prior to 1.3.0/1.3.1?

**Comment by Lucklyric** [comment] 2021-05-16 16:50
Hi, @randommm. This section was recently updated. In fact, there are numerous changes in 1.3 regarding refactoring in the tuner and trainer. As a result, we'll have to wait for more feedback to validate this fix. However, I am certain that your problem is caused by not calling the reset function.

**Comment by Lucklyric** [comment] 2021-05-17 16:43
@randommm , sorry this might not be the solution, I thought it is `TunerStatus.RUNNING`, but it is `TrainerStatus.RNNING` which means it is always True. However, I tried to check `trainer.tunning == True`, it fixes the issue but fails one test case. I am keeping investigating it.

**Comment by tchaton** [comment] 2021-05-21 08:26
Hey @randommm, @Lucklyric,

I am not entirely sure, but I think this bug could be resolved by deleting dataloaders reference to the trainer as the end of the tuner tune call.

I think it could be done right there with a teardown function: https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/tuner/tuning.py#L56, deleting reference on the trainer to the dataloader.

Does anyone of you wants to give it a try ?

Best,
T.C
Best,
T.C

**Closed** 2021-05-24 08:21 UTC
Labels: Priority P0, bug / fix, data / DataModule, help wanted
