### ISSUE TITLE
ddp only uses 1 gpu when multi gpus are available

### ISSUE THREAD

**Issue by lolongcovas** [PyTorchLightning/pytorch-lightning#5254] opened 2020-12-23 22:28 UTC
## 🐛 Bug

When using accelerator=ddp and gpus=2 only one gpu is used but 2 processes are launched.

### To Reproduce
```CUDA_VISIBLE_DEVICES=0,1 python3 pl_examples/basic_examples/simple_image_classifier.py --accelerator ddp  --gpus 2```

Here a screenshot
```+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 00000000:01:00.0 Off |                  N/A |
| 31%   60C    P0    51W / 240W |    512MiB /  8119MiB |     14%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:02:00.0 Off |                  N/A |
|  0%   50C    P2    74W / 280W |   1354MiB / 11178MiB |     80%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1866      G   ...AAAAAAAAAAAACAAAAAAAAAA= --shared-files   120MiB |
|    0      2442      G   /usr/lib/xorg/Xorg                           166MiB |
|    0      2577      G   /usr/bin/gnome-shell                         212MiB |
|    0      3464      G   /usr/lib/firefox/firefox                       1MiB |
|    0      6887      G   /usr/lib/firefox/firefox                       1MiB |
|    0     13528      G   /usr/lib/firefox/firefox                       1MiB |
|    1     20965      C   python3                                      671MiB |
|    1     20988      C   .../projects/byol-pytorch/VENV/bin/python3   671MiB |
+-----------------------------------------------------------------------------+
```

The two processes are 20965 and 20988 and both are using gpu 1

**Comment by awaelchli** [comment] 2020-12-24 07:36
![image](https://user-images.githubusercontent.com/5495193/103070957-f5846a80-45c2-11eb-99bd-1463ea1a35a4.png)


Cannot reproduce on master, which version of Lightning are you rocking?

**Comment by lolongcovas** [comment] 2020-12-24 09:18
```
>>> import pytorch_lightning as pl
>>> pl.__version__
'1.1.2'
>>> 
```

**Comment by awaelchli** [comment] 2020-12-24 09:41
no luck. I am running the same command you posted.

**Comment by zhouyong64** [comment] 2020-12-31 03:42
I have the exact same issue with version 1.1.2.

**Comment by awaelchli** [comment] 2021-01-01 16:16
Unfortunately original poster @lolongcovas has not provided any information about their environment. @zhouyong64 if you have any further details please share them, since I cannot reproduce the observations reported here, neither on dev branch and nor on 1.1.2.

**Comment by tchaton** [comment] 2021-01-04 20:09
Any updates on this issue ?

**Comment by NadavLightricks** [comment] 2021-01-11 14:13
The same issue occurs for me, again with version 1.1.2 - 

![image](https://user-images.githubusercontent.com/52624464/104192732-eb1df980-5427-11eb-8ae3-4f91526a237f.png)

**Comment by edenlightning** [comment] 2021-01-11 15:51
would @NadavLightricks and @lolongcovas be able to give us reproducible example?

**Comment by lolongcovas** [comment] 2021-01-12 11:10
hi, I just launched the example:
```CUDA_VISIBLE_DEVICES=0,1 python3 pl_examples/basic_examples/simple_image_classifier.py --accelerator ddp --gpus 2```
with the version of pytorch lightning 1.1.2

**Comment by awaelchli** [comment] 2021-02-01 16:39
Ok, I will provide my env details:
```
* CUDA:
        - GPU:
                - GeForce GTX 1080 Ti
                - GeForce GTX 1080 Ti
                - GeForce GTX 1080 Ti
                - GeForce GTX 1080 Ti
        - available:         True
        - version:           9.2
* Packages:
        - numpy:             1.19.1
        - pyTorch_debug:     False
        - pyTorch_version:   1.7.1
        - pytorch-lightning: 1.1.2
        - tqdm:              4.48.2
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - 
        - processor:         x86_64
        - python:            3.7.5
        - version:           #67~18.04.1-Ubuntu SMP Tue Jan 5 22:01:05 UTC 2021


```

`CUDA_VISIBLE_DEVICES=0,1 python3 pl_examples/basic_examples/simple_image_classifier.py --accelerator ddp --gpus 2`
on master branch, as expected:

![master](https://user-images.githubusercontent.com/5495193/106487967-81878d00-64b3-11eb-9241-b167d599d831.png)

on 1.1.2 as reported by you with the same command: 

![1 1 2](https://user-images.githubusercontent.com/5495193/106488096-9f54f200-64b3-11eb-9e82-407e12ba6944.png)

and on the latest development branch 1.2-dev:

![1 2-dev](https://user-images.githubusercontent.com/5495193/106488521-168a8600-64b4-11eb-9c81-357389066251.png)

**Comment by edenlightning** [comment] 2021-02-01 16:47
Closing this for now, let us know if there are any other details that might help us try to reproduce.

**Closed by edenlightning** 2021-02-01 16:47 UTC
Labels: DDP, Work as intended, bug / fix, help wanted

**Comment by awaelchli** [comment] 2021-02-01 16:49
@lolongcovas check the readme page on this github for supported pytorch and python combinations. maybe you are running an unsupported version.

**Comment by liutaocode** [comment] 2023-07-21 11:50
> KUBERNETES_PORT

Great! just run : unset KUBERNETES_PORT  
It works for me.

**Comment by awaelchli** [comment] 2023-07-21 11:55
@liutaocode What system are you on? 

It seems that this was the solution for multiple users here too (https://github.com/Lightning-AI/lightning/issues/16236), so we should probably think about excluding this env var in the detection to avoid false positives.
