### ISSUE TITLE
[Feat] Add support for fault tolerance within the ValidationLoop

### ISSUE THREAD

**Issue by tchaton** [PyTorchLightning/pytorch-lightning#9564] opened 2021-09-16 13:45 UTC
### Motivation

Lightning 1.5 is going to introduce Fault Tolerant feature.
However, the feature is still requires some improvements. As a matter of fact, Lightning doesn't support to be restarted within the ValidationLoop yet.

This issue tracks this addition. 

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

<sub>

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, finetuning and solving problems with deep learning

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks and more for research and production with PyTorch Lightning and PyTorch

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

</sub>

**Comment by awaelchli** [comment] 2021-09-17 12:33
duplicate of #9130

**Closed** 2021-09-24 16:21 UTC
Labels: enhancement
