### ISSUE TITLE
accuracy metric dosen't support windows

### ISSUE THREAD

**Issue by davinnovation** [PyTorchLightning/pytorch-lightning#2357] opened 2020-06-25 06:14 UTC
## 🐛 Bug

Pytorch Metric.Accuracy uses `ReduceOp` from 'torch.distribution' but torch.distributrion doesn't support `windows`
 - https://github.com/pytorch/pytorch/blob/cf8a9b50cacb1702f5855859c657a5358976437b/torch/distributed/__init__.py#L10 : `torch.distributed is available on Linux and MacOS.` 

### To Reproduce

Use Metric.Accuracy in Windows environment

#### Code sample

- I use code sample from `https://github.com/PyTorchLightning/pytorch-lightning/issues/2355`

### Expected behavior

add check OS in `metric.accuracy` and use condition for import different module 
``` 
  try:
    return platform.linux_distribution()
  except:
    return "N/A"
```
or warning to windows user, they can't use `metric.accuracy`

### Environment

```
* CUDA:
        - GPU:
                - GeForce RTX 2080 Ti
                - GeForce GTX 1080 Ti
        - available:         True
        - version:           10.1
* Packages:
        - numpy:             1.18.1
        - pyTorch_debug:     False
        - pyTorch_version:   1.5.1
        - pytorch-lightning: 0.8.1
        - tensorboard:       2.2.1
        - tqdm:              4.46.0
* System:
        - OS:                Windows
        - architecture:
                - 64bit
                - WindowsPE
        - processor:         Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
        - python:            3.6.10
        - version:           10.0.18362
```
### Additional context
```
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    from pytorch_lightning.metrics.functional import accuracy
  File "C:\Users\dcho\Anaconda3\envs\torch_py36\lib\site-packages\pytorch_lightning\metrics\__init__.py", line 1, in <module>
    from pytorch_lightning.metrics.converters import numpy_metric, tensor_metric
  File "C:\Users\dcho\Anaconda3\envs\torch_py36\lib\site-packages\pytorch_lightning\metrics\converters.py", line 220, in <module>
    reduce_op: Optional[torch.distributed.ReduceOp] = None,
AttributeError: module 'torch.distributed' has no attribute 'ReduceOp'
```

Always thanks for developing & maintaining the cool framework

**Comment by SkafteNicki** [comment] 2020-06-25 10:36
We are aware of this problem (duplicate of https://github.com/PyTorchLightning/pytorch-lightning/issues/2347), and it will be fixed in the next release

**Closed** 2020-06-27 01:38 UTC
Labels: Priority, duplicate, enhancement, help wanted
