### ISSUE TITLE
Distributed Data Training

### ISSUE THREAD

**Issue by bluesky314** [PyTorchLightning/pytorch-lightning#3034] opened 2020-08-18 14:43 UTC
```
import pytorch_lightning as pl
class LightningModel(pl.LightningModule):

    def __init__(self):
        super(LightningModel, self).__init__()
        # not the best model...
        self.model = U2NET(3, 1)

    def forward(self, x):
        # called with self(x)
        return self.model(x)

    def training_step(self, batch, batch_nb):
        # REQUIRED
        x = batch['image'].float() 
        labels_v=batch['label'].double() 
        
        d0, d1, d2, d3, d4, d5, d6 = self(x)
        d0, d1, d2, d3, d4, d5, d6,loss2, loss = muti_bce_loss_fusion(d0, d1, d2, d3, d4, d5, d6, labels_v)
        
        tensorboard_logs = {'train_loss': loss}
        return {'loss': loss, 'log': tensorboard_logs}


    def configure_optimizers(self):

        opt=torch.optim.Adam(model.parameters(), lr=lr, betas=(0.9, 0.999), eps=1e-08, weight_decay=0) 
#         scheduler=CombineCos(opt,0.2,lr,lr,5e-4,len(self.train_dataloader()),100)
        return opt

    def train_dataloader(self):
        loaders=get_loader([size,size])
        return loaders['train']


    
train_loader = get_loader([size,size])['train']
model = LightningModel()

trainer = pl.Trainer(gpus=1)
trainer.fit(model, train_loader)

```

I want to do Distributed Training with 2 gpus with data parallel. 
This works just fine with one gpu. But when I do `trainer = pl.Trainer(gpus=2)` or `trainer = pl.Trainer(gpus=[0,1])` I get an error:
![Screen Shot 2020-08-18 at 8 12 18 PM](https://user-images.githubusercontent.com/35393972/90527485-37be1b00-e18f-11ea-9f79-cfc3e55e5e78.png)

System
 - 3.6
 - Linux
 - pip
 - Build command you used (if compiling from source):
 - Python version:
 - 10.1
 - Nvidia-100

**Comment by ananyahjha93** [comment] 2020-08-18 16:17
@bluesky314  I am not able to reproduce the same bug, can you provide the lightning version and some code to reproduce this exactly?

**Comment by bluesky314** [comment] 2020-08-18 16:48
I just installed lightning via pip install command given in the docs. My pytorch version is 1.6. The code worked with gpu was set to 1. As you can see in the message up and below,  the error traces internally to multiprocessing files when trainer.fit is called and has not much to do with my code.  The run time error also cannot be caused by any of my definitions. 

Before this I was using wandb to log experiments with single gpu, after I changed to multiple gpu I got a wandb error saying wandb.init was not called. (wandb was not actually used to log anything, just to view the terminal log from wandb page so it did not interact with Lightning) I think copying the program to multiple cpus is leading to a problem.
 
Here is the extended error:
<img width="780" alt="Screen Shot 2020-04-04 at 10 18 39 AM" src="https://user-images.githubusercontent.com/35393972/90541165-d5214b00-e19f-11ea-9aff-4da6e59e9bf8.png">

**Comment by awaelchli** [comment] 2020-08-18 18:08
> I just installed lightning via pip install command given in the docs

You will probably get 0.8.5. Could you try to install the 0.9.0rc13 release?
`pip install pytorch-lightning==0.9.0rc13 --upgrade`

**Comment by bluesky314** [comment] 2020-08-19 07:27
I updated it as above but am getting the same error. The difference is that the print commands at the top of the files are printed twice, meaning that it is making 2 copies of the code but the Runtime error remains

**Comment by awaelchli** [comment] 2020-08-19 11:18
I think you need to put 
```python
if __name__ == "__main__"
    ...
```
before the start of your script. This is a python multiprocessing thing, it imports the module before it runs it, so you need to guard the entry point of the program. Closing this as my suspicion is very high this is the problem here. Let me know if this fixes it for you.

**Comment by bluesky314** [comment] 2020-08-19 12:04
Thanks, add

has removed the previous error but now the process gets stuck at:
<img width="892" alt="image" src="https://user-images.githubusercontent.com/35393972/90632464-12d6b000-e242-11ea-9cf7-e562ebe53216.png">

The training progress does not start showing, but 1.6gb on the 2 gpus gets used up.

**Comment by awaelchli** [comment] 2020-08-19 12:28
And what about distributed_backend="ddp_spawn"? 
What is dso_loader.cc? Make sure this actually supports running on multi-GPU.

**Comment by bluesky314** [comment] 2020-08-19 12:32
I am using pytorch so not sure why tensorboard is getting involved. dso_loader.cc is not my file. This is an AWS instance with 2gpus.

Yes, I have used this code with nn.DataParallel and it worked there. To remove the single cpu bottleneck I wanted to do Distributed DataParallel so someone recommended I try Lightning as it is easier to set up.

**Comment by awaelchli** [comment] 2020-08-19 12:34
ok, is `distributed_backend="ddp_spawn"` also getting stuck?

**Comment by bluesky314** [comment] 2020-08-19 12:34
Let me try and get back

**Comment by williamFalcon** [comment] 2020-08-19 23:12
yeah, this original issue was not using __main__ which is a pytorch requirement.

**Closed by williamFalcon** 2020-08-19 23:12 UTC
Labels: Priority, help wanted, information needed

**Comment by bluesky314** [comment] 2020-08-24 10:18
@awaelchli @williamFalcon I have created a new issue for the new error: https://github.com/PyTorchLightning/pytorch-lightning/issues/3117
