### ISSUE TITLE
Logging confusion matrix

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [PyTorchLightning/pytorch-lightning#9252] opened 2021-09-01 11:20 UTC
Hi guys,

I hope you are all doing great!

`self.log` doesn't support multi-dim metrics such as confusion matrix since it has to apply a `reduction` function, `mean` by default. I would like to be able to properly log and fetch my confusion matrix in a callback but this seems to not be possible atm.

Is there a way to properly plot tensors without reducing them?

Thank you

Francesco

cc @borda @carmocca @edward-io @ananthsub @justusschock @awaelchli

**Comment by carmocca** [comment] 2021-09-01 22:39
Duplicate of https://github.com/PyTorchLightning/pytorch-lightning/issues/8088

You can directly log the multidim tensors to your logger if it supports it, for example

```pyt
self.trainer.logger.experiment.log(...)
```

Closing, feel free to continue in that issue.

**Comment by FrancescoSaverioZuppichini** [comment] 2021-09-02 10:23
Hi @carmocca , thank you! In the linked issue I think nobody is talking about reduction of >1D tensors. For example, in your code snippet, there is no reduction happening.

So, how lighting will reduce a 2D tensor and how can I correctly log it? The doc is not helping here, or at leas I wasn't able to find anything

Thank you

**Comment by FrancescoSaverioZuppichini** [comment] 2021-09-30 13:58
I would like to raise this again, this issue is not solved and should be correctly addressed. Thank you

**Comment by carmocca** [comment] 2021-09-30 15:20
Do you mind sharing a snippet of what you are trying to do and what do you expect to happen?

If I understand your ask, you want to reduce it but keep it 2D, correct?

**Closed** 2021-12-27 22:03 UTC
Labels: feature, won't fix, logging
