### ISSUE TITLE
Support multiple checkpointing schemes

### ISSUE THREAD

**Issue by edenlightning** [PyTorchLightning/pytorch-lightning#3227] opened 2020-08-27 17:36 UTC
Give a list of checkpoint callbacks, as I want to use multiple checkpointing schemes (e.g. save best for different metrics) or save best k1 checkpoints but also save every k2 epochs

**Comment by carmocca** [comment] 2020-08-27 18:02
Duplicate of #2908

**Closed** 2020-10-28 22:27 UTC
Labels: duplicate, enhancement, help wanted, won't fix
