### ISSUE TITLE
How to add FGM. In lighting I know how to add PGD against disturbance in torch module, but I don't know where to add FGM under lighting attack()

### ISSUE THREAD

**Issue by Hou-jing** [PyTorchLightning/pytorch-lightning#12681] opened 2022-04-10 01:50 UTC
![image](https://user-images.githubusercontent.com/75936962/162597762-8aca0ff0-be12-49b7-8226-391f1368f5d9.png)

**Comment by akihironitta** [comment] 2022-04-10 04:01
Duplicate of #12680. Closing this.

**Closed by akihironitta** 2022-04-10 04:01 UTC
Labels: duplicate
