### ISSUE TITLE
make DataModule compatible with Python dataclass

### ISSUE THREAD

**Issue by awaelchli** [PyTorchLightning/pytorch-lightning#8272] opened 2021-07-04 10:21 UTC
## 🚀 Feature

Support the following:

```python
@dataclass
class MyDataModule(LightningDataModule):
    pass
```

### Motivation

To reduce boilerplate code is at the core of philosophy in Lightning. It should be compatible with dataclasses.

### Code sample

Here is an example. It currently does not work as we have some internal attributes that don't play well with the dataclass.

```python

import os
from dataclasses import dataclass

import torch
from torch.utils.data import DataLoader, Dataset

from pytorch_lightning import LightningModule, Trainer, LightningDataModule


class RandomDataset(Dataset):

    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


@dataclass
class BoringDataModule(LightningDataModule):

    batch_size: int = 2

    def train_dataloader(self):
        return DataLoader(RandomDataset(32, 64), batch_size=self.batch_size)


class BoringModel(LightningModule):

    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return {"loss": loss}

    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)


def run():
    model = BoringModel()
    trainer = Trainer(
        default_root_dir=os.getcwd(),
        limit_train_batches=1,
        limit_val_batches=1,
        num_sanity_val_steps=0,
        max_epochs=1,
        weights_summary=None,
    )
    trainer.fit(model, datamodule=BoringDataModule())


if __name__ == '__main__':
    run()

```

### Alternatives

#3792 introduces `save_hyperparameters()` for the datamodule. However, I believe the dataclass approach here is not in conflict with that because both could be useful at the same time.

**Comment by QueshAnmak** [comment] 2021-07-04 18:43
Hi, I would like to work on this issue, could you please assign it to me?

**Comment by awaelchli** [comment] 2021-07-04 19:08
Hey! Yes, you can take it if you want. I haven't really had the time to look why it is not working. I don't know how difficult it would be. 
Give it a try. We appreciate the help!

**Comment by QueshAnmak** [comment] 2021-07-04 19:37
Hey, Is there any slack or discord server I could join to ask my queries?

**Comment by awaelchli** [comment] 2021-07-04 19:38
Yes, feel free to join the PyTorch Lightning slack: https://join.slack.com/t/pytorch-lightning/shared_invite/zt-pw5v393p-qRaDgEk24~EjiZNBpSQFgQ

**Comment by QueshAnmak** [comment] 2021-07-09 21:27
![Screenshot 2021-07-10 025106](https://user-images.githubusercontent.com/78043832/125137142-ba462500-e129-11eb-821b-7f7df27f4156.jpg)
I set init to False (which by default is set to True). This seems to fix the issue. I think the "@property" decorator on the attributes might be the cause of the issue.
![Screenshot 2021-07-10 025441](https://user-images.githubusercontent.com/78043832/125137514-74d62780-e12a-11eb-9d46-6a794b58bac4.jpg)
How should I proceed?

**Comment by awaelchli** [comment] 2021-07-14 23:21
Oh yes, but actually we want dataclass to generate an init for us. Otherwise we don't get any great value of a dataclass here.
But actually, all we have to do is this:

```python
    def __post_init__(self):
        super().__init__()
```

Because the init generated by dataclass does not call `super()`, and that's required by the datamodule.

**Closed** 2021-09-02 22:43 UTC
Labels: enhancement, help wanted, good first issue, data / DataModule

**Comment by adosar** [comment] 2025-01-09 19:21
@awaelchli  For a custom datamodule should `self.save_hyperparmeters` called under `__post_init__`? That is:
```python
@dataclass
class MyDataModule(LightningDataModule):
    x: int = 32
    ...
    
    def __post_init_(self):
          super().__init__()
          self.save_hyperparameters()
```
