### ISSUE TITLE
MultiGPU Training. Logging problem

### ISSUE THREAD

**Issue by toshiks** [PyTorchLightning/pytorch-lightning#1332] opened 2020-04-01 21:22 UTC
## 🐛 Bug

When we try logging to the tensorboard loss during last step of epoch with GPU number more than one, we can get exception.

### To Reproduce

Start training any model on any dataset with gpu amount over than one, but last batch should contains objects only for the part of GPUs.

I have next error:
`ValueError: only one element tensors can be converted to Python scalars`

### Expected behavior

Success logging to tensorboard. 

### Environment

OS: Ubuntu
pytorch-lightning==0.7.1

### Additional context

I suppose problem in the method (trainer/logging.py): 
```python
def reduce_distributed_output(self, output, num_gpus)
```

```python
# reduce only metrics that have the same number of gpus
elif output[k].size(0) == num_gpus:
    reduced = torch.mean(output[k])
    output[k] = reduced
```

If we have a last not full batch, we should get mean, isn't it?

**Comment by Borda** [comment] 2020-04-16 23:17
seems to be the same as #1218 so I am closing this one in its favour...
@toshiks may you give a minimal example to reproduce?

**Closed by Borda** 2020-04-16 23:17 UTC
Labels: bug, help wanted
