### ISSUE TITLE
Error in training with ddp backend and checkpoint_callback

### ISSUE THREAD

**Issue by mmiakashs** [PyTorchLightning/pytorch-lightning#1578] opened 2020-04-23 18:24 UTC
## 🐛 Bug

I am getting the following error when I am using checkpoint_callback or early_stop_callback  in ``ddp`` mode with multi-GPUs. However, If I remove checkpoint_callback and early_stop_callback, then my code executes without any error.

#### Code sample
Here is a sample google colab notebook (Please note that this colab error is not exactly the same actual error): [Colab](https://colab.research.google.com/drive/110kEtr1BjhPtTzQ7r8qOXbnb8VOwQQ6y)

```
Traceback (most recent call last):
  File "../model.py", line 489, in <module>
    main(args=args)
  File "../model.py", line 357, in main
    trainer.fit(model)
  File "/home/machine/.local/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 738, in fit
    mp.spawn(self.ddp_train, nprocs=self.num_processes, args=(model,))
  File "/home/machine/.local/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/machine/.local/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 149, in start_processes
    process.start()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/usr/lib/python3.7/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'torch._C._VariableFunctions'>: it's not the same object as torch._C._VariableFunctions
```

### Environment

 - PyTorch Version : 1.5
  PyTorch Lightning Version : 0.7.3rc3
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Python version: 3.7.5
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: RTX 6000

**Comment by isvoboda** [comment] 2020-04-27 12:12
I have just update from
- PyTorch **1.4** & Pytorch Lightning **0.7.3**

where `"ddp"` & `ModelCheckpoint` worked just fine to
- PyTorch **1.5** & Pytorch Lightning **0.7.4**

where I hit the same error.

**Comment by isvoboda** [comment] 2020-04-27 23:59
I have updated to PyTorch **1.5** & Pytorch Lightning **0.7.5** and `"ddp"` in combination with `ModelCheckpoint` seems to work. Possibly a duplicate of #1628.

**Comment by williamFalcon** [comment] 2020-04-28 00:06
resolved in 0.7.5

**Closed by williamFalcon** 2020-04-28 00:06 UTC
Labels: bug, help wanted

**Comment by mmiakashs** [comment] 2020-04-28 03:41
Thanks @williamFalcon for resolving the issue. But, still I am getting the same error in 0.7.5, you can this [colab notebook](https://colab.research.google.com/drive/110kEtr1BjhPtTzQ7r8qOXbnb8VOwQQ6y) to reproduce. Please let me know, whether I am missing anything. Thanks.

**Comment by Borda** [comment] 2020-04-29 16:08
@mmiakashs mind open a new issue?
