### ISSUE TITLE
Behaviour when limit_train_batches is float is inconsistent

### ISSUE THREAD

**Issue by blisc** [PyTorchLightning/pytorch-lightning#5029] opened 2020-12-08 20:22 UTC
## 🐛 Bug

When passing limit_train_batches as a float to the trainer, the total number of steps during training is inconsistent and is dependent on accumulate_grad_batches, and independent of drop_last. Please see the tests in the notebooks for more examples.

### To Reproduce
See notebook.
https://colab.research.google.com/drive/1RmIwW97NM0bOmF2GUUilPyzCQ2MYYG1g?usp=sharing

### Expected behavior

I don't have an expected behaviour other than to request that the total number of steps remain consistent. Either always drop an incomplete batch, or don't.

### Environment
* CUDA:
	- GPU:
		- Tesla T4
	- available:         True
	- version:           10.1
* Packages:
	- numpy:             1.18.5
	- pyTorch_debug:     True
	- pyTorch_version:   1.7.0+cu101
	- pytorch-lightning: 1.0.8
	- tqdm:              4.41.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.6.9
	- version:           #1 SMP Thu Jul 23 08:00:38 PDT 2020

**Comment by gan3sh500** [comment] 2020-12-10 05:54
Can I take this up?

**Comment by Borda** [comment] 2020-12-11 08:04
@gan3sh500 great, go ahead! 🎉

**Comment by gan3sh500** [comment] 2020-12-14 14:46
@Borda The issue seems to be that `num_train_batches` and `train_loop.should_skip_training` are unaware on DataLoader's `drop_last`. It can be fixed with some messy if else like below and checking `DataLoader`'s `drop_last` in `should_skip_training` similarly. But the approach feels very hacky. Let me know if you have a more elegant solution. Otherwise I can submit these kind of changes as a PR. 
![image](https://user-images.githubusercontent.com/18054340/102095121-276e3200-3e49-11eb-85d4-aea4e8145e9c.png)
above picture from `data_loading` L160 approx.

**Comment by gan3sh500** [comment] 2020-12-18 18:38
@Borda I've submitted a PR. I've checked with the notebook and the behaviour is changed but please review and let me know if that is the expected behaviour.

**Closed** 2021-02-03 07:24 UTC
Labels: Priority P1, bug / fix, help wanted, with code
