### ISSUE TITLE
Mixing hparams and arguments in LightningModule.__init__() crashes load_from_checkpoint()

### ISSUE THREAD

**Issue by siddk** [PyTorchLightning/pytorch-lightning#1468] opened 2020-04-12 22:32 UTC
## 🐛 Bug

Right now, if you initialize a Lightning Module with a mixture of a Namespace (hparams) as well as additional arguments (say to a Dataset), load_from_checkpoint can't recover.

### To Reproduce

Create a LightningModule as follows:

```python
class Model(pl.LightningModule):
      def __init__(self, hparams, train_dataset, val_dataset):
              self.hparams = hparams
              self.train_dset, self.val_dset = train_dataset, val_dataset
              ...
```

Run training, then try to restore from checkpoint, via:

```python
nn = Model.restore_from_checkpoint(<PATH>, train_dataset=None, val_dataset=None)
```

### Expected behavior

Ideally, you'd just be able to pass in the additional arguments (as above) and everything would work.

**Comment by WSzP** [comment] 2020-04-13 09:08
Very interesting issue. I think the whole restore_from_checkpoint could use a bit better documentation. I think you are trying to use checkpoints for something that was not the intention. 
I think what you want is run the model without training (this is why the train and val datasets are empty). In this case I would try falling back to plain torch solution, such as:
```
torch.save(nn.state_dict(), SAVE_PATH)
loaded_model = nn(hparams)
loaded_model.load_state_dict(torch.load(SAVE_PATH))
loaded_model.eval()
print("Model's state_dict:")
for param_tensor in loaded_model.state_dict():
print(param_tensor, "\t", loaded_model.state_dict()[param_tensor].size())
```

**Comment by siddk** [comment] 2020-04-13 15:59
That makes sense for this usecase --> but say I want to pause/resume training later on (the intended usecase of restore from checkpoint). Here, I really want to be able to leverage the fact that Lightning remembers my hyperparameters, and I want to be able to just pass in the additional arguments (like the datasets I've constructed).

**Comment by williamFalcon** [comment] 2020-04-13 16:04
This is fixed in 0.7.3

https://pytorch-lightning.readthedocs.io/en/0.7.3/lightning-module.html#lightningmodule-class

```python
# or load passing whatever args the model takes to load
MyLightningModule.load_from_checkpoint(
    'path/to/checkpoint.ckpt',
    learning_rate=0.1,
    layers=2,
    pretrained_model=some_model
)
```

**Comment by siddk** [comment] 2020-04-13 16:32
This doesn't seem to be true if I explicitly pass a `hparams` argument... only if I break out each of the arguments and pass them to the __init__() method.

**Comment by williamFalcon** [comment] 2020-04-13 16:35
share a colab? this should be true on 0.7.3. 

For now you can do Trainer(PATH, **hparams)

**Comment by siddk** [comment] 2020-04-13 20:19
https://colab.research.google.com/drive/1WmuZfOQxyi4nF_YvjFcJrcpVhNvuCXST

**Comment by HenryJia** [comment] 2020-04-16 04:46
I can reproduce this with that script on e3001a0

Gives me the following traceback
```
Traceback (most recent call last):
  File "pl_loadfromcheckpoint.py", line 40, in <module>
    new_model = Model.load_from_checkpoint('save.ckpt', c='this is', d='a test')
  File "/home/henry/Coding/pytorch-lightning/pytorch_lightning/core/lightning.py", line 1509, in load_from_checkpoint
    model = cls._load_model_state(checkpoint, *args, **kwargs)
  File "/home/henry/Coding/pytorch-lightning/pytorch_lightning/core/lightning.py", line 1541, in _load_model_state
    model = cls(*model_args)
TypeError: __init__() missing 2 required positional arguments: 'c' and 'd'
```

It seems to be due to this if statement here which stops it taking into account anymore arguments if there's a hparam in the checkpoint
https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/core/lightning.py#L1540

**Closed** 2020-04-19 11:03 UTC
Labels: bug, help wanted
