### ISSUE TITLE
Support calling fit and test scripts using "python -m" module syntax with DDP

### ISSUE THREAD

**Issue by nisheethlahoti** [PyTorchLightning/pytorch-lightning#8072] opened 2021-06-22 04:10 UTC
## 🚀 Feature
Support calling fit and test scripts using "python -m" module syntax with DDP

### Motivation
A python script `c.py` located in the directory `a/b` can be called either as `python a/b/c.py` or as `python -m a.b.c`. The latter method has a few advantages:
 1. It supports relative imports internally
 2. The script can be called if it's present in PYTHONPATH, not just in the current working directory. (This is useful when the package has been installed pip etc.)
 3. Things mentioned in https://www.python.org/dev/peps/pep-0338/

Right now, DDP assumes the script has been called using the first method, and fails with obscure errors if it is called using the second.

### Pitch
Support both ways of calling scripts with DDP.

### Alternatives
None that I can think of.

**Comment by awaelchli** [comment] 2021-06-22 11:02
duplicate of  #3689 ?

**Closed** 2021-06-23 02:42 UTC
Labels: DDP, duplicate, enhancement, help wanted
