### ISSUE TITLE
Accuracy calculation issue related to "+="

### ISSUE THREAD

**Issue by vincentzlt** [PyTorchLightning/pytorch-lightning#4713] opened 2020-11-17 14:19 UTC
https://github.com/PyTorchLightning/pytorch-lightning/blob/c208ac68c88a23977ae3d156dabb1440a9f1c9f3/pytorch_lightning/metrics/classification/accuracy.py#L98

I encountered `RuntimeError: Trying to pass too many CPU scalars to CUDA kernel!` error when using the accuracy metric.

This might be related to:
https://discuss.pytorch.org/t/trying-to-pass-too-many-cpu-scalars-to-cuda-kernel/87757/5
https://github.com/pytorch/pytorch/issues/40986

**Comment by SkafteNicki** [comment] 2020-11-17 14:58
@vincentzlt Are you using the metric inside a lightning module or just as standalone?
Code example would be nice :]

**Comment by vincentzlt** [comment] 2020-11-18 07:19
Sorry for not putting code examples

```python
import pytorch_lightning as pl

class Model(pl.LightningModule):
    def __init__(self,...):
        self.acc=pl.metrics.Accuracy(threshold=0, compute_on_step=False)
        ...

    def training_step(self, batch, batch_idx):
        pred, ground_truth=...
        self.acc(pred, ground_truth)
        if batch_idx % 10 == 0:
            self.log('acc', self.acc.compute())
```

Actually, this is not easy to reproduce. when I have a small batch size, I do not have this error. When I have a large batch size, I got this error.

I think the solution is to just change the use of `a += b` to `a = a + b` in the code according to the discussions I posted.

**Comment by SkafteNicki** [comment] 2020-11-18 10:21
Can you in anyway provide a notebook where I can reproduce this, because trying out your code snippet with various batch sizes and both on cpu and gpu, I have not been able to reproduce.

It is clear to me that this error happens due to the metric state and the input tensors not being on the same device. However, when used inside a lightning module both should automatically move to the correct/same device. That´s why I would like to debug more before we change `a+=b` to `a=a+b`.

**Comment by vincentzlt** [comment] 2020-11-20 05:08
Sorry I can not give you the entire code.

I am training a transformer model and have 12500 tokens in a batch, and accumulate 2 batches before gradient descent.

Here is some more detailed error message:

```bash
Traceback (most recent call last):
  File "mt.py", line 243, in <module>
    trainer.fit(mt, dataset)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 446, in fit
    results = self.accelerator_backend.train()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/accelerators/gpu_accelerator.py", line 64, in train
    results = self.train_or_test()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 66, in train_or_test
    results = self.trainer.train()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 495, in train
    self.train_loop.run_training_epoch()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 561, in run_training_epoch
    batch_output = self.run_training_batch(batch, batch_idx, dataloader_idx)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 700, in run_training_batch
    self.training_step_and_backward(split_batch, batch_idx, opt_idx, optimizer, self.trainer.hiddens)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 813, in training_step_and_backward
    result = self.training_step(split_batch, batch_idx, opt_idx, hiddens)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 320, in training_step
    training_step_output = self.trainer.accelerator_backend.training_step(args)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/accelerators/gpu_accelerator.py", line 72, in training_step
    output = self.__training_step(args)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/accelerators/gpu_accelerator.py", line 80, in __training_step
    output = self.trainer.model.training_step(*args)
  File "mt.py", line 90, in training_step
    self.train_acc(y[mask], y_true[mask])
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/metrics/metric.py", line 156, in forward
    self.update(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/metrics/metric.py", line 202, in wrapped_func
    return update(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/metrics/classification/accuracy.py", line 113, in update
    self.correct += torch.sum(preds == target)
RuntimeError: Trying to pass too many CPU scalars to CUDA kernel!
```

I guess the problem is not whether the `pred` or `ground_truth` is properly moved to the correct device. it looks like the `self.correct` in the Accuracy object has not been properly handled. When I use `.cpu()` at the `pred` and `ground_truth` the error is gone.

```python
self.acc(pred.cpu(), ground_truth.cpu())
```

**Comment by SkafteNicki** [comment] 2020-11-20 07:55
Fair enough, could you try printing the device of the different tensors and post the result:
```
print(self.acc.correct.device)
print(pred.device)
print(ground_truth.device)
```
Also are you running single gpu or multi?

**Comment by vincentzlt** [comment] 2020-11-20 08:09
```
cuda:0
cuda:0
cuda:0
Epoch 0:   0% 2/40742 [00:05<29:15:34,  2.59s/it, loss=9.164, v_num=12, train/lr=1.75e-7, train/global_step=0, train/batch_acc=0]Traceback (most recent call last):
  File "mt.py", line 246, in <module>
    trainer.fit(mt, dataset)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 446, in fit
    results = self.accelerator_backend.train()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/accelerators/gpu_accelerator.py", line 64, in train
    results = self.train_or_test()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 66, in train_or_test
    results = self.trainer.train()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 495, in train
    self.train_loop.run_training_epoch()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 561, in run_training_epoch
    batch_output = self.run_training_batch(batch, batch_idx, dataloader_idx)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 700, in run_training_batch
    self.training_step_and_backward(split_batch, batch_idx, opt_idx, optimizer, self.trainer.hiddens)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 813, in training_step_and_backward
    result = self.training_step(split_batch, batch_idx, opt_idx, hiddens)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 320, in training_step
    training_step_output = self.trainer.accelerator_backend.training_step(args)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/accelerators/gpu_accelerator.py", line 72, in training_step
    output = self.__training_step(args)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/accelerators/gpu_accelerator.py", line 80, in __training_step
    output = self.trainer.model.training_step(*args)
  File "mt.py", line 90, in training_step
    self.train_acc(y[mask], y_true[mask])
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/metrics/metric.py", line 156, in forward
    self.update(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/metrics/metric.py", line 202, in wrapped_func
    return update(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/metrics/classification/accuracy.py", line 113, in update
    self.correct += torch.sum(preds == target)
RuntimeError: Trying to pass too many CPU scalars to CUDA kernel!
```

**Comment by SkafteNicki** [comment] 2020-11-20 08:18
Then I don't understand at all, why you are seeing that error, clearly all tensors involved are on GPU, thus I don't understand why it is complaining about CPU.

**Comment by SkafteNicki** [comment] 2020-11-20 14:12
Which pytorch version are you running?

**Comment by vincentzlt** [comment] 2020-11-21 01:56
pytorch 1.7

Yeah, it is quite strange. For now I just use 

> ```python
> self.acc(pred.cpu(), ground_truth.cpu())
> ```

**Comment by SkafteNicki** [comment] 2020-11-24 15:53
@vincentzlt I am closing this for now as I have been unable to reproduce the error. Feel free to reopen if you can provide some code that reproduces the error.

**Closed by SkafteNicki** 2020-11-24 15:53 UTC
Labels: Metrics

**Comment by ant0nsc** [comment] 2020-12-16 23:50
@SkafteNicki , I've been running into the same problem. Here's my 4 line repro (pytorch 1.6.0, pytorch-lightning 1.0.6)

```
metric = Accuracy()
pred=torch.tensor(0.8, device="cuda:0")
label=torch.tensor(1, device="cuda:0")
metric(pred,label)

Out: (truncated):
Traceback (most recent call last):
  File "envs/InnerEye/lib/python3.7/site-packages/pytorch_lightning/metrics/metric.py", line 155, in forward
    self.update(*args, **kwargs)
  File "envs/InnerEye/lib/python3.7/site-packages/pytorch_lightning/metrics/metric.py", line 201, in wrapped_func
    return update(*args, **kwargs)
  File "envs/InnerEye/lib/python3.7/site-packages/pytorch_lightning/metrics/classification/accuracy.py", line 113, in update
    self.correct += torch.sum(preds == target)
RuntimeError: Trying to pass too many CPU scalars to CUDA kernel!
```
The workaround suggested on https://discuss.pytorch.org/t/trying-to-pass-too-many-cpu-scalars-to-cuda-kernel/87757/4 is to re-write the expression as `self.correct = self.correct + torch.sum(preds==target)`. Happy to PR that.

**Comment by SkafteNicki** [comment] 2020-12-17 12:29
Hi @ant0nsc, so `Metric`s are similar to `nn.Module`s in the sense that their metric state needs to be moved to the correct device (similar to the parameters/buffers of `nn.Module`). Therefore, simply changing your code to:
``` python
metric = Accuracy().cuda()
pred=torch.tensor(0.8, device="cuda:0")
label=torch.tensor(1, device="cuda:0")
metric(pred,label)
```
should get it working. We are in the process of determining if we should auto move the metric states to the same device as the input (not just accuracy, but all metrics), in this issue https://github.com/PyTorchLightning/pytorch-lightning/issues/4909

**Comment by ant0nsc** [comment] 2020-12-17 12:45
I get that - but it is somewhat contradictory to the rest of the PL philosophy, where as a user I'm not meant to be moving objects around, but leave that to PL. And if it weren't for that bug with in-place operations in PyTorch, all would work well.
Anyway, there's an easy workaround, and good to hear that it's on your radar with #4909

**Comment by SkafteNicki** [comment] 2020-12-17 12:49
So if the `Metric` is defined in a `LightningModule` then it will be device agnostic i.e. if you set `Trainer(gpus=1)` then it will automatically be moved to the gpu when your `LightningModule` is moved to the gpu. I have only seen this problem when the metric is used as standalone operation.

**Comment by ant0nsc** [comment] 2020-12-17 15:07
@SkafteNicki , thanks, that has given me an idea. My metric computers are stored in a more complex data structure inside my `LightningModule` (a `Dict[str,Metric]`) and that is probably not recognized as something that can be moved to the GPU.
@vincentzlt FYI

**Comment by SkafteNicki** [comment] 2020-12-17 21:24
@ant0nsc please see this comment
https://github.com/PyTorchLightning/pytorch-lightning/issues/4909#issuecomment-736821581
It is the same problem you are facing, namely that `nn.Module` or `Metric` objects are not proper recognized inside a `dict` (or `list`)
