### ISSUE TITLE
Calling module.log(...) within a callback fails

### ISSUE THREAD

**Issue by ananthsub** [PyTorchLightning/pytorch-lightning#3813] opened 2020-10-03 05:59 UTC
## 🐛 Bug

Calling pl_module.log(...) within a Callback fails, even though this is recommended by the documentation here: https://pytorch-lightning.readthedocs.io/en/latest/loggers.html#logging-from-a-callback

### Error

```
  File "my_callback_file.py", line XX, in on_validation_epoch_end
    pl_module.log_dict(my_metrics_dict)
  File "/home/local/USHERBROOKE/pain5474/opt/miniconda3/envs/cav/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py", line 287, in log_dict
    self.log(
  File "/home/local/USHERBROOKE/pain5474/opt/miniconda3/envs/cav/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py", line 233, in log
    self._results.log(
  File "/home/local/USHERBROOKE/pain5474/opt/miniconda3/envs/cav/lib/python3.8/site-packages/pytorch_lightning/core/step_result.py", line 171, in log
    self.__set_meta(
  File "/home/local/USHERBROOKE/pain5474/opt/miniconda3/envs/cav/lib/python3.8/site-packages/pytorch_lightning/core/step_result.py", line 217, in __set_meta
    _internal = self['meta']['_internal']
KeyError: '_internal'
python-BaseException
```
cc @nathanpainchaud 

This is happening on master

### Expected behavior

We can log from callbacks using the lightning module

### Environment

Happening on PyTorch Lightning master

**Comment by SkafteNicki** [comment] 2020-10-07 09:14
@ananthsub I just tried on master and cannot reproduce (I think it was solved yesterday, as I could reproduce 2 days ago).

**Comment by nathanpainchaud** [comment] 2020-10-07 16:12
@SkafteNicki The issue was created by @ananthsub based on a question/issue I initially raised in the slack. I'll try to see if the bug is now resolved on master for me (it was still present as of yesterday afternoon) and I'll update you here as soon as I can.

**Comment by tchaton** [comment] 2020-10-14 11:48
Hey @nathanpainchaud,

Did you manage to `reliably reproduce this behaviour`? And if yes, could share the draft PR associated with this issue ?
I will try to try it out too.

Best regards,
Thomas Chaton.

**Comment by nathanpainchaud** [comment] 2020-10-14 13:37
Hey @tchaton,

Thanks for the follow up! I opened the [draft PR](https://github.com/PyTorchLightning/pytorch-lightning/pull/4144) where I added a test that reproduces the behavior I'm getting.

If I can help in any other way to get this sorted, just let me know!

**Comment by nathanpainchaud** [comment] 2020-10-30 19:47
@tchaton Any updates on whether this is a feature that's planned to be supported, or on the contrary it's been abandoned? I'm only asking this question because the issue has been labelled priority for a while, but every PR referring to it have been closed without getting merged :laughing:

**Comment by williamFalcon** [comment] 2020-10-30 21:49
Yes! thats been worked on these weeks. Starting to be merged now (https://github.com/PyTorchLightning/pytorch-lightning/pull/4439)

**Closed** 2020-11-11 17:05 UTC
Labels: bug / fix, enhancement

**Comment by aligholami** [comment] 2021-02-20 03:53
I still have problems logging my validation metrics using pl_module.log() in the on_validation_end() hook. Any thoughts?
