### ISSUE TITLE
Parser overwritten when using add_argparse_args

### ISSUE THREAD

**Issue by mpeven** [PyTorchLightning/pytorch-lightning#7216] opened 2021-04-26 15:22 UTC
## 🐛 Bug

Using the `add_argparse_args` functions doesn't play nice with the `HyperOptArgumentParser` from TestTube.

The arguments from HyperOptArgumentParser are overwritten, which causes it to fail with the error message:
```AttributeError: 'Namespace' object has no attribute 'hpc_exp_number'```

## Please reproduce using the BoringModel

https://colab.research.google.com/drive/1CEtLb_LCvTnWNVvvCQrRpKYzZ4-QYB_S?usp=sharing

### Additional context

I'm not sure what the fix is here - the only way I was able to get around this was by not using `add_argparse_args` and putting them in manually, but it seems like there should be a better way.

**Comment by awaelchli** [comment] 2021-04-27 08:40
This works well for me. I don't understand what you are experiencing. Can you have a look at this minimal example?

```python
from pytorch_lightning import Trainer
from test_tube import HyperOptArgumentParser

parser = HyperOptArgumentParser(strategy='grid_search', add_help=False)
parser = Trainer.add_argparse_args(parser)
args = parser.parse_args(["--hpc_exp_number", "2"])
print(args.hpc_exp_number)  # output 2

args = parser.parse_args()
print(args.hpc_exp_number)  # output None (default)


```

**Comment by mpeven** [comment] 2021-04-28 17:05
@awaelchli I ran your minimal example and got the output `error: unrecognized arguments: --hpc_exp_number 2`

Here's a colab notebook showing this:
https://colab.research.google.com/drive/1RxTpdUXSUdPyHzlR343_GL9Dvwl6cN8X?usp=sharing

**Comment by awaelchli** [comment] 2021-04-30 03:23
I can confirm the problem is in 1.2.10 and it's fixed on master. You can see it if you install the pre-release. 
`pip install --pre pytorch-lightning`

**Closed by awaelchli** 2021-04-30 03:23 UTC
Labels: bug / fix, help wanted
