### ISSUE TITLE
06-mnist-tpu-training.ipynb - Google Colab error 

### ISSUE THREAD

**Issue by quantum-fusion** [PyTorchLightning/pytorch-lightning#6393] opened 2021-03-07 16:13 UTC
<img width="1254" alt="Screen Shot 2021-03-07 at 11 12 36 AM" src="https://user-images.githubusercontent.com/10088099/110246568-17d92380-7f36-11eb-8771-9d30adc64656.png">
## 🐛 Bug

The bug is that the package will not install.

**Comment by awaelchli** [comment] 2021-03-07 20:40
Duplicate of #6382
But thanks for reporting it. 
Will post updates in the other issue.

**Comment by awaelchli** [comment] 2021-03-07 20:55
Found it. You need to use this 
! pip install https://storage.googleapis.com/tpu-pytorch/wheels/torch_xla-1.7-cp37-cp37m-linux_x86_64.whl

(replaced 36 with 37)

**Comment by quantum-fusion** [comment] 2021-03-08 13:08
@awaelchli See errors , 06-mnist-tpu-training.ipynb still broken.

<img width="1215" alt="Screen Shot 2021-03-08 at 8 07 47 AM" src="https://user-images.githubusercontent.com/10088099/110325500-6bef1100-7fe5-11eb-944f-89e500327222.png">

**Comment by awaelchli** [comment] 2021-03-09 03:22
This is not on our side. I had the same problem, and this simple code will reproduce that:

```python
from torchvision.datasets import MNIST
m = MNIST("./", train=True, download=True)
```

Solution is to upgrade torchvision version

`pip install --upgrade torchvision`

**Comment by quantum-fusion** [comment] 2021-03-10 12:55
@awaelchli I am a newbie with this, and I would like to get a complete running example, because I learn by example, however this example doesn't work as advertised.  I might like to recommend that you get rid of the bugs, and update the notebook that you have published.  The workarounds that you suggested, I tried, but they failed.  Please advise, because this trial and error approach isn't working for me.

<img width="1368" alt="Screen Shot 2021-03-10 at 7 53 34 AM" src="https://user-images.githubusercontent.com/10088099/110632619-d636bb80-8175-11eb-954b-2f3521f55620.png">

**Comment by awaelchli** [comment] 2021-03-10 13:40
> I might like to recommend that you get rid of the bugs, and update the notebook that you have published

This is not my notebook, I am not the author. 

I can clearly see in your screenshot the error message says Syntax error, invalid character. You typed the wrong quotation marks.
In general, it is always possible that a dependency updates and changes something that would break the notebook. I may find some time later today to go through all notebooks and check if they run as expected.

**Comment by quantum-fusion** [comment] 2021-03-10 13:42
@awaelchli Did you mean to say '.' instead of "." ? 

m = MNIST('./', train=True, download=True) , instead of m = MNIST("./", train=True, download=True)

**Comment by awaelchli** [comment] 2021-03-10 13:46
No, you have the wrong symbol somehow, I don't know why. You have something like this: “ 
Where does that come from? Is this the first time you run a Python code? Because this is very common to define strings.

**Comment by quantum-fusion** [comment] 2021-03-10 13:48
@awaelchli I cut and paste , so I don't know if the paste operation caused the wrong character, I cut from your solution, and when I paste, I don't know where that character came from.  I will try again.

**Closed** 2021-03-12 02:04 UTC
Labels: TPU, bug / fix, duplicate, help wanted
