### ISSUE TITLE
CLI subcommand error

### ISSUE THREAD

**Issue by messier202** [PyTorchLightning/pytorch-lightning#9663] opened 2021-09-23 05:49 UTC
After reading [CLI DOC](https://pytorch-lightning.readthedocs.io/en/latest/common/lightning_cli.html)
when I run `python trainer.py --help` , error occurs:
```
usage: trainer.py [-h] [--config CONFIG] [--print_config [={comments,skip_null}+]] {fit,validate,test,predict,tune} ...
trainer.py: error: 'Sub-command "subcommand" is required but not given or its value is None.'
```
program crashed here
https://github.com/PyTorchLightning/pytorch-lightning/blob/4bebf82f271fb577ed41831403551f0bff97651b/pytorch_lightning/utilities/cli.py#L466

**Comment by messier202** [comment] 2021-09-23 07:05
My codes:
```
cli = MyLightningCLI(LightningModule, LightningDataModule, subclass_mode_model=True,
                     subclass_mode_data=True, parser_kwargs={"default_config_files": ["train.yml"]})
```

**Comment by carmocca** [comment] 2021-09-23 15:25
I cannot reproduce the issue. Can you report:

- 1. Your Lightning version
- 2. Your jsonargparse version
- 3. A fully reproducible snippet, including your config.

Using your code:

```python
$ python trainer.py --help
usage: trainer.py [-h] [--config CONFIG] [--print_config [={comments,skip_null}+]]
             {fit,validate,test,predict,tune} ...

pytorch-lightning trainer command line tool

default config file locations:
  ['train.yml'], Note: no existing default config file found.

optional arguments:
  -h, --help            Show this help message and exit.
  --config CONFIG       Path to a configuration file in json or yaml format.
  --print_config [={comments,skip_null}+]
                        Print configuration and exit.

subcommands:
  For more details of each subcommand add it as argument followed by --help.

  {fit,validate,test,predict,tune}
    fit                 Runs the full optimization routine.
    validate            Perform one evaluation epoch over the validation set.
    test                Perform one evaluation epoch over the test set.
    predict             Run inference on your data.
    tune                Runs routines to tune hyperparameters before training.
```

**Comment by messier202** [comment] 2021-09-24 02:20
lightning version: 20210923
jsonargparse version: 3.19.2
to reproduce:
https://github.com/messier202/lightning_cli

**Comment by carmocca** [comment] 2021-09-29 00:13
Thanks, @messier202! The repo was very helpful.

The error message is not the best, but you are not passing the correct `parser_kwargs` format. It should be

```diff
-parser_kwargs={"default_config_files": ["train.yml"]})
+parser_kwargs={"fit": {"default_config_files": ["train.yml"]}})
```

(assuming you want to use those settings for `trainer.fit`)

This is explained at the bottom of [this section](https://pytorch-lightning.readthedocs.io/en/latest/common/lightning_cli.html#use-of-command-line-arguments) (Ctrl+F `parser_kwargs` if you can't find it)

You'll also need to fix the classpaths in your configuration file:

```yaml
model:
  class_path: lightning_cli.model.LitModel
data:
  class_path: lightning_cli.data.MNISTDataModule
```

Hope that helps! Closing as this is working correctly but feel free to ask any further questions.

**Closed by carmocca** 2021-09-29 00:13 UTC
Labels: bug / fix, CLI

**Comment by amitport** [comment] 2025-08-25 16:27
@carmocca actually current docs, specifically seem to mention you can set global default
https://lightning.ai/docs/pytorch/stable/cli/lightning_cli_advanced_2.html
