### ISSUE TITLE
Disable automatic SLURM Detection

### ISSUE THREAD

**Issue by amogkam** [PyTorchLightning/pytorch-lightning#6389] opened 2021-03-07 06:56 UTC
## 🚀 Feature

I want to run my PTL script on a SLURM cluster, but I don't want to use the built in SlurmConnector since I am using Ray to handle distributed training. When using Ray and the SlurmConnector, it results in this error: https://github.com/PyTorchLightning/pytorch-lightning/issues/3651. Is there a way I can disable automatic SLURM detection? Having an environment variable to disable this would really help. Thanks!

**Comment by import-antigravity** [comment] 2021-03-08 16:14
I think this is more of a bug/fix than an enhancement

**Comment by carmocca** [comment] 2021-03-15 19:29
Sort of a duplicate of https://github.com/PyTorchLightning/pytorch-lightning/issues/6204

**Comment by import-antigravity** [comment] 2021-03-15 19:32
> Sort of a duplicate of #6204

Does writing multiple checkpoints cause the `ValueError: signal only works in main thread`? Sorry I have only a passing familiarity with SLURM so I can't really speak intelligently about this.

**Comment by carmocca** [comment] 2021-03-15 20:07
I said sort of because the linked issue comments also ask for a mechanism to disable SLURM detection

**Comment by Queuecumber** [comment] 2021-03-22 19:43
I'm happy to implement that, although I've since come around on the automatic slurm detection (I think the right thing for me is to disable my other library's automatic detection). The simplest way forward is probably to add a `disable_hpc_detection` flag to the trainer which is false by default.

**Comment by import-antigravity** [comment] 2021-03-23 03:06
> The simplest way forward is probably to add a `disable_hpc_detection` flag to the trainer which is false by default.

That seems like the best course of action.

**Comment by import-antigravity** [comment] 2021-08-02 01:38
Could someone re-open this? This is still a problem

**Comment by import-antigravity** [comment] 2021-08-02 14:31
What was the original intent of the SLURM detection? Would it make sense to maybe add a `Trainer` flag to disable it?

**Comment by import-antigravity** [comment] 2021-08-02 23:18
> I'm happy to implement that, although I've since come around on the automatic slurm detection (I think the right thing for me is to disable my other library's automatic detection). The simplest way forward is probably to add a `disable_hpc_detection` flag to the trainer which is false by default.

I think this is a very reasonable fix

**Comment by import-antigravity** [comment] 2021-09-03 14:59
Does someone want to make a PR for this? I suppose I could

**Comment by tchaton** [comment] 2021-10-06 07:58
Hey @amogkam,

In PyTorch Lightning master, the SlurmConnector was refactored into a SignalConnector component.

As a temporary solution, you could patch its `register_signal_handlers` to prevent the signal to be registered.

Best,
T.C

**Comment by amogkam** [comment] 2021-11-11 17:51
@tchaton instead of having to patch it, is it possible to add a flag to disable it?

**Comment by amogkam** [comment] 2021-11-11 17:55
Also relevant: https://github.com/PyTorchLightning/pytorch-lightning/issues/9590

**Comment by ananthsub** [comment] 2021-11-17 05:33
We have some users facing issues with this as well.

Namely, these users use https://github.com/facebookincubator/submitit . There is contention across both SubmitIt and Lightning for resubmitting jobs to the scheduler.

My opinion is the Lightning library should not be in the business of requeuing jobs like this.
1. The support for doing this with SLURM is adhoc. It likely precedes tools like submitit being available back when Will was running jobs on the FAIR cluster. My guess is Lightning wouldn't have built resubmission in if SubmitIt already existed.
2. Lightning doesn't do this for any other clusters. Why is SLURM special cased? Is Lightning saying that it will natively support resubmission for every other scheduler users want to integrate with? That won't scale to the number of schedulers/resubmitting scenarios that can exist.
3. Lightning runs in the context of a larger user application. The resubmission should happen at the application-level, not within the library like this.

**Comment by carmocca** [comment] 2021-11-17 15:18
I think we should keep the feature, as it does seem to be used by the community (impression I've got from Slack questions and other issues).
We could recommend other tools but it looks cheap for us to remove everything and tell people to install another package if the functionality is already available.

However, I think there's value in revamping the SLURM mechanism so that it does not leak into other components and can be easily switched on/off.

This would be a similar idea to the addition of the `LightningCLI` (composable, separated into a utility) even though we already had `argparse`-enabled components (`from_argparse_args`) which do leak into your Trainer/LightningModule/DataModule code.

**Comment by marksibrahim** [comment] 2021-11-17 16:20
+1 for adding an option to disable SLURM signal handling. This conflicts with how other packages [Submitit](https://github.com/facebookincubator/submitit) handle pre-emption and requeuing. This has made it challenging to debug the source of issues around pre-emption.

**Comment by awaelchli** [comment] 2021-11-17 16:37
What if we let the cluster plugins configure signals?

**Comment by ananthsub** [comment] 2021-11-17 16:49
@awaelchli @carmocca since this support for resubmission is only or SLURM, we could either:
1. Add a flag to the SLURMEnvironment class like `auto_requeue`. To preserve backward compatibility, this is by default `True`. Users would need to specify `Trainer(..., plugins=[SLURMEnvironment(auto_requeue=False)], ...)` in their code. 

2. Or support an environment variable like `PL_SLURM_ENABLE_AUTO_REQUEUE` 

Whichever approach above is taken, the flag would need to be checked here: https://github.com/PyTorchLightning/pytorch-lightning/blob/ff3443fe42e9ad03e0604e50b0ae53f27ac2faac/pytorch_lightning/trainer/connectors/signal_connector.py#L52-L81

for whether we register the `slurm_sigusr1_handler_fn` or only disable job requeueing here: https://github.com/PyTorchLightning/pytorch-lightning/blob/ff3443fe42e9ad03e0604e50b0ae53f27ac2faac/pytorch_lightning/trainer/connectors/signal_connector.py#L58-L81

following this addition, we could determine whether to make this opt-in or opt-out

**Comment by awaelchli** [comment] 2021-11-17 23:00
Could the SLURM users comment on whether they prefer opt-in or opt-out, i.e., default `auto_requeue=False` vs `True`? @amogkam @import-antigravity @Queuecumber @marksibrahim

**Comment by Queuecumber** [comment] 2021-11-17 23:08
Opt-out, but that's mostly because I changed my submitit workflow to not requeue because lightning was doing it

**Comment by marksibrahim** [comment] 2021-11-17 23:16
Opt-out (`auto_requeue=False`) for me as well. I'd prefer to handle launching / requeuing outside of Lightning.

**Comment by Queuecumber** [comment] 2021-11-17 23:29
Ok so now I'm a little confused, I was reading opt-out as `auto_requeue=True` by default (i.e., you need to opt-out of requeueing)

**Comment by awaelchli** [comment] 2021-11-17 23:45
Yes @Queuecumber that's right.

In summary:

1) opt-out would be the explicit action of the user to not choose auto-requeue, i.e., they would have to set `auto_requeue=False` if they don't want it. Otherwise no action required (default is True).
2) opt-in would mean the user would explicitly have to set `auto_requeue=True` if they want it. Otherwise no action is required (default is False).

**Comment by marksibrahim** [comment] 2021-11-18 02:20
That was my confusion, my apologies. I prefer `auto_requeue=False` to be the default.  Both options are fine though, as long as there's a clear flag for the behavior.

**Comment by awaelchli** [comment] 2021-11-18 16:24
Opened PR #10601. Feel free to test or review it :)

**Closed** 2021-11-18 17:48 UTC
Labels: feature, help wanted, priority: 0, design, environment: slurm

**Comment by awaelchli** [comment] 2021-11-18 17:54
For now we went with the non-breaking change of setting `auto_requeue=True`. To turn it off, simply do
```python
Trainer(plugins=[SLURMEnvironment(auto_requeue=False)])
```
(for use with submitit for example). 

If we get more feedback from the PL SLURM community about switching to `auto_requeue=False` by default we can then make the decision. We will keep an eye out for SLURM users asking questions e.g. on slack and will be getting their feedback on this topic. 

If we were to flip the `auto_requeue` bool default, it would most likely be a warning in PL v1.X that the default is about to change in v1.(X+2) and v1.(X+2) would be the breaking change.

**Comment by DM-Berger** [comment] 2023-01-10 19:42
I also had this issue on a Compute Canada cluster where Lightning (version 1.8.1) by default tries to use invalid SLURM arguments (e.g. `--ntasks` instead of `--ntasks-per-node` and thus throws an error in interactive or non-interactive jobs. I was able to resolve the issue by subclassing the default `SLURMEnvironment` and over-riding all checks to make it look like no SLURM is available:

```python
from pytorch_lightning.plugins.environments import SLURMEnvironment

class DisabledSLURMEnvironment(SLURMEnvironment):
    def detect() -> bool:
        return False

    @staticmethod
    def _validate_srun_used() -> None:
        return

    @staticmethod
    def _validate_srun_variables() -> None:
        return

# ...

trainer = Trainer(
    accelerator="cpu",  # 
    plugins=[DisabledSLURMEnvironment(auto_requeue=False)],
    **kwargs,
)
```

This seemed to result in Lightning running as it does on my local testing maching.

**Comment by MewmewWho** [comment] 2023-03-15 03:02
Thanks @DM-Berger! I tried to run my training script within a Jupyter server terminal on the University of Arizona's HPC, and experienced exactly the same issue. With your solution, I just successfully ran my training. It seems good for now, and I'll make further comments if any error happens.

**Comment by awaelchli** [comment] 2023-03-15 10:04
Hey @DM-Berger and @MewmewWho 
I recently documented how to use Lightning with "interactive" mode here: https://lightning.ai/docs/pytorch/latest/clouds/cluster_advanced.html#interactive-mode

When you request the SLURM machine, just set the job name to "bash" and then Lightning will bypass the SLURM detection. Then you don't need to make code changes.

**Comment by fraolBatole** [comment] 2023-04-10 16:45
Thanks, @DM-Berger. I also faced a similar error (RuntimeError: You set --ntasks=8 in your SLURM bash script, but this variable is not supported. HINT: Use --ntasks-per-node=8 instead.), but it took me a while to find this page. I'm glad I finally found it, as it was very helpful in resolving the issue.

**Comment by SavvaI** [comment] 2023-05-21 08:04
> Hey @DM-Berger and @MewmewWho I recently documented how to use Lightning with "interactive" mode here: https://lightning.ai/docs/pytorch/latest/clouds/cluster_advanced.html#interactive-mode
> 
> When you request the SLURM machine, just set the job name to "bash" and then Lightning will bypass the SLURM detection. Then you don't need to make code changes.

From which PL version this feature is present? I tried to do it on 1.6.0 and it does not change anything.

**Comment by nikvaessen** [comment] 2024-03-14 09:45
> I also had this issue on a Compute Canada cluster where Lightning (version 1.8.1) by default tries to use invalid SLURM arguments (e.g. `--ntasks` instead of `--ntasks-per-node` and thus throws an error in interactive or non-interactive jobs. I was able to resolve the issue by subclassing the default `SLURMEnvironment` and over-riding all checks to make it look like no SLURM is available:
> 
> ```python
> from pytorch_lightning.plugins.environments import SLURMEnvironment
> 
> class DisabledSLURMEnvironment(SLURMEnvironment):
>     def detect() -> bool:
>         return False
> 
>     @staticmethod
>     def _validate_srun_used() -> None:
>         return
> 
>     @staticmethod
>     def _validate_srun_variables() -> None:
>         return
> 
> # ...
> 
> trainer = Trainer(
>     accelerator="cpu",  # 
>     plugins=[DisabledSLURMEnvironment(auto_requeue=False)],
>     **kwargs,
> )
> ```
> 
> This seemed to result in Lightning running as it does on my local testing maching.

This doesn't work (anymore), as the original `SlurmEnvironment` class is being used in 

https://github.com/Lightning-AI/pytorch-lightning/blob/1439da41b25a1efac581db35433e19e9d2b736d2/src/lightning/pytorch/trainer/connectors/accelerator_connector.py#L395C1

The solution is to monkey patch the detect method of `SLURMEnvironment`:

```python3
from lightning.pytorch.plugins.environments import SLURMEnvironment
SLURMEnvironment.detect = lambda: False
trainer = Trainer(...)
```

**Comment by shahin-trunk** [comment] 2024-06-03 07:52
You can also let SLURM schedule a machine for you and then log in to the machine to run scripts manually. This is useful for development and debugging. If you set the job name to bash or interactive, and then log in and run scripts, Lightning’s SLURM auto-detection will get bypassed and it can launch processes normally.

**Comment by kennyjoseph** [comment] 2025-04-25 15:08
I ended up going a different route since the above did not work for me anymore... I just added my chosen strategy as an argument to trainer with a particular lightning environment. New to `lightning` so would be curious if anyone with more experience has reason to tell me this was a bad idea :)

```
trainer = L.Trainer(
    ...
    strategy=DDPStrategy(cluster_environment=LightningEnvironment()),
    ...
)
```
