### ISSUE TITLE
Support Tensorboard logs dir structure costumizaton

### ISSUE THREAD

**Issue by edenlightning** [PyTorchLightning/pytorch-lightning#6019] opened 2021-02-16 19:16 UTC
Feature request:
As a user, i would like to have control over checkpoint dir name and structure.

Motivation: 
From @janhenriklambrechts (janhenrik.lambrechts@gmail.com):

My logging version directory of a single pytorch-lighting project with tensorboard logs looks something like this:

```
├── checkpoints
│   ├── epoch=86-max_acc=0.7446.ckpt
│   └── last.ckpt
├── events.out.tfevents.1613393562.lthpc.29645.0
├── hparams.yaml
├── train_acc_classifier_1
│   └── events.out.tfevents.1613393662.lthpc.29645.8
├── train_acc_classifier_2
│   └── events.out.tfevents.1613393662.lthpc.29645.7
├── train_acc_classifier_3
│   └── events.out.tfevents.1613393662.lthpc.29645.6
├── train_acc_classifier_4
│   └── events.out.tfevents.1613393662.lthpc.29645.5
├── val_acc_classifier_1
│   └── events.out.tfevents.1613393563.lthpc.29645.4
├── val_acc_classifier_2
│   └── events.out.tfevents.1613393563.lthpc.29645.3
├── val_acc_classifier_3
│   └── events.out.tfevents.1613393563.lthpc.29645.2
└── val_acc_classifier_4
    └── events.out.tfevents.1613393563.lthpc.29645.1
```
my network has multiple exits and I thus want to log the val_acc (or train_acc) of all these exits in a single graph which is why I need to log these setups as different runs.
As this is very unorganised and I would want to be able to in one scp -r call get all my tensorboard runs to my laptop.

Therefore I was wondering if there is a way in PL to log not directly in my version_0  folder but in version_0/tb_logs
I would want to be able to tell PL to save my logs in a subfolder tensorboard_logs as such that I only have two folders checkpoints  and tensorboard_logs in this version_0  directory.
I would have assumed that the log_dir  parameter of the TensorboardLogger would be this functionality, however in this case the checkpoints and logs are still together but now in a different main folder.

cc @borda @tchaton @justusschock @awaelchli @edward-io @ananthsub @rohitgr7 @kamil-kaczmarek @Raalsky @Blaizzy

**Comment by janhenriklambrechts** [comment] 2021-02-18 21:23
I propose a ```sub_dir``` argument for ```Logger``` objects. 

The default behaviour for multiple experiments and loggers right now looks something like this:

```
logs
└── default
    └── version_0
        ├── checkpoints
        │   └── epoch=85.ckpt
        ├── comet_log_0.out
        ├── comet_log_1.out
        ├── neptune_log_0.out
        ├── tensorboard_log_0.out
        ├── tensorboard_log_1.out
        └── tensorboard_log_2.out
```

With `sub_dir="tensorboard_logs"` (and `"comet_logs"`, `"neptune_logs"` respectively) it will look something like this

```
logs
└── default
    └── version_0
        ├── checkpoints
        │   └── epoch=85.ckpt
        ├── comet_logs
        │   ├── comet_log_0.out
        │   └── comet_log_1.out
        ├── neptune_logs
        │   └── neptune_log_0.out
        └── tensorboard_logs
            ├── tensorboard_log_0.out
            ├── tensorboard_log_1.out
            └── tensorboard_log_2.out
```

- I think creating a subdirectory for these logs should also be default behaviour. - given that I see no default usecase for not wanting a `sub_dir` but do consider having subfolders expected behaviour with multiple loggers/experiments. 
- Moreover, checkpoints are automatically grouped into a directory as well even if there is only one checkpoint being saved - so it makes sense from a design point as well.
- If there are good reasons against this being the default, we could leave `sub_dir=None` as the default argument instead.

Happy to create a PR for this, or discussing concerns with this approach 😊

**Comment by daniellepintz** [comment] 2022-02-05 20:28
Should we close this issue since it was done in https://github.com/PyTorchLightning/pytorch-lightning/pull/6195?

**Closed** 2022-02-05 22:37 UTC
Labels: feature, help wanted, design, logger
