### ISSUE TITLE
Refactoring GIF pl.TrainResult is (deprecated) Gif needs to be updated.

### ISSUE THREAD

**Issue by aribornstein** [PyTorchLightning/pytorch-lightning#5557] opened 2021-01-18 17:00 UTC
## 📚 Documentation

The example gif showing refactoring needs to be updated as the reference to pl.TrainResult has been deprecated. 

![image](https://user-images.githubusercontent.com/3045407/104943873-0dcb8780-59bf-11eb-8a37-ec2187171bdf.png)

![](https://github.com/PyTorchLightning/pytorch-lightning/raw/master/docs/source/_images/general/pl_quick_start_full_compressed.gif)

Thanks!

**Comment by carmocca** [comment] 2021-01-18 21:15
Duplicate of https://github.com/PyTorchLightning/pytorch-lightning/issues/4227

**Closed by carmocca** 2021-01-18 21:15 UTC
Labels: documentation
