### ISSUE TITLE
If train_step returns None, callback_metrics is empty

### ISSUE THREAD

**Issue by gibiansky** [PyTorchLightning/pytorch-lightning#4679] opened 2020-11-15 01:19 UTC
## 🐛 Bug

The title says it all: if, instead of returning a Tensor, I return None from train_step (w/ automatic_optimization=False, though I think this is irrelevant), then trainer.callback_metrics is not populated and is empty during the callbacks.

It's weird that these two things are associated, they seem very different parts of the codebase.

Expected: callback_metrics is populated in the same way regardless of return value of training_step. If returning None is not valid, an error should be raised.

**Comment by Borda** [comment] 2020-11-15 09:57
@gibiansky mind share your PL version and some more configuration details?

**Comment by edenlightning** [comment] 2020-11-16 16:19
Can you try to see if this issue persists on master?

**Comment by felixkreuk** [comment] 2020-11-20 07:57
I experience the same behavior on 1.0.7.
Can be mitigated by returning `{}` (empty dict) in `training_step`, thought it definitely looks like a bug.

**Comment by SkafteNicki** [comment] 2020-11-24 15:44
@felixkreuk, @gibiansky I was not able to reproduce using master (see this [notebook](https://colab.research.google.com/drive/14j-13Ij-fsbKQKPa7kxeD5SgOu1qGLTI?usp=sharing)). Can one of you check if master have indeed solved the problem?

**Comment by felixkreuk** [comment] 2020-11-29 16:09
@SkafteNicki not sure about master, but seems to work ok for 1.0.8

**Comment by felixkreuk** [comment] 2020-11-29 18:49
@SkafteNicki issue doesn't exist on master. still exists on 1.0.8 though.

**Comment by SkafteNicki** [comment] 2020-11-30 06:51
@felixkreuk thanks for confirming. Then please update to master, or wait for next release. Closing this issue.

**Closed by SkafteNicki** 2020-11-30 06:51 UTC
Labels: Metrics, bug / fix, help wanted, waiting on author
