### ISSUE TITLE
How optimizer frequencies works

### ISSUE THREAD

**Issue by 7rick03ligh7** [PyTorchLightning/pytorch-lightning#3481] opened 2020-09-12 18:39 UTC
#### What is your question?

I don't understand how optimizer frequencies works
https://github.com/PyTorchLightning/pytorch-lightning/pull/1269

#### Code

When I tried to work with them as a list of optimizers, I got this error
It arises after training_step()
![image](https://user-images.githubusercontent.com/15386257/93002389-aa919a80-f571-11ea-991e-18aee99376d5.png)

#### What's your environment?

 - OS: [Win]
 - Packaging [conda]
 - Version [0.9.0]

#### P.S.

If you have a pytorch-lightning WGAN implementation or something with n_critics I would appreciate if you could share )

**Comment by rohitgr7** [comment] 2020-09-12 18:49
it's fixed on master #3229

**Comment by 7rick03ligh7** [comment] 2020-09-12 19:14
@rohitgr7 
Oh, thanks
But... How can I install from master in conda?

**Comment by awaelchli** [comment] 2020-09-12 19:15
`pip install --upgrade git+https://github.com/PyTorchLightning/pytorch-lightning.git` in your conda env

**Comment by 7rick03ligh7** [comment] 2020-09-13 00:51
Ok, but I'm still interested in the sequence of function calls.

1) Am I right that the pseudocode with multiple optimizers looks like this?
![image](https://user-images.githubusercontent.com/15386257/93007657-13930580-f5a6-11ea-8578-6efca317b09c.png)


2) If I use multiple optimizers with different outputs in training_step() how it will work in training_epoch_end()? I mean how I can aggregate outputs only from the first optimizer and something like that. In other words, how structured outputs from different optimizers in training_epoch_end() 
![image](https://user-images.githubusercontent.com/15386257/93007679-3d4c2c80-f5a6-11ea-8435-a2a581000273.png)

**Comment by awaelchli** [comment] 2020-09-13 01:41
1. I think yes, this is roughly it
2. With multiple optimizers, you will get a list of lists in `training_epoch_end`. If using Results, you get List[List[Result]] and with dict you get List[List[dict]]. The top list has length equal to the number of optimizers. The inner list has length equal to the number of training steps.
3. Don't know, never tried it, but I would assume the progress bar dict gets merged.

**Comment by 7rick03ligh7** [comment] 2020-09-14 16:04
@awaelchli 
Thanks for the reply

I tried it and got this:
![image](https://user-images.githubusercontent.com/15386257/93109455-0897bc80-f6ef-11ea-9009-5518cdc28934.png)
All outputs from optimizers sent to a single list
Remind that I used frequencies (opt1 freq=1, opt2 freq=4)

Is it ok, or it's a bug?

**Comment by rohitgr7** [comment] 2020-09-14 17:25
@7rick03ligh7 
if you are using multiple optimizers with no frequencies defined you will get:
> With multiple optimizers, you will get a list of lists in training_epoch_end. If using Results, you get List[List[Result]] and with dict you get List[List[dict]]. The top list has a length equal to the number of optimizers. The inner list has a length equal to the number of training steps.

but, when you have some frequencies defined, each training_step will use only 1 optimizer depending upon the current training_step, and outputs from the other step with different optimizer won't be transferred. So you will have a list with the size equal to the number of training_steps.

Your output is excepted so it's not a bug.

**Comment by awaelchli** [comment] 2020-09-16 11:41
@rohitgr7 yes! subtle difference there, but very important! this is indeed working as intended. 
@7rick03ligh7 for reference, what @rohitgr7 explained is also written here in the "Note" section:
https://pytorch-lightning.readthedocs.io/en/latest/api/pytorch_lightning.core.html#pytorch_lightning.core.LightningModule.configure_optimizers

**Comment by 7rick03ligh7** [comment] 2020-09-16 15:10
@awaelchli yeah, but in the documentation, it is not clear that with frequencies the outputs will be in a single list (at least for me)

**Closed** 2020-09-16 15:14 UTC
Labels: question
