### ISSUE TITLE
Allow for additional options for self.log(..., reduce_fx={min,max,mean,sum}). 

### ISSUE THREAD

**Issue by dschmidt-rekor** [PyTorchLightning/pytorch-lightning#8941] opened 2021-08-16 20:45 UTC
## 🚀 Feature

Allow additional options for reduce_fx functions. This was supported previously (tested working on 1.3.0) and is no longer supported.

### Motivation

I'd like additional aggregation function choices (user defined and numpy-based for reduce_fx) functions, to be logged. 
Specifically, I'm running a multitarget training with potential nans, so would like to use my own nanmean method)

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

<sub>

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, finetuning and solving problems with deep learning

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks and more for research and production with PyTorch Lightning and PyTorch

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

</sub>

**Comment by tchaton** [comment] 2021-08-16 21:27
I would recommend to implement you own TorchMetrics object.

**Comment by carmocca** [comment] 2021-08-18 12:47
Duplicate of #8894 

Discussion can be continued there 🙂

**Closed by carmocca** 2021-08-18 12:47 UTC
Labels: enhancement, help wanted, logging
