### ISSUE TITLE
Number of steps per epoch

### ISSUE THREAD

**Issue by celsofranssa** [PyTorchLightning/pytorch-lightning#5449] opened 2021-01-10 15:26 UTC
Some learning rate schedulers as [OneCycleLR](https://pytorch.org/docs/stable/optim.html#torch.optim.lr_scheduler.OneCycleLR) requires the number of steps per epoch.

Then, how to get the number of steps in `configure_optimizers(self)` scope?

Note: Training data is given during `Trainer` instantiation:
```python
# training
    dm.setup('fit')
    trainer.fit(model, datamodule=dm)
```

**Comment by tchaton** [comment] 2021-01-11 10:36
Could you try this:
 
```
def configure_optimizers(self):
       num_batches = len(self.trainer.datamodule.train_dataloader()) / self.trainer.accumulate_grad_baches
      ....
      return [optim..], [scheduler...]

```


Here is a good approximation for the total number of steps. 
```    
    @property
    def num_training_steps(self) -> int:
        """Total training steps inferred from datamodule and devices."""
        if self.trainer.max_steps:
            return self.trainer.max_steps

        dataset_size = (
            self.trainer.limit_train_batches
            if self.trainer.limit_train_batches != 0
            else len(self.trainer.datamodule.train_dataloader())
        )

        num_devices = max(1, self.trainer.num_gpus, self.trainer.num_processes)
        if self.trainer.tpu_cores:
            num_devices = max(num_devices, self.trainer.tpu_cores)

        effective_batch_size = self.trainer.datamodule.batch_size * self.trainer.accumulate_grad_batches * num_devices
        return (dataset_size // effective_batch_size) * self.trainer.max_epochs
```

**Comment by celsofranssa** [comment] 2021-01-11 14:04
When using `num_batches = len(self.train_dataloader()) / self.trainer.accumulate_grad_baches`, the following error happens:

```python
Traceback (most recent call last):
  File "xCoFormer.py", line 169, in perform_tasks
    fit(hparams)
  File "xCoFormer.py", line 84, in fit
    trainer.fit(model, datamodule=dm)
  File "/home/celso/projects/venvs/xCoFormer/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 456, in fit
    self.accelerator_backend.setup(model)
  File "/home/celso/projects/venvs/xCoFormer/lib/python3.7/site-packages/pytorch_lightning/accelerators/gpu_accelerator.py", line 52, in setup
    self.setup_optimizers(model)
  File "/home/celso/projects/venvs/xCoFormer/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 145, in setup_optimizers
    optimizers, lr_schedulers, optimizer_frequencies = self.trainer.init_optimizers(model)
  File "/home/celso/projects/venvs/xCoFormer/lib/python3.7/site-packages/pytorch_lightning/trainer/optimizers.py", line 30, in init_optimizers
    optim_conf = model.configure_optimizers()
  File "/home/celso/projects/xCoFormer/source/model/JointEncoder.py", line 44, in configure_optimizers
    print("num_batches: ", len(self.train_dataloader()) / self.trainer.accumulate_grad_baches)
AttributeError: 'Trainer' object has no attribute 'accumulate_grad_baches'
```

**Comment by celsofranssa** [comment] 2021-01-11 14:57
> Closing this issue as the answer should work out. Feel free to re-open it if it doesn't solve your problem.

Did you mean create a new issue?

**Comment by rohitgr7** [comment] 2021-01-11 15:45
@celsofranssa it's `self.trainer.accumulate_grad_baches`. just a typo there.

**Comment by celsofranssa** [comment] 2021-01-11 16:05
I got it, thanks!

**Comment by celsofranssa** [comment] 2021-01-14 14:04
> This should work just fine.
> 
> ```
> def configure_optimizers(self):
>        num_batches = len(self.train_dataloader()) / self.trainer.accumulate_grad_batches
>       ....
>       return [optim..], [scheduler...]
> ```
> 
> Note: If you pass for train/val_dataloader or datamodule directly into the `.fit` function, Lightning will override the train_dataloader() function with the provided one, so it should work fine.
> 
> Here is a good approximation for the total number of steps.
> 
> ```
>     @property
>     def num_training_steps(self) -> int:
>         """Total training steps inferred from datamodule and devices."""
>         dataset = self.train_dataloader()
>         if self.trainer.max_steps:
>             return self.trainer.max_steps
> 
>         dataset_size = (
>             self.trainer.limit_train_batches
>             if self.trainer.limit_train_batches != 0
>             else len(dataset)
>         )
> 
>         num_devices = max(1, self.trainer.num_gpus, self.trainer.num_processes)
>         if self.trainer.tpu_cores:
>             num_devices = max(num_devices, self.trainer.tpu_cores)
> 
>         effective_batch_size = dataset.batch_size * self.trainer.accumulate_grad_batches * num_devices
>         return (dataset_size // effective_batch_size) * self.trainer.max_epochs
> ```
> 
> Closing this issue as the answer should work out. Feel free to re-open it if it doesn't solve your problem.

`dataset_size` is being set to 1.0 instead of the real number of batches in the `dataloader` because:
```python
# default used by the Trainer
trainer = Trainer(limit_train_batches=1.0)
```

**Comment by KevinMusgrave** [comment] 2021-02-05 00:30
@tchaton I don't think the ```num_training_steps``` function works. As @celsofranssa pointed out, ```dataset_size``` gets set to 1, so the function returns 0 because ```(dataset_size // effective_batch_size)``` equals 0.

**Comment by tsteffek** [comment] 2021-02-05 19:52
I just stumbled upon the same problem, and tried `len(self.train_dataloader()) // self.trainer.accumulate_grad_batches`. Works for me.

Your misunderstanding is that `dataset_size` sets the size to `1`. Note that the default is `1.0`, a float. Floats will be used to scale the actual size: The default is therefore `actual_size * 1.0`.

Then again, I'm not opposed to a convenience function/parameter `steps_per_epoch`.

**Comment by KevinMusgrave** [comment] 2021-02-05 20:13
I was referring to the ```num_training_steps```:

> Here is a good approximation for the total number of steps.
> 
> ```
>     @property
>     def num_training_steps(self) -> int:
>         """Total training steps inferred from datamodule and devices."""
>         dataset = self.train_dataloader()
>         if self.trainer.max_steps:
>             return self.trainer.max_steps
> 
>         dataset_size = (
>             self.trainer.limit_train_batches
>             if self.trainer.limit_train_batches != 0
>             else len(dataset)
>         )
> 
>         num_devices = max(1, self.trainer.num_gpus, self.trainer.num_processes)
>         if self.trainer.tpu_cores:
>             num_devices = max(num_devices, self.trainer.tpu_cores)
> 
>         effective_batch_size = dataset.batch_size * self.trainer.accumulate_grad_batches * num_devices
>         return (dataset_size // effective_batch_size) * self.trainer.max_epochs
> ```

**Comment by tsteffek** [comment] 2021-02-05 20:18
Oh, that `dataset_size`. Same name everywhere, it's too confusing. Sorry then.

**Comment by rohitgr7** [comment] 2021-02-05 20:18
```python
@property
def num_training_steps(self) -> int:
    """Total training steps inferred from datamodule and devices."""
    if self.trainer.max_steps:
        return self.trainer.max_steps

    limit_batches = self.trainer.limit_train_batches
    batches = len(self.train_dataloader())
    batches = min(batches, limit_batches) if isinstance(limit_batches, int) else int(limit_batches * batches)     

    num_devices = max(1, self.trainer.num_gpus, self.trainer.num_processes)
    if self.trainer.tpu_cores:
        num_devices = max(num_devices, self.trainer.tpu_cores)

    effective_accum = self.trainer.accumulate_grad_batches * num_devices
    return (batches // effective_accum) * self.trainer.max_epochs
```
@tsteffek @KevinMusgrave this shall work? pls, do let me know if I missed any edge cases, will update.

**Comment by KevinMusgrave** [comment] 2021-02-05 20:29
@rohitgr7 Thanks, that seems to work 👍

**Comment by tsteffek** [comment] 2021-02-05 20:46
So I've been thinking that I've seen that functionality somewhere, and indeed there is a `trainer.num_training_batches`.

Caveat: it's 0 at the time of `configure_optimizers`, sadly.

**Comment by igolan89** [comment] 2021-06-25 13:49
> ```python
> @property
> def num_training_steps(self) -> int:
>     """Total training steps inferred from datamodule and devices."""
>     if self.trainer.max_steps:
>         return self.trainer.max_steps
> 
>     limit_batches = self.trainer.limit_train_batches
>     batches = len(self.train_dataloader())
>     batches = min(batches, limit_batches) if isinstance(limit_batches, int) else int(limit_batches * batches)     
> 
>     num_devices = max(1, self.trainer.num_gpus, self.trainer.num_processes)
>     if self.trainer.tpu_cores:
>         num_devices = max(num_devices, self.trainer.tpu_cores)
> 
>     effective_accum = self.trainer.accumulate_grad_batches * num_devices
>     return (batches // effective_accum) * self.trainer.max_epochs
> ```
> 
> @tsteffek @KevinMusgrave this shall work? pls, do let me know if I missed any edge cases, will update.

Does this still hold for multi-node training? I think `self.trainer.num_gpus` only registers number of gpus per host, not the global amount

**Comment by cowwoc** [comment] 2021-09-03 04:46
The above functions did not yield the correct number of steps per epoch for me so I dug into the source code of progress.py `on_train_epoch_start(self, trainer, pl_module)` and came up with this:

```
    @property
    def total_train_batches(self) -> int:
        """
        The total number of training batches during training, which may change from epoch to epoch.
        """
        return math.ceil(len(self.train_dataset) / self.batch_size)

    @property
    def total_val_batches(self) -> int:
        """
        The total number of validation batches during validation, which may change from epoch to epoch.
        """
        total_val_batches = 0
        if self.trainer.enable_validation:
            is_val_epoch = (self.trainer.current_epoch + 1) % self.trainer.check_val_every_n_epoch == 0
            total_val_batches = math.ceil(len(self.val_dataset) / self.batch_size) if is_val_epoch else 0
        return total_val_batches

    @property
    def training_steps_per_epoch(self) -> int:
        """
        The number of training steps per epoch.

        Taken from progress.py on_train_epoch_start(self, trainer, pl_module)
        """
        total_train_batches = self.total_train_batches
        total_val_batches = self.total_val_batches

        # val can be checked multiple times per epoch
        val_check_batch = int(total_train_batches * self.trainer.val_check_interval)
        val_check_batch = max(1, val_check_batch)
        val_checks_per_epoch = total_train_batches // val_check_batch

        total_val_batches = total_val_batches * val_checks_per_epoch
        return total_train_batches + total_val_batches
```

Now the function returns the same number of steps per epoch as the progress bar and can be invoked from `configure_optimizers()`. I hope this helps someone else.

**Comment by tchaton** [comment] 2021-09-03 08:08
Hey @cowwoc,

I am not sure you should be using the progress bar as it counts the total number of batches across processes + adds validation.

I believed the previous implementation was more accurate.

Best,
T.C

**Comment by cowwoc** [comment] 2021-09-03 13:06
@tchaton Is it wrong to include the number of validation steps? Doesn't `lr_scheduler.step()` get invoked during validation as well?

**Comment by tchaton** [comment] 2021-09-03 13:31
No, it doesn't.

**Comment by cowwoc** [comment] 2021-09-03 13:43
@tchaton Okay, thanks for the clarification. Are there any plans to add this functionality (getting the number of steps per epoch or total number of steps) into the official API?

**Comment by rohitgr7** [comment] 2021-09-05 14:34
> Are there any plans to add this functionality (getting the number of steps per epoch or total number of steps) into the official API?

I think it might be a bit risky to add such a functionality since it calls `len(self.train_dataloader())` and we have an argument `reload_dataloader_every_n_epoch`. So there is a possibility of not having the same number of batches in each training epoch and since configure_optimizers is called just once, they might not sync up. There might be other issues as well since this depends on some dynamic variables which are prone to change while training.

**Comment by cowwoc** [comment] 2021-09-05 17:07
To which I say... If the committers can't figure out how to implement this safely, what chance do end-users have? :)

**Comment by RuRo** [comment] 2021-10-20 21:50
@tchaton do you mind reopening this issue? Since this seems to be such a non-trivial problem, perhaps lightning should provide `steps_per_epoch` (or `num_training_steps`) property out of the box?

**Comment by cowwoc** [comment] 2021-11-09 05:11
Watch out. Version 1.5.0 changes the default value of `max_steps` from `None` to `-1` so:

```
        if self.trainer.max_steps:
            return self.trainer.max_steps
```

has to be changed to:

```
        if self.trainer.max_steps != -1:
            return self.trainer.max_steps
```

**Comment by tchaton** [comment] 2021-12-10 09:12
Marking to keep it alive.

**Comment by cowwoc** [comment] 2022-01-15 07:42
Not stale.

**Comment by cowwoc** [comment] 2022-02-17 13:40
See related PR: https://github.com/PyTorchLightning/pytorch-lightning/pull/11599

**Comment by carmocca** [comment] 2022-04-06 04:09
Fixed with #11599

**Closed by carmocca** 2022-04-06 04:09 UTC
Labels: question, waiting on author

**Comment by JulesGM** [comment] 2022-09-08 21:57
@carmocca does this work with multi node training?

**Comment by carmocca** [comment] 2022-09-09 11:41
It should

**Comment by ayansengupta17** [comment] 2023-04-10 09:20
For `Lightning 2.0`
```
def num_steps(self) -> int:
        
        dataset = self.trainer.fit_loop._data_source.dataloader()
        dataset_size = len(dataset)
        num_devices = max(1, self.trainer.num_devices)
        num_steps = dataset_size * self.trainer.max_epochs // (self.trainer.accumulate_grad_batches * num_devices)
        return num_steps

```

**Comment by carmocca** [comment] 2023-04-10 15:12
@ayansengupta17 In your example, I suggest you access `trainer.train_dataloader` instead to access your original dataloader

**Comment by mwulmer** [comment] 2023-07-20 09:07
I am using `lightning 2.0.5` and it seems that `self.trainer.train_dataloader` returns the combined dataloader and `len(self.trainer.train_dataloader) = len(dataset)/(batchsize * num_devices)`. Can somebody confirm that? The function I am using is:

```
@property
def num_training_steps(self) -> int:
    """Get number of training steps"""
    if self.trainer.max_steps > -1:
        return self.trainer.max_steps

    self.trainer.fit_loop.setup_data()
    dataset_size = len(self.trainer.train_dataloader)
    num_steps = dataset_size * self.trainer.max_epochs

    return num_steps
```

**Comment by rachtibat** [comment] 2023-12-21 19:31
It is important to return in configure_optimizers
`return [optimizer], [{"scheduler": scheduler, "interval": "step"}]`

and then

```
@property
def num_training_steps(self) -> int:
    """Get number of training steps"""
    if self.trainer.max_steps > -1:
        return self.trainer.max_steps

    self.trainer.fit_loop.setup_data()
    dataset_size = len(self.trainer.train_dataloader)
    num_steps = dataset_size * self.trainer.max_epochs // (self.trainer.accumulate_grad_batches * num_devices)
    return num_steps
```

works superb!

**Comment by alancneves** [comment] 2024-01-10 19:09
> I am using `lightning 2.0.5` and it seems that `self.trainer.train_dataloader` returns the combined dataloader and `len(self.trainer.train_dataloader) = len(dataset)/(batchsize * num_devices)`. Can somebody confirm that? The function I am using is:
> 
> ```
> @property
> def num_training_steps(self) -> int:
>     """Get number of training steps"""
>     if self.trainer.max_steps > -1:
>         return self.trainer.max_steps
> 
>     self.trainer.fit_loop.setup_data()
>     dataset_size = len(self.trainer.train_dataloader)
>     num_steps = dataset_size * self.trainer.max_epochs
> 
>     return num_steps
> ```

I can confirm that `len(self.trainer.train_dataloader) = len(dataset)/(batchsize * num_devices)`.
In my case, I've to change your last line to include the accumulated_gradient, leading to:
```num_steps = dataset_size * self.trainer.max_epochs // self.trainer.accumulate_grad_batches```

Worked perfectly!
