### ISSUE TITLE
WandB Logger always resumes even when `Trainer(resume_from_checkpoing=None)`

### ISSUE THREAD

**Issue by Laksh1997** [PyTorchLightning/pytorch-lightning#2470] opened 2020-07-02 16:05 UTC
## 🐛 Bug

@awaelchli As requested, bug above in the title.

### To Reproduce

```python
model = CoolSystem.load_from_checkpoint(checkpoint)
logger = WandbLogger()
trainer = Trainer(resume_from_checkpoint=None)
trainer.fit(model)
```

The above resumes the wandb run.

PL 0.8.4

 - PyTorch Version (e.g., 1.0): 1.6 nightly
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): Conda
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version:
 - GPU models and configuration: V100
 - Any other relevant information:

**Comment by awaelchli** [comment] 2020-07-05 06:10
@Laksh1997 I simply cannot reproduce this, I tried in several ways, online, offline, with and without checkpoints etc.. Did you set any environment variables related to WandB?
If possible, could you post a full code sample or Google colab?
Thanks

**Comment by edenlightning** [comment] 2020-07-28 20:31
Closing this. @Laksh1997 please reopen if still relevant.

**Closed by edenlightning** 2020-07-28 20:31 UTC
Labels: bug / fix, help wanted, information needed
