### ISSUE TITLE
Metrics: MSE, RMSE, MAE, RMSLE

### ISSUE THREAD

**Issue by justusschock** [PyTorchLightning/pytorch-lightning#1304] opened 2020-03-30 13:17 UTC
## 🚀 Feature
Implement the following as metrics (grouped due to similarity):
- [ ] MSE
- [ ] RMSE
- [ ] MAE
- [ ] RMSLE

> Note: Probably it suffices for some of them to derive a new class from the loss variant in `torch.nn` and the `BaseMetric` class

**Comment by Borda** [comment] 2020-06-16 23:46
@cuent ^^ mind type anything so I can assign it to you... :rabbit:

**Comment by cuent** [comment] 2020-06-16 23:54
Thanks 😄 Will try to push tmrr!

**Closed** 2020-06-17 17:46 UTC
Labels: enhancement, good first issue, help wanted

**Comment by flxai** [comment] 2023-02-22 15:16
For anyone landing here from a search engine: The situation has changed since 2020 and almost all are available in [TorchMetrics](https://torchmetrics.readthedocs.io/en/latest/), [an official PyTorch Lightning project to outsource metrics](https://www.pytorchlightning.ai/blog/torchmetrics-pytorch-metrics-built-to-scale).

* [MSE](https://torchmetrics.readthedocs.io/en/stable/regression/mean_squared_error.html)
* RMSE
  * `torch.sqrt(mse(y, y_hat))`
* [MAE](https://torchmetrics.readthedocs.io/en/stable/regression/mean_absolute_error.html)
* RMSLE
  * `torch.sqrt(msle(y, y_hat))`
  * Using [MSLE](https://torchmetrics.readthedocs.io/en/stable/regression/mean_squared_log_error.html)
