### ISSUE TITLE
Image not logged to TensorBoard if it is last operation in on_test_epoch_end

### ISSUE THREAD

**Issue by LucaButera** [PyTorchLightning/pytorch-lightning#4858] opened 2020-11-25 17:39 UTC
## 🐛 Bug

When testing a model and logging an image to tensor board during last epoch's ```on_test_epoch_end``` the image does not appear in tensorboard.
Anyway if I add a ```sleep``` after the line that logs the image, or if I reduce the image size, the problem disappears and the image is correctly logged.
I reasoned that somehow the process that logs to tensorboard is quickly killed due to the run finishing hence it is not able to complete the logging task. But I have no way to be sure.

## Please reproduce using the BoringModel and post here
I would like to do so but if I run the raw [BoringModel](https://colab.research.google.com/drive/1HvWVVTK8j2Nj52qU4Q4YCyzOm0_aLQF3?usp=sharing) I get the following error ```MisconfigurationException: ckpt_path is "best", but ModelCheckpoint is not configured to save the best model.``` upon calling ```text_x```

### To Reproduce
It should be equivalent to add to any model the following method
```
def on_test_epoch_end(self) -> None:
    if isinstance(self.logger, pytorch_lightning.loggers.TensorBoardLogger):
        self.logger.experiment.add_image('test_image',
                                             torch.ones((3, 948, 1248), dtype=torch.float32),
                                             self.global_step)
```

### Expected behavior

I expect the image to show up on TensorBoard each time I call a logging method.

### Environment

 - PyTorch Version: 1.7.0
 - OS: macOS 11.0.1
 - How you installed PyTorch: `pip`
 - Python version: 3.8.3
 - CUDA/cuDNN version: None
 - GPU models and configuration: None
 - Any other relevant information: None

**Comment by Borda** [comment] 2020-11-30 10:20
@LucaButera mind share what PL version are you using?

**Comment by LucaButera** [comment] 2020-11-30 10:25
@Borda Sure, version is 1.0.7
On a side note, I installed using ```poetry``` but I guess this does not differ from a normal ```pip install```.

**Comment by janhenriklambrechts** [comment] 2020-12-01 15:34
Happy to help with this one :)

**Comment by LucaButera** [comment] 2020-12-01 16:43
@janhenriklambrechts I just tried with the BoringModel again and now, for whatever reason, I am able to run the notebook.

I have not been able to reproduce the bug in Colab. I tried with ```fast_dev_run=True```, which is the setting I am using locally, and with a normal run. In both cases I could visualize the image in TensorBoard.

Mind that the bug still persists on my local machine, even in ```pytorch-lightning==1.0.8```. 
One thing I noticed is that if my image is completely black (so full of 0s) it gets correctly logged.

If I have enough time, tomorrow I will try running the dummy experiment locally, both with and without ```fast_dev_run``` set, to see what happens.

**Comment by janhenriklambrechts** [comment] 2020-12-02 13:20
@LucaButera so far, I have been unable to reproduce this issue. As you mention that a completely black image does get logged properly it does not seem like this problem would exist because of killing the logging before it completed.

Just as a sanity check, in your steps to reproduce you use a tensor.zeros() image which will show up completely white which might seem like the image does not get logged as it blends in with the background: 

![image](https://user-images.githubusercontent.com/31068156/100877434-10266080-34a9-11eb-9b83-8122212826b4.png)

However, when we adjust the brightness and contrast sliders we can see that the image did log properly, in fact:

![image](https://user-images.githubusercontent.com/31068156/100877536-34823d00-34a9-11eb-85f7-586178918af6.png)

Let me know if the image does show up when adjusting the sliders, or if this has nothing do do with your issue :)

**Comment by LucaButera** [comment] 2020-12-02 13:35
@janhenriklambrechts Sadly this does not solve the problem. Adjusting sliders doesn't help as the image is not there at all.
I tried using a ```torch.rand()``` that produces a sort of white noise image and it also fails to show. 
I will try to reproduce the bug with minimal code on my machine, just to check if it could be a side effect of some sort.

In the meantime, may I ask what OS are you running this on? I am on macOS, I don't know if this could be a relevant factor, but I think something about multiprocessing is handled differently than in Linux, and the fact that I haven't been able to reproduce the bug in Colab points me in that direction. But I may be on the wrong track.

**Comment by janhenriklambrechts** [comment] 2020-12-02 13:43
@LucaButera I am using Linux indeed, dont really have the option of testing this on macOS atm. Testing locally with a minimal example (f.e. BoringModel) would indeed be useful so we can narrow this down.

**Comment by Borda** [comment] 2020-12-04 14:24
@LucaButera you shared the boring model example but the missing image is hot happening there, right?

**Comment by LucaButera** [comment] 2020-12-04 14:33
@Borda that's correct. As I said I think it is mandatory that I perform a minimal reproduction of the bug on my machine. This would help understanding what could be the cause.

**Comment by rohitgr7** [comment] 2020-12-04 14:37
can you try this with some other logger, if possible? This way we can know whether it is an issue with TensorboardLogger only or others too.

**Comment by LucaButera** [comment] 2020-12-04 14:45
@rohitgr7 I'll do that, but I think I will not have time until next week.
Could you advise which logger with image logging capabilities is easier to setup and test?

**Comment by borisdayma** [comment] 2020-12-09 15:17
For info, if using wandb here is the [relevant documentation](https://docs.wandb.com/library/log#images-and-overlays).

**Comment by LucaButera** [comment] 2020-12-09 16:46
A small update on the local tests:

Wandb logger seems to log the image correctly in the same conditions. I don't know if this is actually relevant. Cause in both cases, to log images, you need to directly use the underlying logger via ```self.logger.experiment```

I have been able to reproduce the bug on my local machine, in the same environment that originally generated the bug. The code I used is the following:

```python
import pytorch_lightning as pl
import torch
from torch.utils.data import DataLoader, Dataset


class RandomDataset(Dataset):
    def __init__(self, size, num_samples):
        self.len = num_samples
        self.data = torch.randn(num_samples, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(pl.LightningModule):

    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def loss(self, batch, prediction):
        # An arbitrary loss to have a loss that updates the model weights during `Trainer.fit` calls
        return torch.nn.functional.mse_loss(prediction, torch.ones_like(prediction))

    def training_step(self, batch, batch_idx):
        output = self.layer(batch)
        loss = self.loss(batch, output)
        return {"loss": loss}

    def training_step_end(self, training_step_outputs):
        return training_step_outputs

    def training_epoch_end(self, outputs) -> None:
        torch.stack([x["loss"] for x in outputs]).mean()

    def validation_step(self, batch, batch_idx):
        output = self.layer(batch)
        loss = self.loss(batch, output)
        return {"x": loss}

    def validation_epoch_end(self, outputs) -> None:
        torch.stack([x['x'] for x in outputs]).mean()

    def test_step(self, batch, batch_idx):
        output = self.layer(batch)
        loss = self.loss(batch, output)
        self.log('fake_test_acc', loss)
        return {"y": loss}

    def test_epoch_end(self, outputs) -> None:
        torch.stack([x["y"] for x in outputs]).mean()

    def configure_optimizers(self):
        optimizer = torch.optim.SGD(self.layer.parameters(), lr=0.1)
        lr_scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=1)
        return [optimizer], [lr_scheduler]

    def on_test_epoch_end(self) -> None:
        self.logger.experiment.add_image('test_image',
                                         torch.rand((3, 2000, 2500), dtype=torch.float32),
                                         self.global_step)


def main():
    # init model
    model = BoringModel()
    # init dummy datasets
    num_samples = 10000
    b_size = 32
    train = RandomDataset(b_size, num_samples)
    train = DataLoader(train, batch_size=b_size)
    val = RandomDataset(b_size, num_samples)
    val = DataLoader(val, batch_size=b_size)
    test = RandomDataset(b_size, num_samples)
    test = DataLoader(test, batch_size=b_size)
    # Initialize a trainer
    trainer = pl.Trainer(
        max_epochs=1,
        progress_bar_refresh_rate=20,
    )
    # Train and test the model ⚡
    trainer.fit(model, train, val)
    trainer.test(test_dataloaders=test)


if __name__ == '__main__':
    main()

```

This is the output of the env details collector script run on my local machine.
```
* CUDA:
	- GPU:
	- available:         False
	- version:           None
* Packages:
	- numpy:             1.19.4
	- pyTorch_debug:     True
	- pyTorch_version:   1.7.0
	- pytorch-lightning: 1.0.8
	- tqdm:              4.54.0
* System:
	- OS:                Darwin
	- architecture:
		- 64bit
		- 
	- processor:         i386
	- python:            3.8.3
	- version:           Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64
```

Next thing I will try is to reproduce the bug on a minimal environment.

**Comment by LucaButera** [comment] 2020-12-09 17:01
A quick followup. I managed to reproduce the issue on a minimal environment consisting of the following packages:
```bash
Package                Version
---------------------- ---------
absl-py                0.11.0
cachetools             4.1.1
certifi                2020.12.5
chardet                3.0.4
dataclasses            0.6
fsspec                 0.8.4
future                 0.18.2
google-auth            1.23.0
google-auth-oauthlib   0.4.2
grpcio                 1.34.0
idna                   2.10
Markdown               3.3.3
numpy                  1.19.4
oauthlib               3.1.0
Pillow                 8.0.1
pip                    20.2.4
protobuf               3.14.0
pyasn1                 0.4.8
pyasn1-modules         0.2.8
pytorch-lightning      1.0.8
PyYAML                 5.3.1
requests               2.25.0
requests-oauthlib      1.3.0
rsa                    4.6
setuptools             50.3.2
six                    1.15.0
tensorboard            2.4.0
tensorboard-plugin-wit 1.7.0
torch                  1.7.0
tqdm                   4.54.1
typing-extensions      3.7.4.3
urllib3                1.26.2
Werkzeug               1.0.1
wheel                  0.35.1
```

Produced by running ```poetry add pytorch-lightning Pillow``` on a clean environment.
The code used is the same shown [previously](https://github.com/PyTorchLightning/pytorch-lightning/issues/4858#issuecomment-741897886)

As before, this is the output of the env details collector.
```bash
* CUDA:
	- GPU:
	- available:         False
	- version:           None
* Packages:
	- numpy:             1.19.4
	- pyTorch_debug:     True
	- pyTorch_version:   1.7.0
	- pytorch-lightning: 1.0.8
	- tqdm:              4.54.1
* System:
	- OS:                Darwin
	- architecture:
		- 64bit
		- 
	- processor:         i386
	- python:            3.8.3
	- version:           Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64
```

**Comment by janhenriklambrechts** [comment] 2020-12-10 14:46
Thanks @LucaButera, Ill use this extra info to try to reproduce this on Linux!

**Comment by janhenriklambrechts** [comment] 2020-12-12 21:15
Hi @LucaButera, I was able to reproduce the image not showing up as per the code example above.
However, the image did show up normally when instead of 

```python    
  def on_test_epoch_end(self) -> None:
        self.logger.experiment.add_image('test_image',
                                         torch.rand((3, 2000, 2500), dtype=torch.float32),
                                         self.global_step)
```

I use the following small modification and the image does show up:

```python
def on_test_epoch_end(self) -> None:
    if isinstance(self.logger, pytorch_lightning.loggers.TensorBoardLogger):
        self.logger.experiment.add_image('test_image',
                                             torch.ones((3, 948, 1248), dtype=torch.float32),
                                             self.global_step)
```

Can you confirm that this works with you as well?

**Comment by LucaButera** [comment] 2020-12-14 09:40
@janhenriklambrechts I tried using your code but it still does not work. However, if I keep making the image smaller and smaller, it eventually gets logged. I don't think the ```if``` condition plays any role in this, as if the ```logger``` was not a ```TensorBoardLogger``` the code would simply fail (either way it is a ```TensorBoardLogger```).

As I previously stated, this strengthens my belief that it is an issue with the main process terminating before the image has finished being logged. This would justify the fact that adding a ```sleep``` or using smaller images makes everything work.
What do you think about this?

**Comment by janhenriklambrechts** [comment] 2020-12-17 13:53
Hi @LucaButera, I have been scratching my head over your problem, as I have been able to log images of size up to 5000x5000, no problem. When I resize logging images to this size, lightning correctly waits for the image to finish logging when the epoch ends - so no sign of a Lightning bug.

One last proposition, sometimes Tensorboard will take some time in processing larger images so they may not show up in the beginning. However, if you wait for some seconds and then refresh your browser, you will see that these images were in fact properly logged.  If this does not fix your issue I will have to hand it over to someone with MacOS as they might be able to reproduce it. 

Thank you for your patience!

**Comment by LucaButera** [comment] 2020-12-17 14:20
@janhenriklambrechts Hey, actually I did refresh multiple times and also tried both Chrome and Safari to navigate TensorBoard. Sadly, at this point I'm pretty convinced it is a macOS issue.

**Comment by janhenriklambrechts** [comment] 2020-12-17 14:29
@Borda I did everything I could here, can we assign this to someone who can reproduce on MacOS?

**Comment by rohitgr7** [comment] 2020-12-18 17:52
since it's working with Wandb, I think it has something to do with `flush_secs` argument here: https://pytorch.org/docs/stable/tensorboard.html#torch.utils.tensorboard.writer.SummaryWriter

**Closed** 2021-01-25 00:22 UTC
Labels: 3rd-party, Priority P1, bug / fix, good first issue, help wanted, won't fix
